
import React, { useState, useEffect } from 'react';
import ToolTemplate from '@/components/ToolTemplate';
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { Calendar, Trash2, Send, Wand2, Copy, Plus, Clock, Twitter, Linkedin, ExternalLink, Image as ImageIcon, Download, Palette, X, Settings, Key, Facebook, Instagram, Share2, MessageCircle } from 'lucide-react';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import html2canvas from 'html2canvas';
import { generateGenericText, extractUrlContext, BlogGenerator } from '@/utils/aiGenerator';
// ... rest of imports
import { toast } from 'sonner';
import { format, addDays, startOfWeek, endOfWeek, eachDayOfInterval, isSameDay } from 'date-fns';

interface ScheduledPost {
    id: string;
    content: string;
    platform: 'twitter' | 'linkedin' | 'facebook';
    scheduledDate: string; // ISO String
    status: 'pending' | 'posted';
}

const SocialScheduler = () => {
    // State
    const [topic, setTopic] = useState('');
    const [tone, setTone] = useState('professional');
    const [platform, setPlatform] = useState<'twitter' | 'linkedin' | 'facebook'>('twitter');
    const [isGenerating, setIsGenerating] = useState(false);
    const [generatedPosts, setGeneratedPosts] = useState<string[]>([]);
    const [scheduledPosts, setScheduledPosts] = useState<ScheduledPost[]>([]);
    const [selectedDate, setSelectedDate] = useState<Date>(new Date());

    // Visual Creator State
    const [visualMode, setVisualMode] = useState(false);
    const [visualContent, setVisualContent] = useState('');
    const [visualBg, setVisualBg] = useState('bg-gradient-to-br from-purple-900 to-indigo-900');
    const [visualFontSize, setVisualFontSize] = useState(24);
    const [visualAuthor, setVisualAuthor] = useState(true);

    const [isGeneratingBg, setIsGeneratingBg] = useState(false);
    const [scrapedContext, setScrapedContext] = useState('');
    const [apiKey, setApiKey] = useState('');
    const [showSettings, setShowSettings] = useState(false);

    // Load API Key
    useEffect(() => {
        const key = localStorage.getItem('gemini_api_key');
        if (key) setApiKey(key);
    }, []);

    const saveApiKey = (key: string) => {
        setApiKey(key);
        localStorage.setItem('gemini_api_key', key);
    };

    const handleGenerateBackground = async () => {
        setIsGeneratingBg(true);
        // FORCE PICSUM (Guaranteed Visuals)
        try {
            // Seed includes timestamp to allow "Re-Rolling" the image
            const seedStr = (topic || "") + (visualContent || "random") + Date.now().toString();
            // Use a simple hash code for the seed
            let hash = 0;
            for (let i = 0; i < seedStr.length; i++) {
                hash = ((hash << 5) - hash) + seedStr.charCodeAt(i);
                hash |= 0;
            }
            const seed = Math.abs(hash);

            // Picsum URL - High Quality, Blur for style
            // We use 'seed' to make it deterministic for the topic
            const url = `https://picsum.photos/seed/${seed}/1080/1080?blur=2`;

            // Pre-load to valid
            const img = new Image();
            img.src = url;

            img.onload = () => {
                setVisualBg(url);
                toast.success("Background Applied! 🎨");
                setIsGeneratingBg(false);
            };

            img.onerror = () => {
                // Should almost never happen with Picsum
                console.error("Picsum failed");
                setVisualBg('bg-gradient-to-br from-purple-900 to-indigo-900');
                toast.error("Could not load image. Using Gradient.");
                setIsGeneratingBg(false);
            };

        } catch (e) {
            console.error(e);
            setIsGeneratingBg(false);
        }
    };

    const handleShare = (platform: string) => {
        const text = encodeURIComponent(`${visualContent}\n\nGenerated by Axevora Social Scheduler 🚀`);
        const url = encodeURIComponent("https://axevora.com");

        switch (platform) {
            case 'twitter':
                window.open(`https://twitter.com/intent/tweet?text=${text}&url=${url}`, '_blank');
                break;
            case 'linkedin':
                window.open(`https://www.linkedin.com/sharing/share-offsite/?url=${url}`, '_blank');
                break;
            case 'whatsapp':
                window.open(`https://wa.me/?text=${text}%20${url}`, '_blank');
                break;
            case 'reddit':
                window.open(`https://reddit.com/submit?url=${url}&title=${text}`, '_blank');
                break;
            case 'pinterest':
                window.open(`https://pinterest.com/pin/create/button/?url=${url}&description=${text}`, '_blank');
                break;
            case 'quora':
                window.open(`https://www.quora.com/share?url=${url}&title=${text}`, '_blank');
                break;
            case 'native':
                if (navigator.share) {
                    navigator.share({
                        title: 'Axevora Post',
                        text: decodeURIComponent(text),
                        url: "https://axevora.com"
                    }).catch(console.error);
                } else {
                    navigator.clipboard.writeText(decodeURIComponent(text));
                    toast.success("Link & Text Copied!");
                }
                break;
            case 'facebook':
            case 'instagram':
                handleVisualDownload();
                navigator.clipboard.writeText(decodeURIComponent(text));
                toast.success("Image Downloaded + Caption Copied! Paste on " + platform);
                setTimeout(() => {
                    if (platform === 'facebook') window.open('https://facebook.com', '_blank');
                    if (platform === 'instagram') window.open('https://instagram.com', '_blank');
                }, 1500);
                break;
        }
    };

    const backgrounds = [
        { name: 'Midnight', class: 'bg-gradient-to-br from-gray-900 via-purple-900 to-violet-900' },
        { name: 'Sunset', class: 'bg-gradient-to-br from-orange-500 via-red-500 to-yellow-500' },
        { name: 'Ocean', class: 'bg-gradient-to-br from-blue-600 to-cyan-400' },
        { name: 'Emerald', class: 'bg-gradient-to-br from-emerald-500 to-teal-900' },
        { name: 'Cherry', class: 'bg-gradient-to-br from-pink-500 to-rose-500' },
        { name: 'Slate', class: 'bg-slate-900' },
    ];

    // Load from Local Storage on Mount
    useEffect(() => {
        const saved = localStorage.getItem('axevora_posts');
        if (saved) {
            setScheduledPosts(JSON.parse(saved));
        }
    }, []);

    // Save to Local Storage on Change
    useEffect(() => {
        localStorage.setItem('axevora_posts', JSON.stringify(scheduledPosts));
    }, [scheduledPosts]);

    // AI Generation Logic
    const handleGenerate = async () => {
        if (!topic.trim()) return toast.error("Please enter a topic!");
        setIsGenerating(true);
        setGeneratedPosts([]); // Clear previous
        setScrapedContext('');

        try {
            let finalTextPrompt = topic;
            let siteContext = '';

            // 1. Check if Topic is URL-like
            const ctx = await extractUrlContext(topic);
            if (ctx && ctx.title) {
                toast.info(`Browsing: ${ctx.title.substring(0, 30)}...`);
                siteContext = `${ctx.title}`;
                setScrapedContext(siteContext);

                // Minimal Context for GET safety
                const safeDesc = (ctx.description || '').substring(0, 100).replace(/[^\w\s]/gi, ''); // Remove non-alphanumeric
                finalTextPrompt = `site: ${ctx.title}. details: ${safeDesc}`;
            }

            const prompt = `Write 5 viral ${platform} posts about: ${finalTextPrompt}. Tone: ${tone}. Sep by "|||".`;

            // Using existing AI Service with API KEY
            const result = await generateGenericText(prompt, apiKey);

            if (result) {
                const posts = result.split('|||').map(p => p.trim()).filter(p => p.length > 0);
                setGeneratedPosts(posts);
                toast.success(siteContext ? "Posts generated from Website!" : "AI Generated 5 posts!");
            }
        } catch (error) {
            console.error("AI Error:", error);
            toast.error("Failed to generate. Try again.");
        } finally {
            setIsGenerating(false);
        }
    };

    // Schedule Logic
    const schedulePost = (content: string) => {
        const newPost: ScheduledPost = {
            id: Date.now().toString() + Math.random().toString(36).substr(2, 9),
            content,
            platform,
            scheduledDate: selectedDate.toISOString(),
            status: 'pending'
        };
        setScheduledPosts([...scheduledPosts, newPost]);
        toast.success("Post scheduled!");
    };

    const deletePost = (id: string) => {
        setScheduledPosts(posts => posts.filter(p => p.id !== id));
        toast.success("Post deleted");
    };

    const handleVisualDownload = async () => {
        const element = document.getElementById('visual-preview');
        if (!element) return;

        try {
            const canvas = await html2canvas(element, { useCORS: true, scale: 2 }); // High res
            const dataUrl = canvas.toDataURL('image/png');
            const link = document.createElement('a');
            link.href = dataUrl;
            link.download = `axevora-post-${Date.now()}.png`;
            link.click();
            toast.success("Image Downloaded! 🎨");
            setVisualMode(false);
        } catch (err) {
            console.error(err);
            toast.error("Failed to generate image.");
        }
    };

    const openVisualCreator = (content: string) => {
        setVisualContent(content);
        setVisualMode(true);
    };

    // Posting Logic (Intent Links)
    const postNow = (post: ScheduledPost) => {
        let url = '';
        const text = encodeURIComponent(post.content);

        switch (post.platform) {
            case 'twitter':
                url = `https://twitter.com/intent/tweet?text=${text}`;
                break;
            case 'linkedin':
                url = `https://www.linkedin.com/feed/?shareActive=true&text=${text}`; // Note: LinkedIn intents are tricky, feed share is safer
                break;
            case 'facebook':
                url = `https://www.facebook.com/sharer/sharer.php?u=&quote=${text}`;
                break;
        }

        window.open(url, '_blank', 'width=600,height=400');

        // Mark as posted locally
        const updated = scheduledPosts.map(p => p.id === post.id ? { ...p, status: 'posted' } : p);
        // @ts-ignore - TS might complain about mismatch in map but its fine here
        setScheduledPosts(updated as ScheduledPost[]);
    };

    // Calendar Grid Calculation
    const weekStart = startOfWeek(selectedDate);
    const weekEnd = endOfWeek(selectedDate);
    const weekDays = eachDayOfInterval({ start: weekStart, end: weekEnd });

    return (
        <ToolTemplate
            title="AI Content Planner"
            description="Generate viral posts & schedule them locally without API keys."
            icon={Calendar}
        >
            <div className="grid grid-cols-1 lg:grid-cols-12 gap-8">

                {/* Left: Generator */}
                <div className="lg:col-span-5 space-y-6">
                    <Card className="bg-white/5 border-white/10">
                        <CardHeader>
                            <CardTitle className="text-xl flex items-center gap-2">
                                <Wand2 className="w-5 h-5 text-purple-400" /> AI Generator
                            </CardTitle>
                            <CardDescription>Create content in seconds</CardDescription>
                        </CardHeader>
                        <CardContent className="space-y-4">
                            <div>
                                <label className="text-xs font-medium text-gray-400 mb-1 block">Platform</label>
                                <div className="flex gap-2">
                                    {['twitter', 'linkedin', 'facebook'].map((p) => (
                                        <Button
                                            key={p}
                                            variant={platform === p ? 'default' : 'outline'}
                                            size="sm"
                                            onClick={() => setPlatform(p as any)}
                                            className={`capitalize ${platform === p ? 'bg-purple-600 hover:bg-purple-700' : 'border-white/10'}`}
                                        >
                                            {p}
                                        </Button>
                                    ))}
                                </div>
                            </div>

                            <div>
                                <label className="text-xs font-medium text-gray-400 mb-1 block">Topic / Idea</label>
                                <Input
                                    placeholder="e.g. 'Future of AI in Marketing'"
                                    value={topic}
                                    onChange={(e) => setTopic(e.target.value)}
                                    className="bg-black/20 border-white/10"
                                />
                            </div>

                            <div>
                                <label className="text-xs font-medium text-gray-400 mb-1 block">Tone</label>
                                <Select value={tone} onValueChange={setTone}>
                                    <SelectTrigger className="bg-black/20 border-white/10">
                                        <SelectValue />
                                    </SelectTrigger>
                                    <SelectContent>
                                        <SelectItem value="professional">Professional 👔</SelectItem>
                                        <SelectItem value="funny">Funny / Witty 😂</SelectItem>
                                        <SelectItem value="viral">Viral / Controversial 🔥</SelectItem>
                                        <SelectItem value="educational">Educational 📚</SelectItem>
                                    </SelectContent>
                                </Select>
                            </div>

                            <Button
                                onClick={handleGenerate}
                                disabled={isGenerating}
                                className="w-full bg-gradient-to-r from-purple-600 to-blue-600 hover:from-purple-700 hover:to-blue-700 text-white font-bold h-12"
                            >
                                {isGenerating ? <span className="animate-pulse">Dreaming... ✨</span> : "Generate Posts 🚀"}
                            </Button>
                        </CardContent>
                    </Card>

                    {/* Generated Results */}
                    {generatedPosts.length > 0 && (
                        <div className="space-y-3 animate-in fade-in slide-in-from-bottom-4 duration-500">
                            <h3 className="text-sm font-bold text-gray-400 uppercase tracking-wider">AI Drafts</h3>
                            {generatedPosts.map((post, idx) => (
                                <Card key={idx} className="bg-white/5 border-white/10 hover:border-purple-500/30 transition-colors group">
                                    <CardContent className="p-4 relative">
                                        <p className="text-sm text-gray-200 mb-3">{post}</p>
                                        <div className="flex gap-2 justify-end">
                                            <Button
                                                size="sm" variant="ghost"
                                                onClick={() => { navigator.clipboard.writeText(post); toast.success("Copied!"); }}
                                                className="h-7 text-xs text-gray-400 hover:text-white"
                                            >
                                                <Copy className="w-3 h-3 mr-1" /> Copy
                                            </Button>
                                            <Button
                                                size="sm" variant="ghost"
                                                onClick={() => openVisualCreator(post)}
                                                className="h-7 text-xs text-pink-400 hover:text-pink-300 hover:bg-pink-500/10"
                                            >
                                                <ImageIcon className="w-3 h-3 mr-1" /> Visual
                                            </Button>
                                            <Button
                                                size="sm"
                                                onClick={() => schedulePost(post)}
                                                className="h-7 text-xs bg-purple-500/20 text-purple-300 hover:bg-purple-500/40"
                                            >
                                                <Plus className="w-3 h-3 mr-1" /> Schedule
                                            </Button>
                                        </div>
                                    </CardContent>
                                </Card>
                            ))}
                        </div>
                    )}
                </div>

                {/* Right: Calendar & Queue */}
                <div className="lg:col-span-7 space-y-6">
                    {/* Weekly Calendar Strip */}
                    <Card className="bg-white/5 border-white/10 overflow-hidden">
                        <CardHeader className="pb-2">
                            <CardTitle className="text-lg flex justify-between items-center">
                                <span>Weekly Plan</span>
                                <div className="flex gap-2 text-sm font-normal text-gray-400">
                                    <button onClick={() => setSelectedDate(addDays(selectedDate, -7))} className="hover:text-white">&lt; Prev</button>
                                    <span className="text-white">{format(selectedDate, 'MMM yyyy')}</span>
                                    <button onClick={() => setSelectedDate(addDays(selectedDate, 7))} className="hover:text-white">Next &gt;</button>
                                </div>
                            </CardTitle>
                        </CardHeader>
                        <CardContent>
                            <div className="grid grid-cols-7 gap-1 text-center">
                                {weekDays.map((day, i) => {
                                    const isSelected = isSameDay(day, selectedDate);
                                    const count = scheduledPosts.filter(p => isSameDay(new Date(p.scheduledDate), day)).length;

                                    return (
                                        <div
                                            key={i}
                                            onClick={() => setSelectedDate(day)}
                                            className={`
                                                p-2 rounded-lg cursor-pointer transition-all border
                                                ${isSelected
                                                    ? 'bg-purple-600 border-purple-400 text-white shadow-lg shadow-purple-900/50'
                                                    : 'bg-black/20 border-transparent hover:bg-white/5 text-gray-400'}
                                            `}
                                        >
                                            <div className="text-[10px] uppercase font-bold opacity-70 mb-1">{format(day, 'EEE')}</div>
                                            <div className="text-lg font-black">{format(day, 'd')}</div>
                                            {count > 0 && (
                                                <div className="mt-1">
                                                    <span className="bg-white text-purple-900 text-[9px] px-1.5 py-0.5 rounded-full font-bold">
                                                        {count}
                                                    </span>
                                                </div>
                                            )}
                                        </div>
                                    );
                                })}
                            </div>
                        </CardContent>
                    </Card>

                    {/* Selected Day's Queue */}
                    <div>
                        <h3 className="text-sm font-bold text-gray-300 mb-3 flex items-center gap-2">
                            <Clock className="w-4 h-4 text-purple-400" />
                            Schedule for {format(selectedDate, 'EEEE, MMM do')}
                        </h3>

                        <div className="space-y-3">
                            {scheduledPosts
                                .filter(p => isSameDay(new Date(p.scheduledDate), selectedDate))
                                .length === 0 ? (
                                <div className="text-center py-12 border-2 border-dashed border-white/5 rounded-xl text-gray-500">
                                    <p>No posts scheduled for this day.</p>
                                    <p className="text-xs mt-1">Select a draft from the left to add one.</p>
                                </div>
                            ) : (
                                scheduledPosts
                                    .filter(p => isSameDay(new Date(p.scheduledDate), selectedDate))
                                    .map((post) => (
                                        <Card key={post.id} className="bg-white/5 border-white/10 group animate-in slide-in-from-right-4 duration-300">
                                            <CardContent className="p-4 flex gap-4 items-start">
                                                <div className={`p-2 rounded-full mt-1 shrink-0 ${post.platform === 'twitter' ? 'bg-blue-500/20 text-blue-400' :
                                                    post.platform === 'linkedin' ? 'bg-blue-700/20 text-blue-500' : 'bg-blue-600/20 text-blue-400'
                                                    }`}>
                                                    {post.platform === 'twitter' && <Twitter className="w-4 h-4" />}
                                                    {post.platform === 'linkedin' && <Linkedin className="w-4 h-4" />}
                                                    {post.platform === 'facebook' && <span className="font-bold text-xs">fb</span>}
                                                </div>

                                                <div className="flex-1 min-w-0">
                                                    <p className="text-sm text-gray-200 line-clamp-3 mb-2">{post.content}</p>
                                                    <div className="flex items-center gap-2">
                                                        {post.status === 'posted' ? (
                                                            <span className="text-[10px] bg-green-500/20 text-green-400 px-2 py-0.5 rounded-full font-bold uppercase tracking-wider">Posted</span>
                                                        ) : (
                                                            <span className="text-[10px] bg-yellow-500/20 text-yellow-500 px-2 py-0.5 rounded-full font-bold uppercase tracking-wider">Pending</span>
                                                        )}
                                                        <span className="text-[10px] text-gray-500">{post.platform}</span>
                                                    </div>
                                                    <div className='flex gap-2 mt-2'>
                                                        <Button
                                                            size="sm" variant="ghost"
                                                            onClick={() => openVisualCreator(post.content)}
                                                            className="h-6 text-[10px] px-2 text-pink-400 hover:text-pink-300 bg-pink-500/5 hover:bg-pink-500/10"
                                                        >
                                                            <ImageIcon className="w-3 h-3 mr-1" /> Create Visual
                                                        </Button>
                                                    </div>
                                                </div>

                                                <div className="flex flex-col gap-2 shrink-0">
                                                    <Button
                                                        size="icon" variant="default"
                                                        onClick={() => postNow(post)}
                                                        title="Post Now"
                                                        className="h-8 w-8 bg-green-600 hover:bg-green-700 text-white"
                                                    >
                                                        <ExternalLink className="w-4 h-4" />
                                                    </Button>
                                                    <Button
                                                        size="icon" variant="ghost"
                                                        onClick={() => deletePost(post.id)}
                                                        className="h-8 w-8 text-gray-500 hover:text-red-400 hover:bg-red-500/10"
                                                    >
                                                        <Trash2 className="w-4 h-4" />
                                                    </Button>
                                                </div>
                                            </CardContent>
                                        </Card>
                                    ))
                            )}
                        </div>
                    </div>
                </div>
            </div>

            {/* Visual Creator Modal Overlay */}
            {visualMode && (
                <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/80 backdrop-blur-sm p-4 animate-in fade-in duration-200">
                    <div className="bg-[#1a1a2e] border border-white/10 rounded-2xl w-full max-w-4xl overflow-hidden shadow-2xl flex flex-col md:flex-row h-[80vh]">

                        {/* Preview Area */}
                        <div className="flex-1 bg-black/50 p-8 flex items-center justify-center overflow-auto">
                            <div
                                id="visual-preview"
                                className={`aspect-square w-full max-w-[500px] ${!visualBg.startsWith('http') ? visualBg : 'bg-gray-800'} p-12 flex flex-col justify-center items-center text-center shadow-2xl relative transition-all duration-500 bg-cover bg-center`}
                                style={visualBg.startsWith('http') ? { backgroundImage: `url(${visualBg})` } : {}}
                            >
                                {/* Dark overlay for text readability */}
                                <div className={`absolute inset-0 ${visualBg.startsWith('http') ? 'bg-black/60' : 'bg-black/10'} mix-blend-overlay`}></div>

                                <div className="relative z-10 flex flex-col items-center justify-center p-8 rounded-3xl bg-black/40 backdrop-blur-md border border-white/10 shadow-2xl mx-4 transition-all duration-300 hover:scale-[1.02]">
                                    <div className="w-12 h-1 mb-6 bg-gradient-to-r from-yellow-400 to-red-500 rounded-full shadow-[0_0_15px_rgba(255,165,0,0.5)]"></div>
                                    <h2
                                        className="font-black text-transparent bg-clip-text bg-gradient-to-b from-white via-gray-100 to-gray-300 drop-shadow-sm leading-tight text-center uppercase tracking-tighter"
                                        style={{
                                            fontSize: `${visualFontSize}px`,
                                            textShadow: '0 4px 8px rgba(0,0,0,0.5)'
                                        }}
                                    >
                                        {visualContent}
                                    </h2>
                                    <div className="flex items-center gap-2 mt-6 opacity-90">
                                        <span className="text-yellow-400 text-xs tracking-[0.2em] font-bold uppercase">Exclusive</span>
                                        <div className="w-1 h-1 bg-white rounded-full"></div>
                                        <span className="text-white text-xs tracking-widest uppercase font-medium">Limited Time</span>
                                    </div>
                                </div>

                                {visualAuthor && (
                                    <div className="absolute bottom-8 z-10 flex items-center gap-2 opacity-90 scale-90">
                                        <div className="w-8 h-8 rounded-full bg-gradient-to-br from-yellow-400 to-orange-600 flex items-center justify-center shadow-lg">
                                            <span className="text-white font-bold text-xs">A</span>
                                        </div>
                                        <span className="text-white text-sm font-bold tracking-widest uppercase drop-shadow-md">axevora.com</span>
                                    </div>
                                )}
                            </div>
                        </div>

                        {/* Controls Sidebar */}
                        <div className="w-full md:w-80 bg-white/5 border-l border-white/10 p-6 space-y-8 overflow-y-auto">
                            <div className="flex justify-between items-center">
                                <h3 className="text-lg font-bold text-white flex items-center gap-2">
                                    <Palette className="w-5 h-5 text-purple-400" /> Visual Studio
                                </h3>
                                <Button size="icon" variant="ghost" onClick={() => setVisualMode(false)} className="text-gray-400 hover:text-white">
                                    <X className="w-5 h-5" />
                                </Button>
                            </div>

                            <div className="space-y-4">
                                <div className="flex justify-between items-center mb-2">
                                    <label className="text-sm font-medium text-gray-300">Background Style</label>
                                    <Button
                                        size="sm"
                                        variant="outline"
                                        onClick={handleGenerateBackground}
                                        disabled={isGeneratingBg}
                                        className="h-6 text-[10px] border-purple-500/30 text-purple-300 hover:bg-purple-500/10"
                                    >
                                        {isGeneratingBg ? <span className="animate-spin mr-1">💫</span> : <Wand2 className="w-3 h-3 mr-1" />}
                                        AI Background
                                    </Button>
                                </div>
                                <div className="grid grid-cols-2 gap-2">
                                    {backgrounds.map(bg => (
                                        <button
                                            key={bg.name}
                                            onClick={() => setVisualBg(bg.class)}
                                            className={`p-2 rounded-lg text-xs font-medium transition-all border ${visualBg === bg.class ? 'border-purple-500 scale-105' : 'border-transparent hover:bg-white/5 text-gray-400'
                                                }`}
                                        >
                                            <div className={`h-8 w-full rounded mb-1 ${bg.class}`}></div>
                                            {bg.name}
                                        </button>
                                    ))}
                                </div>
                            </div>

                            <div className="space-y-4">
                                <label className="text-sm font-medium text-gray-300">Text Size: {visualFontSize}px</label>
                                <input
                                    type="range"
                                    min="16" max="64"
                                    value={visualFontSize}
                                    onChange={(e) => setVisualFontSize(Number(e.target.value))}
                                    className="w-full accent-purple-500 h-2 bg-white/10 rounded-full appearance-none cursor-pointer"
                                />
                            </div>

                            <div className="space-y-4">
                                <label className="flex items-center gap-3 text-sm font-medium text-gray-300 cursor-pointer">
                                    <input
                                        type="checkbox"
                                        checked={visualAuthor}
                                        onChange={(e) => setVisualAuthor(e.target.checked)}
                                        className="w-4 h-4 rounded border-gray-600 bg-black/20 text-purple-500 focus:ring-purple-500"
                                    />
                                    Show Watermark
                                </label>
                            </div>

                            <div className="pt-4 border-t border-white/10">
                                <Button
                                    onClick={handleVisualDownload}
                                    className="w-full bg-gradient-to-r from-pink-500 to-rose-500 hover:from-pink-600 hover:to-rose-600 text-white font-bold py-6 mb-4"
                                >
                                    <Download className="w-5 h-5 mr-2" /> Download Image
                                </Button>

                                <div className="grid grid-cols-4 gap-2">
                                    <Button variant="outline" size="icon" onClick={() => handleShare('twitter')} className="border-white/10 hover:bg-white/10 hover:text-blue-400"><Twitter className="w-4 h-4" /></Button>
                                    <Button variant="outline" size="icon" onClick={() => handleShare('facebook')} className="border-white/10 hover:bg-white/10 hover:text-blue-600"><Facebook className="w-4 h-4" /></Button>
                                    <Button variant="outline" size="icon" onClick={() => handleShare('instagram')} className="border-white/10 hover:bg-white/10 hover:text-pink-500"><Instagram className="w-4 h-4" /></Button>
                                    <Button variant="outline" size="icon" onClick={() => handleShare('linkedin')} className="border-white/10 hover:bg-white/10 hover:text-blue-700"><Linkedin className="w-4 h-4" /></Button>
                                    <Button variant="outline" size="icon" onClick={() => handleShare('whatsapp')} className="border-white/10 hover:bg-white/10 hover:text-green-500"><MessageCircle className="w-4 h-4" /></Button>
                                    <Button variant="outline" size="icon" onClick={() => handleShare('reddit')} className="border-white/10 hover:bg-white/10 hover:text-orange-500"><span className="font-bold text-xs">Rd</span></Button>
                                    <Button variant="outline" size="icon" onClick={() => handleShare('quora')} className="border-white/10 hover:bg-white/10 hover:text-red-700"><span className="font-bold text-xs text-red-700">Q</span></Button>
                                    <Button variant="outline" size="icon" onClick={() => handleShare('pinterest')} className="border-white/10 hover:bg-white/10 hover:text-red-600"><span className="font-bold text-xs">Pin</span></Button>
                                    <Button variant="outline" size="icon" onClick={() => handleShare('native')} className="border-white/10 hover:bg-white/10"><Share2 className="w-4 h-4" /></Button>
                                </div>
                                <p className="text-[10px] text-gray-500 text-center mt-2">Click to share / download</p>
                            </div>
                        </div>
                    </div>
                </div>
            )}
        </ToolTemplate>
    );
};

export default SocialScheduler;
