import { convertToAffiliateUrl } from './utils/convertUrl';

export interface DailyProduct {
  id: string;
  name: string;
  brand: string;
  model: string;
  category: 'phones' | 'tablets' | 'laptops' | 'tvs' | 'audio' | 'cameras' | 'appliances' | 'accessories';
  price: number;
  originalPrice?: number;
  discountPercentage?: number;
  currency: string;
  rating: number;
  reviewCount: number;
  axevoraScore: number;
  scoreLabel: string;
  badge?: 'Best Overall' | 'Best Value' | 'Best for Study' | 'Best Performance' | 'Best Battery' | 'Editor Choice' | 'Top Rated';
  specs: {
    processor?: string;
    ram?: string;
    storage?: string;
    display?: string;
    battery?: string;
    camera?: string;
    gpu?: string;
    os?: string;
  };
  whyWeLikeIt: string;
  bestFor: string;
  tradeOff?: string;
  merchantName: string;
  merchantLogoUrl: string;
  dealUrl: string;
  imageUrl: string | null;
  imageSourceDomain?: string;
  dealType: 'PRODUCT_DEAL';
  verificationStatus: 'LIVE_VERIFIED' | 'SOURCE_STATED';
}

const DAILY_CURATED_DATA: Record<string, DailyProduct[]> = {
  tablets: [
    {
      id: 'tab-1',
      name: 'Samsung Galaxy Tab A9+ (11.0 Inch, 8GB RAM, 128GB)',
      brand: 'Samsung',
      model: 'Galaxy Tab A9+',
      category: 'tablets',
      price: 18999,
      originalPrice: 27999,
      discountPercentage: 32,
      currency: 'INR',
      rating: 4.4,
      reviewCount: 3840,
      axevoraScore: 8.9,
      scoreLabel: 'Excellent',
      badge: 'Best Overall',
      specs: {
        processor: 'Snapdragon 695 5G',
        ram: '8GB RAM',
        storage: '128GB Storage',
        display: '11.0" 90Hz WQXGA Display',
        battery: '7040 mAh Battery',
        camera: '8MP Rear + 5MP Front',
        os: 'Android 14 (One UI)'
      },
      whyWeLikeIt: 'Smooth 90Hz quad-speaker display with Samsung DeX multitasking support.',
      bestFor: 'Study, Online Classes & Streaming',
      tradeOff: '15W charging speed takes ~2.5 hrs for full charge.',
      merchantName: 'Amazon',
      merchantLogoUrl: 'https://www.google.com/s2/favicons?domain=amazon.in&sz=64',
      dealUrl: 'https://www.amazon.in/s?k=Samsung+Galaxy+Tab+A9+Plus+128GB&tag=axevora06-21',
      imageUrl: 'https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6565/6565784_sd.jpg',
      imageSourceDomain: 'bestbuy.com',
      dealType: 'PRODUCT_DEAL',
      verificationStatus: 'SOURCE_STATED'
    },
    {
      id: 'tab-2',
      name: 'Lenovo Tab M11 (11.0 Inch, 8GB RAM, 128GB, Pen Included)',
      brand: 'Lenovo',
      model: 'Tab M11',
      category: 'tablets',
      price: 14999,
      originalPrice: 29000,
      discountPercentage: 48,
      currency: 'INR',
      rating: 4.3,
      reviewCount: 1920,
      axevoraScore: 8.7,
      scoreLabel: 'Great Value',
      badge: 'Best for Study',
      specs: {
        processor: 'MediaTek Helio G88',
        ram: '8GB RAM',
        storage: '128GB Storage',
        display: '11.0" 90Hz FHD IPS',
        battery: '7040 mAh Battery',
        camera: '13MP Rear + 8MP Front',
        os: 'Android 13 (Upgradable)'
      },
      whyWeLikeIt: 'Comes bundled with Lenovo Tab Pen for handwritten notes and PDF highlighting.',
      bestFor: 'Students, Note Taking & PDF Reading',
      tradeOff: 'Helio G88 processor is tuned for study/browsing, not heavy 3D gaming.',
      merchantName: 'Amazon',
      merchantLogoUrl: 'https://www.google.com/s2/favicons?domain=amazon.in&sz=64',
      dealUrl: 'https://www.amazon.in/s?k=Lenovo+Tab+M11+with+pen&tag=axevora06-21',
      imageUrl: 'https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6575/6575971_sd.jpg',
      imageSourceDomain: 'bestbuy.com',
      dealType: 'PRODUCT_DEAL',
      verificationStatus: 'SOURCE_STATED'
    },
    {
      id: 'tab-3',
      name: 'Realme Pad 2 (11.5 Inch 120Hz 2K Display, 6GB, 128GB)',
      brand: 'Realme',
      model: 'Pad 2',
      category: 'tablets',
      price: 15999,
      originalPrice: 24999,
      discountPercentage: 36,
      currency: 'INR',
      rating: 4.4,
      reviewCount: 2450,
      axevoraScore: 8.8,
      scoreLabel: 'Excellent',
      badge: 'Best Value',
      specs: {
        processor: 'MediaTek Helio G99',
        ram: '6GB RAM',
        storage: '128GB Storage',
        display: '11.5" 120Hz 2K Display',
        battery: '8360 mAh + 33W Fast Charge',
        camera: '8MP Rear + 5MP Front',
        os: 'Realme UI 4.0 for Pad'
      },
      whyWeLikeIt: 'Top-tier 120Hz 2K screen with rapid 33W SUPERVOOC fast charging.',
      bestFor: 'Entertainment, Multitasking & Battery Life',
      tradeOff: 'No official stylus included in box.',
      merchantName: 'Flipkart',
      merchantLogoUrl: 'https://www.google.com/s2/favicons?domain=flipkart.com&sz=64',
      dealUrl: 'https://www.flipkart.com/search?q=realme+Pad+2',
      imageUrl: 'https://i5.walmartimages.com/asr/3ce63198-f037-4a9d-a09f-bc969b02be07.31070f3a5d522035a447be00193fc354.jpeg',
      imageSourceDomain: 'walmart.com',
      dealType: 'PRODUCT_DEAL',
      verificationStatus: 'SOURCE_STATED'
    },
    {
      id: 'tab-4',
      name: 'Redmi Pad SE (11.0 Inch FHD+, 6GB RAM, 128GB)',
      brand: 'Xiaomi',
      model: 'Redmi Pad SE',
      category: 'tablets',
      price: 12999,
      originalPrice: 16999,
      discountPercentage: 24,
      currency: 'INR',
      rating: 4.3,
      reviewCount: 4200,
      axevoraScore: 8.5,
      scoreLabel: 'Great Value',
      badge: 'Best Battery',
      specs: {
        processor: 'Snapdragon 680 6nm',
        ram: '6GB RAM',
        storage: '128GB Storage',
        display: '11.0" 90Hz FHD+ Eye-Care',
        battery: '8000 mAh Battery',
        camera: '8MP Rear + 5MP Front',
        os: 'MIUI Pad 14'
      },
      whyWeLikeIt: 'Unbeatable price-to-performance ratio with TÜV Rheinland eye-care certified display.',
      bestFor: 'Kids, Long Reading Sessions & Budget Study',
      tradeOff: '10W bundled charger is slow for an 8000mAh battery.',
      merchantName: 'Amazon',
      merchantLogoUrl: 'https://www.google.com/s2/favicons?domain=amazon.in&sz=64',
      dealUrl: 'https://www.amazon.in/s?k=Redmi+Pad+SE+128GB&tag=axevora06-21',
      imageUrl: 'https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6565/6565784_sd.jpg',
      imageSourceDomain: 'bestbuy.com',
      dealType: 'PRODUCT_DEAL',
      verificationStatus: 'SOURCE_STATED'
    },
    {
      id: 'tab-5',
      name: 'OnePlus Pad Go (11.35 Inch 2.4K Display, 8GB, 128GB)',
      brand: 'OnePlus',
      model: 'Pad Go',
      category: 'tablets',
      price: 19999,
      originalPrice: 24999,
      discountPercentage: 20,
      currency: 'INR',
      rating: 4.5,
      reviewCount: 1850,
      axevoraScore: 8.9,
      scoreLabel: 'Top Pick',
      badge: 'Best Performance',
      specs: {
        processor: 'MediaTek Helio G99',
        ram: '8GB RAM',
        storage: '128GB Storage',
        display: '11.35" 2.4K (2408x1720) 90Hz',
        battery: '8000 mAh + 33W Fast Charge',
        camera: '8MP Rear + 8MP Front',
        os: 'OxygenOS 13.2'
      },
      whyWeLikeIt: 'Stunning 7:5 ReadFit 2.4K display with clean, bloatware-free OxygenOS.',
      bestFor: 'Reading E-Books, Video Calls & Daily Productivity',
      tradeOff: 'Lacks fingerprint sensor (Face Unlock only).',
      merchantName: 'Amazon',
      merchantLogoUrl: 'https://www.google.com/s2/favicons?domain=amazon.in&sz=64',
      dealUrl: 'https://www.amazon.in/s?k=OnePlus+Pad+Go+8GB&tag=axevora06-21',
      imageUrl: 'https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6575/6575971_sd.jpg',
      imageSourceDomain: 'bestbuy.com',
      dealType: 'PRODUCT_DEAL',
      verificationStatus: 'SOURCE_STATED'
    },
    {
      id: 'tab-6',
      name: 'Apple iPad 9th Gen (10.2 Inch Retina, 64GB, A13 Bionic)',
      brand: 'Apple',
      model: 'iPad 9th Gen',
      category: 'tablets',
      price: 24990,
      originalPrice: 32900,
      discountPercentage: 24,
      currency: 'INR',
      rating: 4.6,
      reviewCount: 8900,
      axevoraScore: 9.1,
      scoreLabel: 'Outstanding',
      badge: 'Editor Choice',
      specs: {
        processor: 'Apple A13 Bionic',
        ram: '3GB RAM',
        storage: '64GB Storage',
        display: '10.2" Retina True Tone Display',
        battery: 'Up to 10 Hours',
        camera: '8MP Rear + 12MP Ultra Wide Front',
        os: 'iPadOS 17'
      },
      whyWeLikeIt: 'Center Stage ultra-wide front camera and legendary 5+ year iPadOS software updates.',
      bestFor: 'College Students, Digital Art & Family Tablet',
      tradeOff: 'Base model has 64GB storage and uses Lightning connector.',
      merchantName: 'Croma',
      merchantLogoUrl: 'https://www.google.com/s2/favicons?domain=croma.com&sz=64',
      dealUrl: 'https://www.croma.com/searchB?q=Apple+iPad+9th+Gen',
      imageUrl: 'https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6525/6525404_sd.jpg',
      imageSourceDomain: 'bestbuy.com',
      dealType: 'PRODUCT_DEAL',
      verificationStatus: 'SOURCE_STATED'
    },
    {
      id: 'tab-7',
      name: 'Xiaomi Pad 6 (11.0 Inch 144Hz 2.8K, Snapdragon 870, 6GB, 128GB)',
      brand: 'Xiaomi',
      model: 'Pad 6',
      category: 'tablets',
      price: 26999,
      originalPrice: 39999,
      discountPercentage: 33,
      currency: 'INR',
      rating: 4.6,
      reviewCount: 5120,
      axevoraScore: 9.2,
      scoreLabel: 'Flagship Killer',
      badge: 'Best Performance',
      specs: {
        processor: 'Snapdragon 870 3.2GHz',
        ram: '6GB LPDDR5',
        storage: '128GB UFS 3.1',
        display: '11.0" 144Hz 2.8K Dolby Vision',
        battery: '8840 mAh + 33W Fast Charge',
        camera: '13MP Rear + 8MP Front',
        os: 'HyperOS for Pad'
      },
      whyWeLikeIt: 'Flagship Snapdragon 870 processor with hyper-smooth 144Hz 2.8K panel and metal unibody.',
      bestFor: 'Hardcore Gaming, Video Editing & Heavy Multitasking',
      tradeOff: 'No cellular (LTE/5G) option available.',
      merchantName: 'Amazon',
      merchantLogoUrl: 'https://www.google.com/s2/favicons?domain=amazon.in&sz=64',
      dealUrl: 'https://www.amazon.in/s?k=Xiaomi+Pad+6&tag=axevora06-21',
      imageUrl: 'https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6565/6565784_sd.jpg',
      imageSourceDomain: 'bestbuy.com',
      dealType: 'PRODUCT_DEAL',
      verificationStatus: 'SOURCE_STATED'
    },
    {
      id: 'tab-8',
      name: 'Lenovo Tab K10 (10.3 Inch FHD, 4GB RAM, 64GB)',
      brand: 'Lenovo',
      model: 'Tab K10',
      category: 'tablets',
      price: 9999,
      originalPrice: 19000,
      discountPercentage: 47,
      currency: 'INR',
      rating: 4.1,
      reviewCount: 1400,
      axevoraScore: 8.2,
      scoreLabel: 'Budget Choice',
      badge: 'Best Value',
      specs: {
        processor: 'MediaTek Helio P22T',
        ram: '4GB RAM',
        storage: '64GB Storage',
        display: '10.3" FHD TDDI Display',
        battery: '7500 mAh Battery',
        camera: '8MP Rear + 5MP Front',
        os: 'Android 12'
      },
      whyWeLikeIt: 'Sub-₹10k full HD 10.3-inch screen with sturdy build and enterprise battery tuning.',
      bestFor: 'Entry-Level Study, Zoom Meetings & Billing Systems',
      tradeOff: 'Entry-level processor suitable only for basic apps and video.',
      merchantName: 'Flipkart',
      merchantLogoUrl: 'https://www.google.com/s2/favicons?domain=flipkart.com&sz=64',
      dealUrl: 'https://www.flipkart.com/search?q=Lenovo+Tab+K10',
      imageUrl: 'https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6575/6575971_sd.jpg',
      imageSourceDomain: 'bestbuy.com',
      dealType: 'PRODUCT_DEAL',
      verificationStatus: 'SOURCE_STATED'
    },
    {
      id: 'tab-9',
      name: 'HONOR Pad X8b (11.0 Inch 90Hz, 8GB RAM, 128GB)',
      brand: 'Honor',
      model: 'Pad X8b',
      category: 'tablets',
      price: 13999,
      originalPrice: 22999,
      discountPercentage: 39,
      currency: 'INR',
      rating: 4.2,
      reviewCount: 950,
      axevoraScore: 8.4,
      scoreLabel: 'Great Value',
      badge: 'Top Rated',
      specs: {
        processor: 'Snapdragon 680',
        ram: '8GB (4+4GB Virtual)',
        storage: '128GB Storage',
        display: '11.0" 90Hz FHD+ Eye-Comfort',
        battery: '7250 mAh Battery',
        camera: '5MP Rear + 5MP Front',
        os: 'MagicOS 7.2'
      },
      whyWeLikeIt: 'Lightweight 460g aluminum alloy body with immersive quad speakers.',
      bestFor: 'Online Tuition, Document Reading & Media',
      tradeOff: 'Camera quality in low light is mediocre.',
      merchantName: 'Amazon',
      merchantLogoUrl: 'https://www.google.com/s2/favicons?domain=amazon.in&sz=64',
      dealUrl: 'https://www.amazon.in/s?k=HONOR+Pad+X8&tag=axevora06-21',
      imageUrl: 'https://i5.walmartimages.com/asr/3ce63198-f037-4a9d-a09f-bc969b02be07.31070f3a5d522035a447be00193fc354.jpeg',
      imageSourceDomain: 'walmart.com',
      dealType: 'PRODUCT_DEAL',
      verificationStatus: 'SOURCE_STATED'
    },
    {
      id: 'tab-10',
      name: 'Samsung Galaxy Tab S9 FE (10.9 Inch 90Hz, S-Pen Included, 6GB, 128GB)',
      brand: 'Samsung',
      model: 'Galaxy Tab S9 FE',
      category: 'tablets',
      price: 34999,
      originalPrice: 44999,
      discountPercentage: 22,
      currency: 'INR',
      rating: 4.6,
      reviewCount: 2100,
      axevoraScore: 9.3,
      scoreLabel: 'Premium Choice',
      badge: 'Best Overall',
      specs: {
        processor: 'Exynos 1380 5nm',
        ram: '6GB RAM',
        storage: '128GB Storage (microSD up to 1TB)',
        display: '10.9" 90Hz WQXGA Vision Booster',
        battery: '8000 mAh + 45W Fast Charge',
        camera: '8MP Rear + 12MP Ultra-Wide Front',
        os: 'One UI 6.0 (IP68 Water Resistant)'
      },
      whyWeLikeIt: 'Official IP68 water & dust resistance with in-box magnetic low-latency S-Pen.',
      bestFor: 'Engineers, Medical Students, Designers & Professionals',
      tradeOff: 'Higher price bracket compared to budget study tablets.',
      merchantName: 'Amazon',
      merchantLogoUrl: 'https://www.google.com/s2/favicons?domain=amazon.in&sz=64',
      dealUrl: 'https://www.amazon.in/s?k=Samsung+Galaxy+Tab+S9+FE&tag=axevora06-21',
      imageUrl: 'https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6565/6565784_sd.jpg',
      imageSourceDomain: 'bestbuy.com',
      dealType: 'PRODUCT_DEAL',
      verificationStatus: 'SOURCE_STATED'
    }
  ],

  laptops: [
    {
      id: 'lap-1',
      name: 'ASUS TUF Gaming A15 (Ryzen 7 7435HS, RTX 3050 4GB, 16GB, 512GB SSD, 144Hz)',
      brand: 'ASUS',
      model: 'TUF Gaming A15',
      category: 'laptops',
      price: 58990,
      originalPrice: 77990,
      discountPercentage: 24,
      currency: 'INR',
      rating: 4.4,
      reviewCount: 3100,
      axevoraScore: 9.1,
      scoreLabel: 'Outstanding',
      badge: 'Best Overall',
      specs: {
        processor: 'AMD Ryzen 7 7435HS (8 Cores, 16 Threads)',
        gpu: 'NVIDIA GeForce RTX 3050 4GB (75W TGP)',
        ram: '16GB DDR5 4800MHz',
        storage: '512GB PCIe 4.0 NVMe SSD',
        display: '15.6" 144Hz FHD vIPS Panel',
        battery: '48Whr + 150W Fast Charger',
        os: 'Windows 11 Home'
      },
      whyWeLikeIt: '8-core Ryzen 7 power with high-TGP RTX 3050 and dual-fan anti-dust cooling.',
      bestFor: 'AAA Gaming, 1080p Esports & Video Editing',
      tradeOff: 'Ryzen 7 7435HS lacks integrated iGPU, so battery backup is ~3.5 hours on idle.',
      merchantName: 'Amazon',
      merchantLogoUrl: 'https://www.google.com/s2/favicons?domain=amazon.in&sz=64',
      dealUrl: 'https://www.amazon.in/s?k=ASUS+TUF+Gaming+A15+RTX+3050&tag=axevora06-21',
      imageUrl: 'https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6575/6575971_sd.jpg',
      imageSourceDomain: 'bestbuy.com',
      dealType: 'PRODUCT_DEAL',
      verificationStatus: 'SOURCE_STATED'
    },
    {
      id: 'lap-2',
      name: 'Lenovo LOQ 15 (Core i5-12450HX, RTX 3050 6GB 95W TGP, 16GB, 512GB SSD, 144Hz)',
      brand: 'Lenovo',
      model: 'LOQ 15IAX9',
      category: 'laptops',
      price: 61990,
      originalPrice: 82990,
      discountPercentage: 25,
      currency: 'INR',
      rating: 4.5,
      reviewCount: 2200,
      axevoraScore: 9.3,
      scoreLabel: 'Top Performer',
      badge: 'Best Performance',
      specs: {
        processor: 'Intel Core i5-12450HX (8 Cores, 12 Threads)',
        gpu: 'NVIDIA GeForce RTX 3050 6GB (95W Max TGP)',
        ram: '16GB DDR5 4800MHz',
        storage: '512GB Gen4 SSD',
        display: '15.6" 144Hz 100% sRGB FHD Display',
        battery: '60Whr with Super Rapid Charge Pro',
        os: 'Windows 11 Home'
      },
      whyWeLikeIt: '6GB VRAM RTX 3050 with 95W TGP and 100% sRGB color-accurate display.',
      bestFor: 'Competitive Gamers, 3D Renderers & Graphic Designers',
      tradeOff: '2.4 kg weight makes it heavier for daily backpack travel.',
      merchantName: 'Flipkart',
      merchantLogoUrl: 'https://www.google.com/s2/favicons?domain=flipkart.com&sz=64',
      dealUrl: 'https://www.flipkart.com/search?q=Lenovo+LOQ+RTX+3050+6GB',
      imageUrl: 'https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6575/6575971_sd.jpg',
      imageSourceDomain: 'bestbuy.com',
      dealType: 'PRODUCT_DEAL',
      verificationStatus: 'SOURCE_STATED'
    },
    {
      id: 'lap-3',
      name: 'Acer Nitro V 15 (Core i5-13420H, RTX 3050 6GB, 16GB, 512GB SSD, 144Hz)',
      brand: 'Acer',
      model: 'Nitro V 15',
      category: 'laptops',
      price: 59990,
      originalPrice: 79999,
      discountPercentage: 25,
      currency: 'INR',
      rating: 4.3,
      reviewCount: 1800,
      axevoraScore: 9.0,
      scoreLabel: 'Excellent',
      badge: 'Best Value',
      specs: {
        processor: 'Intel Core i5-13420H 13th Gen',
        gpu: 'NVIDIA GeForce RTX 3050 6GB GDDR6',
        ram: '16GB DDR5 RAM',
        storage: '512GB PCIe Gen4 SSD',
        display: '15.6" 144Hz IPS FHD Display',
        battery: '57Whr Battery',
        os: 'Windows 11 Home'
      },
      whyWeLikeIt: '13th Gen Intel processor with Thunderbolt 4 port and 6GB dedicated graphics.',
      bestFor: 'Engineering Students, Gamers & Streamers',
      tradeOff: 'Dual exhaust fans can get loud under 100% prolonged GPU load.',
      merchantName: 'Amazon',
      merchantLogoUrl: 'https://www.google.com/s2/favicons?domain=amazon.in&sz=64',
      dealUrl: 'https://www.amazon.in/s?k=Acer+Nitro+V+15+RTX+3050&tag=axevora06-21',
      imageUrl: 'https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6575/6575971_sd.jpg',
      imageSourceDomain: 'bestbuy.com',
      dealType: 'PRODUCT_DEAL',
      verificationStatus: 'SOURCE_STATED'
    },
    {
      id: 'lap-4',
      name: 'HP Victus 15 (Ryzen 5 5600H, AMD Radeon RX 6500M 4GB, 16GB, 512GB SSD)',
      brand: 'HP',
      model: 'Victus 15-fb0157AX',
      category: 'laptops',
      price: 51990,
      originalPrice: 68000,
      discountPercentage: 23,
      currency: 'INR',
      rating: 4.2,
      reviewCount: 2600,
      axevoraScore: 8.6,
      scoreLabel: 'Great Value',
      badge: 'Best for Study',
      specs: {
        processor: 'AMD Ryzen 5 5600H (6 Cores, 12 Threads)',
        gpu: 'AMD Radeon RX 6500M 4GB GDDR6',
        ram: '16GB DDR4 RAM',
        storage: '512GB NVMe SSD',
        display: '15.6" 144Hz FHD IPS Panel',
        battery: '52.5Whr Fast Charge (50% in 30 mins)',
        os: 'Windows 11 + MS Office 2021'
      },
      whyWeLikeIt: 'Includes lifetime MS Office 2021 license and solid battery with fast charging.',
      bestFor: 'College Projects, Casual Gaming & Office Work',
      tradeOff: 'RX 6500M is slightly behind RTX 3050 in ray-tracing performance.',
      merchantName: 'Amazon',
      merchantLogoUrl: 'https://www.google.com/s2/favicons?domain=amazon.in&sz=64',
      dealUrl: 'https://www.amazon.in/s?k=HP+Victus+Gaming+Laptop+5600H&tag=axevora06-21',
      imageUrl: 'https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6575/6575971_sd.jpg',
      imageSourceDomain: 'bestbuy.com',
      dealType: 'PRODUCT_DEAL',
      verificationStatus: 'SOURCE_STATED'
    },
    {
      id: 'lap-5',
      name: 'MSI Thin 15 (Core i5-12450H, RTX 2050 4GB, 16GB, 512GB SSD, 144Hz, 1.86kg)',
      brand: 'MSI',
      model: 'Thin 15 B12UCX',
      category: 'laptops',
      price: 46990,
      originalPrice: 62990,
      discountPercentage: 25,
      currency: 'INR',
      rating: 4.1,
      reviewCount: 1100,
      axevoraScore: 8.4,
      scoreLabel: 'Budget Choice',
      badge: 'Best Value',
      specs: {
        processor: 'Intel Core i5-12450H 12th Gen',
        gpu: 'NVIDIA GeForce RTX 2050 4GB GDDR6',
        ram: '16GB DDR4 RAM',
        storage: '512GB NVMe SSD',
        display: '15.6" 144Hz FHD IPS-Level',
        battery: '52.4Whr Battery',
        os: 'Windows 11 Home'
      },
      whyWeLikeIt: 'Ultra-portable 1.86kg lightweight chassis with dedicated ray-tracing RTX GPU under ₹48k.',
      bestFor: 'Students Needing Lightweight Portability & 1080p Gaming',
      tradeOff: 'Single fan cooling requires flat desk use during heavy gaming.',
      merchantName: 'Flipkart',
      merchantLogoUrl: 'https://www.google.com/s2/favicons?domain=flipkart.com&sz=64',
      dealUrl: 'https://www.flipkart.com/search?q=MSI+Thin+15+i5',
      imageUrl: 'https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6575/6575971_sd.jpg',
      imageSourceDomain: 'bestbuy.com',
      dealType: 'PRODUCT_DEAL',
      verificationStatus: 'SOURCE_STATED'
    },
    {
      id: 'lap-6',
      name: 'Apple MacBook Air M1 (13.3 Inch Retina, 8GB RAM, 256GB SSD, 18hr Battery)',
      brand: 'Apple',
      model: 'MacBook Air M1',
      category: 'laptops',
      price: 64990,
      originalPrice: 92900,
      discountPercentage: 30,
      currency: 'INR',
      rating: 4.8,
      reviewCount: 14500,
      axevoraScore: 9.5,
      scoreLabel: 'Legendary',
      badge: 'Best Battery',
      specs: {
        processor: 'Apple M1 Silicon (8-Core CPU, 7-Core GPU)',
        gpu: '7-Core Integrated M1 GPU',
        ram: '8GB Unified Memory',
        storage: '256GB High-Speed SSD',
        display: '13.3" 2560x1600 Retina P3 Display',
        battery: 'Up to 18 Hours All-Day Battery',
        os: 'macOS Sonoma'
      },
      whyWeLikeIt: 'Silent fanless design with class-leading 15-18 hour real battery life and aluminum unibody.',
      bestFor: 'Coding, Content Writing, College, Business & Travel',
      tradeOff: 'Not meant for native Windows gaming titles; RAM and SSD are not user-upgradeable.',
      merchantName: 'Amazon',
      merchantLogoUrl: 'https://www.google.com/s2/favicons?domain=amazon.in&sz=64',
      dealUrl: 'https://www.amazon.in/s?k=Apple+MacBook+Air+M1&tag=axevora06-21',
      imageUrl: 'https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6525/6525404_sd.jpg',
      imageSourceDomain: 'bestbuy.com',
      dealType: 'PRODUCT_DEAL',
      verificationStatus: 'SOURCE_STATED'
    },
    {
      id: 'lap-7',
      name: 'Dell 15 Thin & Light (Core i5-1235U, 16GB RAM, 512GB SSD, 15.6" FHD)',
      brand: 'Dell',
      model: 'Dell 15 3520',
      category: 'laptops',
      price: 47990,
      originalPrice: 62000,
      discountPercentage: 23,
      currency: 'INR',
      rating: 4.2,
      reviewCount: 3100,
      axevoraScore: 8.5,
      scoreLabel: 'Reliable Workhorse',
      badge: 'Best for Study',
      specs: {
        processor: 'Intel Core i5-1235U (10 Cores, 12 Threads)',
        gpu: 'Intel Iris Xe Graphics',
        ram: '16GB DDR4 RAM',
        storage: '512GB NVMe SSD',
        display: '15.6" 120Hz FHD Narrow Border',
        battery: '41Whr with ExpressCharge',
        os: 'Windows 11 + MS Office 2021'
      },
      whyWeLikeIt: '120Hz display with lift-hinge ergonomics and 16GB RAM for multitasking.',
      bestFor: 'Office Productivity, Coding, Accounting & Students',
      tradeOff: 'Integrated graphics only; not designed for heavy AAA games.',
      merchantName: 'Amazon',
      merchantLogoUrl: 'https://www.google.com/s2/favicons?domain=amazon.in&sz=64',
      dealUrl: 'https://www.amazon.in/s?k=Dell+15+i5+12th+Gen+16GB&tag=axevora06-21',
      imageUrl: 'https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6575/6575971_sd.jpg',
      imageSourceDomain: 'bestbuy.com',
      dealType: 'PRODUCT_DEAL',
      verificationStatus: 'SOURCE_STATED'
    },
    {
      id: 'lap-8',
      name: 'Lenovo IdeaPad Slim 3 (Ryzen 7 5700U 8-Core, 16GB, 512GB SSD, 15.6" FHD)',
      brand: 'Lenovo',
      model: 'IdeaPad Slim 3',
      category: 'laptops',
      price: 46990,
      originalPrice: 68990,
      discountPercentage: 32,
      currency: 'INR',
      rating: 4.3,
      reviewCount: 4100,
      axevoraScore: 8.7,
      scoreLabel: 'High Productivity',
      badge: 'Best Value',
      specs: {
        processor: 'AMD Ryzen 7 5700U (8 Cores, 16 Threads)',
        gpu: 'AMD Radeon Vega 8 Graphics',
        ram: '16GB DDR4 3200MHz',
        storage: '512GB PCIe SSD',
        display: '15.6" FHD Anti-Glare 250 nits',
        battery: '45Whr with Rapid Charge',
        os: 'Windows 11 + MS Office 2021'
      },
      whyWeLikeIt: 'True 8-core, 16-thread processor under ₹47k delivers effortless programming & compile speeds.',
      bestFor: 'Software Developers, Data Analysts & Power Office Users',
      tradeOff: 'Plastic palm rest and 250-nit indoor display.',
      merchantName: 'Amazon',
      merchantLogoUrl: 'https://www.google.com/s2/favicons?domain=amazon.in&sz=64',
      dealUrl: 'https://www.amazon.in/s?k=Lenovo+IdeaPad+Slim+3+Ryzen+7&tag=axevora06-21',
      imageUrl: 'https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6575/6575971_sd.jpg',
      imageSourceDomain: 'bestbuy.com',
      dealType: 'PRODUCT_DEAL',
      verificationStatus: 'SOURCE_STATED'
    },
    {
      id: 'lap-9',
      name: 'ASUS Vivobook 15 (Core i3-1215U, 8GB, 512GB SSD, FHD Display)',
      brand: 'ASUS',
      model: 'Vivobook 15 X1504ZA',
      category: 'laptops',
      price: 33990,
      originalPrice: 47990,
      discountPercentage: 29,
      currency: 'INR',
      rating: 4.2,
      reviewCount: 5200,
      axevoraScore: 8.1,
      scoreLabel: 'Budget Value',
      badge: 'Best Value',
      specs: {
        processor: 'Intel Core i3-1215U (6 Cores, 8 Threads)',
        gpu: 'Intel UHD Graphics',
        ram: '8GB DDR4 (Expandable to 16GB)',
        storage: '512GB M.2 NVMe SSD',
        display: '15.6" FHD Anti-Glare Display',
        battery: '42Whr Battery',
        os: 'Windows 11 Home'
      },
      whyWeLikeIt: '180-degree lay-flat hinge with physical webcam privacy shield under ₹34k.',
      bestFor: 'School Students, Daily Web Surfing & Accounting',
      tradeOff: '8GB RAM is single channel; upgrading to 16GB is recommended.',
      merchantName: 'Amazon',
      merchantLogoUrl: 'https://www.google.com/s2/favicons?domain=amazon.in&sz=64',
      dealUrl: 'https://www.amazon.in/s?k=ASUS+Vivobook+15+i3+12th+Gen&tag=axevora06-21',
      imageUrl: 'https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6575/6575971_sd.jpg',
      imageSourceDomain: 'bestbuy.com',
      dealType: 'PRODUCT_DEAL',
      verificationStatus: 'SOURCE_STATED'
    },
    {
      id: 'lap-10',
      name: 'Apple MacBook Air M2 (13.6 Inch Liquid Retina, 8GB, 256GB SSD, MagSafe 3)',
      brand: 'Apple',
      model: 'MacBook Air M2',
      category: 'laptops',
      price: 84990,
      originalPrice: 99900,
      discountPercentage: 15,
      currency: 'INR',
      rating: 4.8,
      reviewCount: 6800,
      axevoraScore: 9.6,
      scoreLabel: 'Premium Flagship',
      badge: 'Best Overall',
      specs: {
        processor: 'Apple M2 Silicon (8-Core CPU, 8-Core GPU)',
        gpu: '8-Core M2 Next-Gen GPU',
        ram: '8GB Unified Memory',
        storage: '256GB High-Speed SSD',
        display: '13.6" 500 nits Liquid Retina Display',
        battery: 'Up to 18 Hours + MagSafe 3 Charging',
        os: 'macOS Sequoia'
      },
      whyWeLikeIt: 'Modern slim unibody design, 1080p FaceTime HD camera, and dedicated MagSafe 3 charging port.',
      bestFor: 'Creators, Developers, Executives & Power Users',
      tradeOff: 'Premium pricing; external monitor support limited to 1 display natively.',
      merchantName: 'Amazon',
      merchantLogoUrl: 'https://www.google.com/s2/favicons?domain=amazon.in&sz=64',
      dealUrl: 'https://www.amazon.in/s?k=Apple+MacBook+Air+M2&tag=axevora06-21',
      imageUrl: 'https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6525/6525404_sd.jpg',
      imageSourceDomain: 'bestbuy.com',
      dealType: 'PRODUCT_DEAL',
      verificationStatus: 'SOURCE_STATED'
    }
  ],

  phones: [
    {
      id: 'ph-1',
      name: 'OnePlus Nord CE4 5G (8GB RAM, 128GB, 100W SUPERVOOC, Snapdragon 7 Gen 3)',
      brand: 'OnePlus',
      model: 'Nord CE4',
      category: 'phones',
      price: 24999,
      originalPrice: 27999,
      discountPercentage: 11,
      currency: 'INR',
      rating: 4.4,
      reviewCount: 7800,
      axevoraScore: 9.1,
      scoreLabel: 'Outstanding',
      badge: 'Best Overall',
      specs: {
        processor: 'Qualcomm Snapdragon 7 Gen 3 (4nm)',
        ram: '8GB LPDDR4X',
        storage: '128GB UFS 3.1 (Expandable up to 1TB)',
        display: '6.7" 120Hz Fluid AMOLED Display',
        battery: '5500 mAh + 100W Flash Charge',
        camera: '50MP Sony LYT-600 OIS + 8MP Ultra-Wide',
        os: 'OxygenOS 14'
      },
      whyWeLikeIt: 'Blazing fast 100W charging (1-100% in 29 min) with massive 5500mAh battery and Sony OIS camera.',
      bestFor: 'All-Round Smartphone Performance & Battery Life',
      tradeOff: 'Plastic frame construction.',
      merchantName: 'Amazon',
      merchantLogoUrl: 'https://www.google.com/s2/favicons?domain=amazon.in&sz=64',
      dealUrl: 'https://www.amazon.in/s?k=OnePlus+Nord+CE4+5G&tag=axevora06-21',
      imageUrl: 'https://www.lowyat.net/wp-content/uploads/2023/01/oneplus-11r-5g-design-01.jpg',
      imageSourceDomain: 'lowyat.net',
      dealType: 'PRODUCT_DEAL',
      verificationStatus: 'SOURCE_STATED'
    },
    {
      id: 'ph-2',
      name: 'iQOO Z9s 5G (8GB RAM, 128GB, Sony IMX882 OIS, Dimensity 7300)',
      brand: 'iQOO',
      model: 'Z9s 5G',
      category: 'phones',
      price: 19999,
      originalPrice: 25999,
      discountPercentage: 23,
      currency: 'INR',
      rating: 4.4,
      reviewCount: 3900,
      axevoraScore: 9.0,
      scoreLabel: 'Top Performer',
      badge: 'Best Value',
      specs: {
        processor: 'MediaTek Dimensity 7300 4nm',
        ram: '8GB RAM',
        storage: '128GB Storage',
        display: '6.77" 120Hz 3D Curved AMOLED 1800 nits',
        battery: '5500 mAh + 44W FlashCharge',
        camera: '50MP Sony IMX882 OIS + 2MP Bokeh',
        os: 'Funtouch OS 14'
      },
      whyWeLikeIt: 'Ultra-sleek 3D curved 120Hz AMOLED display with 700K+ AnTuTu benchmark score under ₹20k.',
      bestFor: 'Gaming, Portrait Photography & Sleek Design',
      tradeOff: 'Mono speaker output; no ultra-wide lens.',
      merchantName: 'Amazon',
      merchantLogoUrl: 'https://www.google.com/s2/favicons?domain=amazon.in&sz=64',
      dealUrl: 'https://www.amazon.in/s?k=iQOO+Z9s+5G&tag=axevora06-21',
      imageUrl: 'https://www.lowyat.net/wp-content/uploads/2023/01/oneplus-11r-5g-design-01.jpg',
      imageSourceDomain: 'lowyat.net',
      dealType: 'PRODUCT_DEAL',
      verificationStatus: 'SOURCE_STATED'
    },
    {
      id: 'ph-3',
      name: 'Realme 12+ 5G (8GB RAM, 128GB, Sony LYT-600 OIS, 67W SUPERVOOC)',
      brand: 'Realme',
      model: '12+ 5G',
      category: 'phones',
      price: 18999,
      originalPrice: 23999,
      discountPercentage: 21,
      currency: 'INR',
      rating: 4.3,
      reviewCount: 4600,
      axevoraScore: 8.8,
      scoreLabel: 'Great Value',
      badge: 'Best for Study',
      specs: {
        processor: 'MediaTek Dimensity 7050 5G',
        ram: '8GB RAM',
        storage: '128GB Storage',
        display: '6.67" 120Hz AMOLED 2000 nits Rainwater Touch',
        battery: '5000 mAh + 67W Fast Charge',
        camera: '50MP Sony LYT-600 OIS + 8MP Wide + 2MP Macro',
        os: 'Realme UI 5.0'
      },
      whyWeLikeIt: 'Luxury vegan leather watch-inspired back design with excellent cinematic portrait mode.',
      bestFor: 'Street Photography, Social Media & Daily Style',
      tradeOff: 'Realme UI has pre-installed recommendation apps (can be disabled).',
      merchantName: 'Flipkart',
      merchantLogoUrl: 'https://www.google.com/s2/favicons?domain=flipkart.com&sz=64',
      dealUrl: 'https://www.flipkart.com/search?q=realme+12+plus+5G',
      imageUrl: 'https://i5.walmartimages.com/asr/3ce63198-f037-4a9d-a09f-bc969b02be07.31070f3a5d522035a447be00193fc354.jpeg',
      imageSourceDomain: 'walmart.com',
      dealType: 'PRODUCT_DEAL',
      verificationStatus: 'SOURCE_STATED'
    },
    {
      id: 'ph-4',
      name: 'Apple iPhone 15 (128GB, 48MP Camera, Dynamic Island, A16 Bionic, Black)',
      brand: 'Apple',
      model: 'iPhone 15 128GB',
      category: 'phones',
      price: 69900,
      originalPrice: 79900,
      discountPercentage: 13,
      currency: 'INR',
      rating: 4.7,
      reviewCount: 16200,
      axevoraScore: 9.6,
      scoreLabel: 'Flagship Benchmark',
      badge: 'Best Overall',
      specs: {
        processor: 'Apple A16 Bionic (4nm)',
        ram: '6GB RAM',
        storage: '128GB Storage',
        display: '6.1" Super Retina XDR OLED (2000 nits peak)',
        battery: '3349 mAh (All-Day Battery) + USB-C',
        camera: '48MP Main with 2x Telephoto + 12MP Ultra-Wide',
        os: 'iOS 18'
      },
      whyWeLikeIt: 'Next-gen 48MP camera with 2x optical-quality zoom, Dynamic Island, and universal USB-C port.',
      bestFor: 'Point-and-Shoot Photography, 4K Dolby Video & Apple Ecosystem',
      tradeOff: '60Hz display refresh rate; 20W charging is standard.',
      merchantName: 'Amazon',
      merchantLogoUrl: 'https://www.google.com/s2/favicons?domain=amazon.in&sz=64',
      dealUrl: 'https://www.amazon.in/s?k=iPhone+15+128GB+Black&tag=axevora06-21',
      imageUrl: 'https://i5.walmartimages.com/seo/AT-T-Apple-iPhone-15-128GB-Black_cef93f3f-12a3-42ef-bac9-49564807a10d.f72a0ebba79e327024f18cfc932116b5.jpeg',
      imageSourceDomain: 'walmart.com',
      dealType: 'PRODUCT_DEAL',
      verificationStatus: 'SOURCE_STATED'
    },
    {
      id: 'ph-5',
      name: 'Samsung Galaxy S24 5G (8GB RAM, 128GB, Galaxy AI, 50MP OIS)',
      brand: 'Samsung',
      model: 'Galaxy S24',
      category: 'phones',
      price: 64999,
      originalPrice: 74999,
      discountPercentage: 13,
      currency: 'INR',
      rating: 4.6,
      reviewCount: 3800,
      axevoraScore: 9.4,
      scoreLabel: 'AI Flagship',
      badge: 'Best Performance',
      specs: {
        processor: 'Exynos 2400 4nm / Snapdragon 8 Gen 3',
        ram: '8GB RAM',
        storage: '128GB Storage',
        display: '6.2" 1-120Hz Dynamic AMOLED 2X (2600 nits)',
        battery: '4000 mAh + 25W Fast Charge + Wireless',
        camera: '50MP OIS + 10MP 3x Optical Telephoto + 12MP Ultra-Wide',
        os: 'One UI 6.1 with 7 Years OS Updates'
      },
      whyWeLikeIt: 'Guaranteed 7 years of Android OS updates with built-in Galaxy AI live translation and Circle to Search.',
      bestFor: 'Compact Flagship Lovers, Power Users & Long-Term Ownership',
      tradeOff: '4000mAh battery is average under heavy 5G GPS usage.',
      merchantName: 'Amazon',
      merchantLogoUrl: 'https://www.google.com/s2/favicons?domain=amazon.in&sz=64',
      dealUrl: 'https://www.amazon.in/s?k=Samsung+Galaxy+S24+5G&tag=axevora06-21',
      imageUrl: 'https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6565/6565784_sd.jpg',
      imageSourceDomain: 'bestbuy.com',
      dealType: 'PRODUCT_DEAL',
      verificationStatus: 'SOURCE_STATED'
    },
    {
      id: 'ph-6',
      name: 'Moto G85 5G (8GB RAM, 128GB, 3D Curved 120Hz pOLED, 50MP Sony LYT-600 OIS)',
      brand: 'Motorola',
      model: 'Moto G85 5G',
      category: 'phones',
      price: 17999,
      originalPrice: 20999,
      discountPercentage: 14,
      currency: 'INR',
      rating: 4.3,
      reviewCount: 5400,
      axevoraScore: 8.7,
      scoreLabel: 'Great Value',
      badge: 'Best Value',
      specs: {
        processor: 'Snapdragon 6s Gen 3 5G',
        ram: '8GB RAM',
        storage: '128GB Storage',
        display: '6.67" 120Hz 3D Curved pOLED (1600 nits)',
        battery: '5000 mAh + 33W TurboPower',
        camera: '50MP Sony LYT-600 OIS + 8MP Ultra-Wide',
        os: 'Clean Hello UI (Android 14)'
      },
      whyWeLikeIt: 'Premium 3D curved pOLED display with ad-free, bloatware-free clean Android experience under ₹18k.',
      bestFor: 'Clean Android Fans, Media Consumers & Daily Commuters',
      tradeOff: 'Snapdragon 6s Gen 3 is tuned for battery efficiency rather than extreme gaming.',
      merchantName: 'Flipkart',
      merchantLogoUrl: 'https://www.google.com/s2/favicons?domain=flipkart.com&sz=64',
      dealUrl: 'https://www.flipkart.com/search?q=moto+g85+5g',
      imageUrl: 'https://i5.walmartimages.com/asr/3ce63198-f037-4a9d-a09f-bc969b02be07.31070f3a5d522035a447be00193fc354.jpeg',
      imageSourceDomain: 'walmart.com',
      dealType: 'PRODUCT_DEAL',
      verificationStatus: 'SOURCE_STATED'
    },
    {
      id: 'ph-7',
      name: 'Poco X6 Pro 5G (8GB RAM, 256GB, Dimensity 8300 Ultra, 120Hz 1.5K AMOLED)',
      brand: 'Poco',
      model: 'X6 Pro 5G',
      category: 'phones',
      price: 23999,
      originalPrice: 30999,
      discountPercentage: 23,
      currency: 'INR',
      rating: 4.5,
      reviewCount: 8200,
      axevoraScore: 9.3,
      scoreLabel: 'Performance Beast',
      badge: 'Best Performance',
      specs: {
        processor: 'MediaTek Dimensity 8300-Ultra 4nm (1.4M+ AnTuTu)',
        ram: '8GB LPDDR5X',
        storage: '256GB UFS 4.0',
        display: '6.67" 120Hz 1.5K Flow AMOLED (1800 nits)',
        battery: '5000 mAh + 67W Turbo Charge',
        camera: '64MP OIS Triple Camera',
        os: 'Xiaomi HyperOS'
      },
      whyWeLikeIt: 'Unmatched 1.4 Million AnTuTu flagship processor with UFS 4.0 and LPDDR5X at a mid-range price.',
      bestFor: 'Hardcore Mobile Gamers (BGMI, COD, Genshin Impact)',
      tradeOff: 'Camera tuning is average compared to camera-first phones.',
      merchantName: 'Flipkart',
      merchantLogoUrl: 'https://www.google.com/s2/favicons?domain=flipkart.com&sz=64',
      dealUrl: 'https://www.flipkart.com/search?q=poco+x6+pro+5g',
      imageUrl: 'https://i5.walmartimages.com/asr/3ce63198-f037-4a9d-a09f-bc969b02be07.31070f3a5d522035a447be00193fc354.jpeg',
      imageSourceDomain: 'walmart.com',
      dealType: 'PRODUCT_DEAL',
      verificationStatus: 'SOURCE_STATED'
    },
    {
      id: 'ph-8',
      name: 'Samsung Galaxy M35 5G (6GB RAM, 128GB, 6000mAh Battery, 120Hz sAMOLED)',
      brand: 'Samsung',
      model: 'Galaxy M35 5G',
      category: 'phones',
      price: 15999,
      originalPrice: 21999,
      discountPercentage: 27,
      currency: 'INR',
      rating: 4.3,
      reviewCount: 9100,
      axevoraScore: 8.8,
      scoreLabel: 'Battery King',
      badge: 'Best Battery',
      specs: {
        processor: 'Samsung Exynos 1380 5nm (with Vapor Cooling Chamber)',
        ram: '6GB RAM',
        storage: '128GB Storage',
        display: '6.6" 120Hz Super AMOLED (1000 nits HBM)',
        battery: '6000 mAh Monster Battery + 25W Fast Charge',
        camera: '50MP OIS No Shake Camera + 8MP Ultra-Wide',
        os: 'One UI 6.1 (4 OS Upgrades)'
      },
      whyWeLikeIt: 'Massive 6000mAh battery that easily lasts 2 full days with Gorilla Glass Victus+ protection.',
      bestFor: 'Heavy Travel, Field Work & Non-Stop Media Consumers',
      tradeOff: '222g weight feels thick in hand; no charger in the box.',
      merchantName: 'Amazon',
      merchantLogoUrl: 'https://www.google.com/s2/favicons?domain=amazon.in&sz=64',
      dealUrl: 'https://www.amazon.in/s?k=Samsung+Galaxy+M35+5G&tag=axevora06-21',
      imageUrl: 'https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6565/6565784_sd.jpg',
      imageSourceDomain: 'bestbuy.com',
      dealType: 'PRODUCT_DEAL',
      verificationStatus: 'SOURCE_STATED'
    },
    {
      id: 'ph-9',
      name: 'Nothing Phone (2a) 5G (8GB RAM, 128GB, Custom Dimensity 7200 Pro, Glyph Interface)',
      brand: 'Nothing',
      model: 'Phone (2a)',
      category: 'phones',
      price: 23999,
      originalPrice: 25999,
      discountPercentage: 8,
      currency: 'INR',
      rating: 4.4,
      reviewCount: 6500,
      axevoraScore: 9.0,
      scoreLabel: 'Design Forward',
      badge: 'Top Rated',
      specs: {
        processor: 'MediaTek Dimensity 7200 Pro 4nm',
        ram: '8GB RAM',
        storage: '128GB Storage',
        display: '6.7" 120Hz Flexible AMOLED (Symmetrical Bezels)',
        battery: '5000 mAh + 45W Fast Charge',
        camera: '50MP OIS Main + 50MP Ultra-Wide',
        os: 'Nothing OS 2.6 (Zero Bloatware)'
      },
      whyWeLikeIt: 'Unique transparent design with functional Glyph notification lighting and dual 50MP cameras.',
      bestFor: 'Design Enthusiasts, Creative Photographers & Minimalists',
      tradeOff: 'No bundled charger in box; back is transparent polycarbonate.',
      merchantName: 'Flipkart',
      merchantLogoUrl: 'https://www.google.com/s2/favicons?domain=flipkart.com&sz=64',
      dealUrl: 'https://www.flipkart.com/search?q=nothing+phone+2a',
      imageUrl: 'https://i5.walmartimages.com/asr/3ce63198-f037-4a9d-a09f-bc969b02be07.31070f3a5d522035a447be00193fc354.jpeg',
      imageSourceDomain: 'walmart.com',
      dealType: 'PRODUCT_DEAL',
      verificationStatus: 'SOURCE_STATED'
    },
    {
      id: 'ph-10',
      name: 'Redmi 13C 5G (4GB RAM, 128GB, Dimensity 6100+, 90Hz Display)',
      brand: 'Xiaomi',
      model: 'Redmi 13C 5G',
      category: 'phones',
      price: 9499,
      originalPrice: 13999,
      discountPercentage: 32,
      currency: 'INR',
      rating: 4.1,
      reviewCount: 11200,
      axevoraScore: 8.3,
      scoreLabel: 'Budget 5G King',
      badge: 'Best Value',
      specs: {
        processor: 'MediaTek Dimensity 6100+ 5G',
        ram: '4GB RAM',
        storage: '128GB UFS 2.2 Storage',
        display: '6.74" 90Hz HD+ Star Trail Design',
        battery: '5000 mAh + 18W Fast Charge',
        camera: '50MP AI Dual Camera',
        os: 'MIUI 14'
      },
      whyWeLikeIt: 'Sub-₹10k genuine 5G connectivity with fast UFS 2.2 storage and star-trail shimmering back.',
      bestFor: 'First-time 5G Smartphone Buyers, Parents & Delivery Executives',
      tradeOff: '720p HD+ resolution display.',
      merchantName: 'Amazon',
      merchantLogoUrl: 'https://www.google.com/s2/favicons?domain=amazon.in&sz=64',
      dealUrl: 'https://www.amazon.in/s?k=Redmi+13C+5G&tag=axevora06-21',
      imageUrl: 'https://i5.walmartimages.com/asr/3ce63198-f037-4a9d-a09f-bc969b02be07.31070f3a5d522035a447be00193fc354.jpeg',
      imageSourceDomain: 'walmart.com',
      dealType: 'PRODUCT_DEAL',
      verificationStatus: 'SOURCE_STATED'
    }
  ],

  tvs: [
    {
      id: 'tv-1',
      name: 'Samsung 55 Inch Crystal 4K Dynamic Ultra HD Smart TV (UA55DUE70BKLXL)',
      brand: 'Samsung',
      model: 'UA55DUE70BKLXL',
      category: 'tvs',
      price: 41990,
      originalPrice: 64900,
      discountPercentage: 35,
      currency: 'INR',
      rating: 4.4,
      reviewCount: 4200,
      axevoraScore: 9.1,
      scoreLabel: 'Outstanding',
      badge: 'Best Overall',
      specs: {
        display: '55" 4K UHD (3840x2160) Crystal Processor 4K',
        os: 'Samsung Tizen OS with Knox Security',
        battery: '20W 2CH Speakers with OTS Lite & Q-Symphony',
        camera: '3 HDMI Ports (eARC) + 1 USB Port',
        ram: 'HDR10+ & Contrast Enhancer'
      },
      whyWeLikeIt: 'Crystal 4K processor upscaling with vibrant PurColor and Knox security architecture.',
      bestFor: 'Home Theater, Sports & High-Definition OTT Streaming',
      tradeOff: '60Hz refresh rate (standard in budget 4K range).',
      merchantName: 'Amazon',
      merchantLogoUrl: 'https://www.google.com/s2/favicons?domain=amazon.in&sz=64',
      dealUrl: 'https://www.amazon.in/s?k=Samsung+55+inch+4K+TV&tag=axevora06-21',
      imageUrl: 'https://pisces.bbystatic.com/image2/BestBuy_US/images/products/f4d18627-1422-4a00-ab64-eb061eb00236.jpg',
      imageSourceDomain: 'bestbuy.com',
      dealType: 'PRODUCT_DEAL',
      verificationStatus: 'SOURCE_STATED'
    },
    {
      id: 'tv-2',
      name: 'LG 55 Inch 4K Ultra HD Smart LED TV (55UR7500PSC)',
      brand: 'LG',
      model: '55UR7500PSC',
      category: 'tvs',
      price: 43990,
      originalPrice: 71990,
      discountPercentage: 39,
      currency: 'INR',
      rating: 4.4,
      reviewCount: 3800,
      axevoraScore: 9.0,
      scoreLabel: 'Top Performer',
      badge: 'Best Value',
      specs: {
        display: '55" 4K UHD with α5 Gen6 AI Processor 4K',
        os: 'webOS 23 with User Profiles & Magic Remote Support',
        battery: '20W AI Sound Pro (Virtual 5.1.2 Up-mix)',
        camera: '3 HDMI 2.0 (eARC, ALLM) + 2 USB',
        ram: 'HDR10 Pro + Filmmaker Mode'
      },
      whyWeLikeIt: 'α5 AI Processor with ALLM low-latency game optimizer and webOS interface.',
      bestFor: 'Family Movies, Console Gaming & AirPlay Casting',
      tradeOff: 'Magic Remote is sold separately on some budget sub-variants.',
      merchantName: 'Flipkart',
      merchantLogoUrl: 'https://www.google.com/s2/favicons?domain=flipkart.com&sz=64',
      dealUrl: 'https://www.flipkart.com/search?q=LG+55+inch+4k+tv',
      imageUrl: 'https://pisces.bbystatic.com/image2/BestBuy_US/images/products/f4d18627-1422-4a00-ab64-eb061eb00236.jpg',
      imageSourceDomain: 'bestbuy.com',
      dealType: 'PRODUCT_DEAL',
      verificationStatus: 'SOURCE_STATED'
    },
    {
      id: 'tv-3',
      name: 'Sony Bravia 55 Inch 4K Ultra HD Smart LED Google TV (KD-55X74L)',
      brand: 'Sony',
      model: 'KD-55X74L',
      category: 'tvs',
      price: 54990,
      originalPrice: 99900,
      discountPercentage: 45,
      currency: 'INR',
      rating: 4.7,
      reviewCount: 6500,
      axevoraScore: 9.4,
      scoreLabel: 'Best Picture Quality',
      badge: 'Editor Choice',
      specs: {
        display: '55" 4K HDR X1 Picture Processor',
        os: 'Google TV with Voice Search & Apple AirPlay',
        battery: '20W Open Baffle Speaker with Dolby Audio',
        camera: '3 HDMI (eARC) + 2 USB + Dual Wi-Fi',
        ram: 'Live Color & 4K X-Reality PRO'
      },
      whyWeLikeIt: 'Sony X1 4K HDR Processor delivers natural skin tones and deep image processing.',
      bestFor: 'Cinema Purists, Sports Enthusiasts & Google Ecosystem',
      tradeOff: 'Slightly higher price point compared to domestic competitors.',
      merchantName: 'Croma',
      merchantLogoUrl: 'https://www.google.com/s2/favicons?domain=croma.com&sz=64',
      dealUrl: 'https://www.croma.com/searchB?q=Sony+Bravia+55+inch+4k',
      imageUrl: 'https://pisces.bbystatic.com/image2/BestBuy_US/images/products/f4d18627-1422-4a00-ab64-eb061eb00236.jpg',
      imageSourceDomain: 'bestbuy.com',
      dealType: 'PRODUCT_DEAL',
      verificationStatus: 'SOURCE_STATED'
    },
    {
      id: 'tv-4',
      name: 'Xiaomi 55 Inch X Pro 4K Dolby Vision IQ Google TV',
      brand: 'Xiaomi',
      model: 'X Pro 55',
      category: 'tvs',
      price: 37999,
      originalPrice: 49999,
      discountPercentage: 24,
      currency: 'INR',
      rating: 4.3,
      reviewCount: 5100,
      axevoraScore: 8.9,
      scoreLabel: 'Sound & Display Leader',
      badge: 'Best Value',
      specs: {
        display: '55" 4K UHD with Dolby Vision IQ & HDR10+',
        os: 'Google TV with PatchWall 4+',
        battery: '30W Box Speakers with Dolby Audio & DTS:X',
        camera: '3 HDMI 2.1 (eARC, ALLM) + 2 USB',
        ram: '2GB RAM + 32GB Storage'
      },
      whyWeLikeIt: 'Punchy 30W built-in box speakers with Dolby Vision IQ ambient light adaptation.',
      bestFor: 'Living Rooms, High-Volume Movies without Soundbar',
      tradeOff: 'PatchWall interface can show promotional content.',
      merchantName: 'Amazon',
      merchantLogoUrl: 'https://www.google.com/s2/favicons?domain=amazon.in&sz=64',
      dealUrl: 'https://www.amazon.in/s?k=Xiaomi+55+inch+X+Pro+4K+TV&tag=axevora06-21',
      imageUrl: 'https://pisces.bbystatic.com/image2/BestBuy_US/images/products/f4d18627-1422-4a00-ab64-eb061eb00236.jpg',
      imageSourceDomain: 'bestbuy.com',
      dealType: 'PRODUCT_DEAL',
      verificationStatus: 'SOURCE_STATED'
    },
    {
      id: 'tv-5',
      name: 'TCL 55 Inch 4K Metallic Bezel-Less Google TV (55V6B)',
      brand: 'TCL',
      model: '55V6B',
      category: 'tvs',
      price: 28990,
      originalPrice: 65990,
      discountPercentage: 56,
      currency: 'INR',
      rating: 4.2,
      reviewCount: 3200,
      axevoraScore: 8.6,
      scoreLabel: 'Budget 4K Champion',
      badge: 'Best Value',
      specs: {
        display: '55" 4K UHD (3840x2160) HDR10',
        os: 'Google TV with Hands-Free Voice Control',
        battery: '24W Integrated Dolby Audio Speakers',
        camera: '3 HDMI 2.1 + 1 USB 3.0',
        ram: '2GB RAM + 16GB Storage'
      },
      whyWeLikeIt: 'Sub-₹30k price point for a massive 55-inch metallic bezel-less 4K screen.',
      bestFor: 'First-time 4K TV Buyers & Budget Home Setups',
      tradeOff: 'Viewing angles on the VA panel are optimal directly in front.',
      merchantName: 'Amazon',
      merchantLogoUrl: 'https://www.google.com/s2/favicons?domain=amazon.in&sz=64',
      dealUrl: 'https://www.amazon.in/s?k=TCL+55+inch+4K+TV&tag=axevora06-21',
      imageUrl: 'https://pisces.bbystatic.com/image2/BestBuy_US/images/products/f4d18627-1422-4a00-ab64-eb061eb00236.jpg',
      imageSourceDomain: 'bestbuy.com',
      dealType: 'PRODUCT_DEAL',
      verificationStatus: 'SOURCE_STATED'
    },
    {
      id: 'tv-6',
      name: 'Hisense 55 Inch 4K QLED Smart Google TV (55E7K)',
      brand: 'Hisense',
      model: '55E7K QLED',
      category: 'tvs',
      price: 33990,
      originalPrice: 59990,
      discountPercentage: 43,
      currency: 'INR',
      rating: 4.3,
      reviewCount: 2100,
      axevoraScore: 8.9,
      scoreLabel: 'QLED Color Leader',
      badge: 'Best Performance',
      specs: {
        display: '55" 4K Quantum Dot QLED (1 Billion Colors)',
        os: 'Google TV with Game Mode Plus (VRR & ALLM)',
        battery: '24W Dolby Atmos Sound System',
        camera: '3 HDMI 2.1 Ports + Dual-Band Wi-Fi',
        ram: 'Dolby Vision + MEMC Motion Smoothing'
      },
      whyWeLikeIt: 'Quantum Dot QLED color reproduction with ultra-rich color gamut at an LED price.',
      bestFor: 'HDR Gaming, Colorful 4K Nature Documentaries',
      tradeOff: 'Native panel refresh rate is 60Hz.',
      merchantName: 'Flipkart',
      merchantLogoUrl: 'https://www.google.com/s2/favicons?domain=flipkart.com&sz=64',
      dealUrl: 'https://www.flipkart.com/search?q=Hisense+55+inch+QLED+TV',
      imageUrl: 'https://pisces.bbystatic.com/image2/BestBuy_US/images/products/f4d18627-1422-4a00-ab64-eb061eb00236.jpg',
      imageSourceDomain: 'bestbuy.com',
      dealType: 'PRODUCT_DEAL',
      verificationStatus: 'SOURCE_STATED'
    },
    {
      id: 'tv-7',
      name: 'Acer 55 Inch Advanced I Series 4K Google TV (AR55GR2851UDFL)',
      brand: 'Acer',
      model: 'AR55GR2851UDFL',
      category: 'tvs',
      price: 29999,
      originalPrice: 47999,
      discountPercentage: 38,
      currency: 'INR',
      rating: 4.2,
      reviewCount: 1900,
      axevoraScore: 8.5,
      scoreLabel: 'Great Value',
      badge: 'Best Value',
      specs: {
        display: '55" 4K UHD 1.07 Billion Colors HDR10',
        os: 'Google TV with Dual-Band Wi-Fi',
        battery: '36W High-Fidelity PRO Speakers with Dolby Atmos',
        camera: '3 HDMI 2.1 + 2 USB',
        ram: '2GB RAM + 16GB Storage'
      },
      whyWeLikeIt: 'Massive 36W high-output Dolby Atmos sound that fills large living halls.',
      bestFor: 'Large Rooms, Loud Music & Group Watching',
      tradeOff: 'Remote build is plastic and lightweight.',
      merchantName: 'Amazon',
      merchantLogoUrl: 'https://www.google.com/s2/favicons?domain=amazon.in&sz=64',
      dealUrl: 'https://www.amazon.in/s?k=Acer+55+inch+4K+Google+TV&tag=axevora06-21',
      imageUrl: 'https://pisces.bbystatic.com/image2/BestBuy_US/images/products/f4d18627-1422-4a00-ab64-eb061eb00236.jpg',
      imageSourceDomain: 'bestbuy.com',
      dealType: 'PRODUCT_DEAL',
      verificationStatus: 'SOURCE_STATED'
    },
    {
      id: 'tv-8',
      name: 'OnePlus 55 Inch Y Series 4K Ultra HD Smart Android TV (55Y1S Pro)',
      brand: 'OnePlus',
      model: '55Y1S Pro',
      category: 'tvs',
      price: 36990,
      originalPrice: 49999,
      discountPercentage: 26,
      currency: 'INR',
      rating: 4.3,
      reviewCount: 6800,
      axevoraScore: 8.8,
      scoreLabel: 'Smart Ecosystem',
      badge: 'Best for Study',
      specs: {
        display: '55" 4K UHD Gamma Engine HDR10+',
        os: 'Android TV with OnePlus Connect 2.0',
        battery: '24W Output with Dolby Audio',
        camera: '3 HDMI 2.1 (ALLM) + 2 USB',
        ram: 'Auto Low Latency Mode (ALLM)'
      },
      whyWeLikeIt: 'OnePlus Connect ecosystem lets you control the TV, track sleep, and cast seamlessly from mobile.',
      bestFor: 'OnePlus Ecosystem Users & Smart Home Integration',
      tradeOff: 'Runs Android TV 10 rather than Google TV.',
      merchantName: 'Amazon',
      merchantLogoUrl: 'https://www.google.com/s2/favicons?domain=amazon.in&sz=64',
      dealUrl: 'https://www.amazon.in/s?k=OnePlus+55+inch+4K+TV&tag=axevora06-21',
      imageUrl: 'https://pisces.bbystatic.com/image2/BestBuy_US/images/products/f4d18627-1422-4a00-ab64-eb061eb00236.jpg',
      imageSourceDomain: 'bestbuy.com',
      dealType: 'PRODUCT_DEAL',
      verificationStatus: 'SOURCE_STATED'
    },
    {
      id: 'tv-9',
      name: 'Toshiba 55 Inch 4K Ultra HD Smart QLED TV (55M550MP)',
      brand: 'Toshiba',
      model: '55M550MP QLED',
      category: 'tvs',
      price: 39999,
      originalPrice: 79990,
      discountPercentage: 50,
      currency: 'INR',
      rating: 4.4,
      reviewCount: 1400,
      axevoraScore: 9.0,
      scoreLabel: 'Bass Master QLED',
      badge: 'Editor Choice',
      specs: {
        display: '55" Quantum Dot 4K with REGZA Engine ZRi',
        os: 'Google TV with Apple HomeKit & AirPlay',
        battery: '49W 2.1ch Audio with Built-in REGZA Bass Woofer',
        camera: '3 HDMI 2.1 + 2 USB',
        ram: 'Full Array Local Dimming + Dolby Vision'
      },
      whyWeLikeIt: 'Built-in 2.1 channel speaker system with 49W output and integrated dedicated subwoofer.',
      bestFor: 'Music Lovers & Action Movie Fans without separate sound systems',
      tradeOff: 'Slightly thicker profile due to internal subwoofer housing.',
      merchantName: 'Amazon',
      merchantLogoUrl: 'https://www.google.com/s2/favicons?domain=amazon.in&sz=64',
      dealUrl: 'https://www.amazon.in/s?k=Toshiba+55+inch+QLED+TV&tag=axevora06-21',
      imageUrl: 'https://pisces.bbystatic.com/image2/BestBuy_US/images/products/f4d18627-1422-4a00-ab64-eb061eb00236.jpg',
      imageSourceDomain: 'bestbuy.com',
      dealType: 'PRODUCT_DEAL',
      verificationStatus: 'SOURCE_STATED'
    },
    {
      id: 'tv-10',
      name: 'Samsung 55 Inch QLED 4K Q60D Smart TV (QA55Q60DAULXL)',
      brand: 'Samsung',
      model: 'QA55Q60DAULXL',
      category: 'tvs',
      price: 63990,
      originalPrice: 94900,
      discountPercentage: 33,
      currency: 'INR',
      rating: 4.6,
      reviewCount: 1800,
      axevoraScore: 9.4,
      scoreLabel: 'Premium QLED',
      badge: 'Best Overall',
      specs: {
        display: '55" 100% Color Volume with Quantum Dot QLED',
        os: 'Tizen OS with SolarCell Remote',
        battery: '20W 2CH Object Tracking Sound Lite',
        camera: '3 HDMI (eARC) + 2 USB + Bluetooth 5.2',
        ram: 'Quantum HDR & AirSlim Design (26mm thin)'
      },
      whyWeLikeIt: 'Ultra-thin AirSlim profile (26mm) with 100% Color Volume and eco-friendly solar-powered remote.',
      bestFor: 'Luxury Wall Mount Living Rooms & Precision 4K Masterpieces',
      tradeOff: 'Higher investment compared to standard Crystal UHD models.',
      merchantName: 'Amazon',
      merchantLogoUrl: 'https://www.google.com/s2/favicons?domain=amazon.in&sz=64',
      dealUrl: 'https://www.amazon.in/s?k=Samsung+55+inch+QLED+Q60D&tag=axevora06-21',
      imageUrl: 'https://pisces.bbystatic.com/image2/BestBuy_US/images/products/f4d18627-1422-4a00-ab64-eb061eb00236.jpg',
      imageSourceDomain: 'bestbuy.com',
      dealType: 'PRODUCT_DEAL',
      verificationStatus: 'SOURCE_STATED'
    }
  ],

  audio: [
    {
      id: 'aud-1',
      name: 'Sony WH-1000XM5 Wireless Industry Leading ANC Headphones (30hr Battery, LDAC)',
      brand: 'Sony',
      model: 'WH-1000XM5',
      category: 'audio',
      price: 26990,
      originalPrice: 34990,
      discountPercentage: 23,
      currency: 'INR',
      rating: 4.7,
      reviewCount: 9400,
      axevoraScore: 9.6,
      scoreLabel: 'ANC Industry Standard',
      badge: 'Best Overall',
      specs: {
        processor: 'Integrated Processor V1 + HD QN1',
        battery: '30 Hours ANC Playback + 3-Min Fast Charge',
        display: '8 Microphones for Auto NC Optimizer',
        os: 'Multipoint Bluetooth 5.2 + LDAC Hi-Res Audio'
      },
      whyWeLikeIt: 'Unrivalled active noise cancellation with 8 precision microphones and Speak-to-Chat tech.',
      bestFor: 'Frequent Flyers, Office Focus & Audiophile Streaming',
      tradeOff: 'Non-folding headband takes slightly more space in travel backpacks.',
      merchantName: 'Amazon',
      merchantLogoUrl: 'https://www.google.com/s2/favicons?domain=amazon.in&sz=64',
      dealUrl: 'https://www.amazon.in/s?k=Sony+WH-1000XM5&tag=axevora06-21',
      imageUrl: 'https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6525/6525404_sd.jpg',
      imageSourceDomain: 'bestbuy.com',
      dealType: 'PRODUCT_DEAL',
      verificationStatus: 'SOURCE_STATED'
    },
    {
      id: 'aud-2',
      name: 'OnePlus Buds 3 TWS (49dB Smart ANC, LHDC 5.0, Dual Drivers, 44hr Battery)',
      brand: 'OnePlus',
      model: 'Buds 3',
      category: 'audio',
      price: 4999,
      originalPrice: 6499,
      discountPercentage: 23,
      currency: 'INR',
      rating: 4.5,
      reviewCount: 6800,
      axevoraScore: 9.1,
      scoreLabel: 'Outstanding Value',
      badge: 'Best Value',
      specs: {
        processor: 'Dual Drivers (10.4mm Woofer + 6mm Tweeter)',
        battery: '44 Hours Total Battery with Case + Fast Charge',
        display: '49dB Smart Adaptive Active Noise Cancellation',
        os: 'LHDC 5.0 Hi-Res Audio & Dual Device Connection'
      },
      whyWeLikeIt: 'Coaxial dual-driver acoustic architecture with sliding volume touch controls on stems.',
      bestFor: 'Daily Commute, Workouts (IP55) & High-Bitrate Music',
      tradeOff: 'LHDC codec requires a compatible Android smartphone for maximum bitrate.',
      merchantName: 'Amazon',
      merchantLogoUrl: 'https://www.google.com/s2/favicons?domain=amazon.in&sz=64',
      dealUrl: 'https://www.amazon.in/s?k=OnePlus+Buds+3&tag=axevora06-21',
      imageUrl: 'https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6525/6525404_sd.jpg',
      imageSourceDomain: 'bestbuy.com',
      dealType: 'PRODUCT_DEAL',
      verificationStatus: 'SOURCE_STATED'
    },
    {
      id: 'aud-3',
      name: 'Realme Buds Air 6 Pro (50dB ANC, Hi-Res LDAC, 11mm + 6mm Dual Drivers)',
      brand: 'Realme',
      model: 'Buds Air 6 Pro',
      category: 'audio',
      price: 4499,
      originalPrice: 7999,
      discountPercentage: 44,
      currency: 'INR',
      rating: 4.4,
      reviewCount: 3200,
      axevoraScore: 9.0,
      scoreLabel: 'Hi-Res Value',
      badge: 'Best Value',
      specs: {
        processor: '11mm Bass Driver + 6mm Micro-Planar Tweeter',
        battery: '40 Hours Playback + 10-Min Charge for 7 Hours',
        display: '50dB Deep Hybrid ANC with 4000Hz Ultra-Wide Band',
        os: 'LDAC Certified 990kbps Lossless Transmission'
      },
      whyWeLikeIt: 'LDAC support under ₹4.5k with planar tweeter clarity and 50dB deep noise cancellation.',
      bestFor: 'Acoustic Clarity, Vocal Tracks & Commute Isolation',
      tradeOff: 'Glossy case can catch micro-scratches over time.',
      merchantName: 'Flipkart',
      merchantLogoUrl: 'https://www.google.com/s2/favicons?domain=flipkart.com&sz=64',
      dealUrl: 'https://www.flipkart.com/search?q=realme+buds+air+6+pro',
      imageUrl: 'https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6525/6525404_sd.jpg',
      imageSourceDomain: 'bestbuy.com',
      dealType: 'PRODUCT_DEAL',
      verificationStatus: 'SOURCE_STATED'
    },
    {
      id: 'aud-4',
      name: 'boAt Nirvana Ion ANC (32dB ANC, 120hr Monstrous Battery, Dual EQ)',
      brand: 'boAt',
      model: 'Nirvana Ion ANC',
      category: 'audio',
      price: 2499,
      originalPrice: 9990,
      discountPercentage: 75,
      currency: 'INR',
      rating: 4.2,
      reviewCount: 14200,
      axevoraScore: 8.7,
      scoreLabel: 'Battery Champion',
      badge: 'Best Battery',
      specs: {
        processor: '10mm Crystal Bionic Sound Drivers',
        battery: '120 Hours Total Battery Life (24hr Earbuds)',
        display: '32dB Active Noise Cancellation + Quad Mics ENx',
        os: 'In-Ear Detection & Multipoint Pairing'
      },
      whyWeLikeIt: 'Astonishing 24-hour standalone earbud playback (120 hrs with case) eliminates weekly charging anxiety.',
      bestFor: 'Non-stop Calling, Long Train Travels & Students',
      tradeOff: 'Earbud stem is slightly larger due to the massive internal battery cell.',
      merchantName: 'Amazon',
      merchantLogoUrl: 'https://www.google.com/s2/favicons?domain=amazon.in&sz=64',
      dealUrl: 'https://www.amazon.in/s?k=boAt+Nirvana+Ion+ANC&tag=axevora06-21',
      imageUrl: 'https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6525/6525404_sd.jpg',
      imageSourceDomain: 'bestbuy.com',
      dealType: 'PRODUCT_DEAL',
      verificationStatus: 'SOURCE_STATED'
    },
    {
      id: 'aud-5',
      name: 'Sony WH-CH720N Wireless Over-Ear ANC Headphones (V1 Chip, 35hr Battery, 192g)',
      brand: 'Sony',
      model: 'WH-CH720N',
      category: 'audio',
      price: 7990,
      originalPrice: 14990,
      discountPercentage: 47,
      currency: 'INR',
      rating: 4.4,
      reviewCount: 5100,
      axevoraScore: 8.9,
      scoreLabel: 'Comfort King',
      badge: 'Best for Study',
      specs: {
        processor: 'Sony Integrated Processor V1 (from 1000XM5)',
        battery: '35 Hours Battery Life with ANC On',
        display: 'Dual Noise Sensor Technology',
        os: 'DSEE Upscaling & Multipoint Connection'
      },
      whyWeLikeIt: 'Weighs only 192g with ultra-soft ear cushions and flagship V1 processor noise cancellation.',
      bestFor: 'All-Day Work from Home, Coding & Study Sessions',
      tradeOff: 'No touch controls (uses tactile buttons on earcups).',
      merchantName: 'Amazon',
      merchantLogoUrl: 'https://www.google.com/s2/favicons?domain=amazon.in&sz=64',
      dealUrl: 'https://www.amazon.in/s?k=Sony+WH-CH720N&tag=axevora06-21',
      imageUrl: 'https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6525/6525404_sd.jpg',
      imageSourceDomain: 'bestbuy.com',
      dealType: 'PRODUCT_DEAL',
      verificationStatus: 'SOURCE_STATED'
    },
    {
      id: 'aud-6',
      name: 'JBL Live Pro 2 TWS (True Adaptive ANC, 40hr Battery, 6 Mics, Wireless Charge)',
      brand: 'JBL',
      model: 'Live Pro 2',
      category: 'audio',
      price: 8999,
      originalPrice: 16999,
      discountPercentage: 47,
      currency: 'INR',
      rating: 4.3,
      reviewCount: 2900,
      axevoraScore: 8.9,
      scoreLabel: 'Signature Sound',
      badge: 'Editor Choice',
      specs: {
        processor: '11mm Dynamic Drivers with JBL Signature Sound',
        battery: '40 Hours Playback (10+30) + Qi Wireless Charging',
        display: 'True Adaptive Noise Cancelling with Smart Ambient',
        os: '6 Beamforming Microphones for Crystal Calls'
      },
      whyWeLikeIt: 'JBL Signature Bass response with wireless charging case and 6 beamforming microphones.',
      bestFor: 'Bass Enthusiasts, Business Calls & Gym Workouts',
      tradeOff: 'Stem size is standard oval.',
      merchantName: 'Amazon',
      merchantLogoUrl: 'https://www.google.com/s2/favicons?domain=amazon.in&sz=64',
      dealUrl: 'https://www.amazon.in/s?k=JBL+Live+Pro+2&tag=axevora06-21',
      imageUrl: 'https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6525/6525404_sd.jpg',
      imageSourceDomain: 'bestbuy.com',
      dealType: 'PRODUCT_DEAL',
      verificationStatus: 'SOURCE_STATED'
    },
    {
      id: 'aud-7',
      name: 'Apple AirPods Pro (2nd Gen with USB-C, H2 Chip, 2x ANC, MagSafe Case)',
      brand: 'Apple',
      model: 'AirPods Pro 2 USB-C',
      category: 'audio',
      price: 21999,
      originalPrice: 24900,
      discountPercentage: 12,
      currency: 'INR',
      rating: 4.8,
      reviewCount: 18500,
      axevoraScore: 9.7,
      scoreLabel: 'Benchmark In-Ear ANC',
      badge: 'Best Overall',
      specs: {
        processor: 'Apple H2 Headphone Chip + U1 Case Chip',
        battery: '30 Hours Total with MagSafe USB-C Case',
        display: '2x Active Noise Cancellation + Adaptive Transparency',
        os: 'Personalized Spatial Audio with Dynamic Head Tracking'
      },
      whyWeLikeIt: 'Adaptive Audio dynamically blends active noise cancellation and transparency as your environment changes.',
      bestFor: 'iPhone/Mac Ecosystem Users, Commuters & Crystal Calls',
      tradeOff: 'Full feature set requires Apple ecosystem devices.',
      merchantName: 'Amazon',
      merchantLogoUrl: 'https://www.google.com/s2/favicons?domain=amazon.in&sz=64',
      dealUrl: 'https://www.amazon.in/s?k=AirPods+Pro+2+USB-C&tag=axevora06-21',
      imageUrl: 'https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6525/6525404_sd.jpg',
      imageSourceDomain: 'bestbuy.com',
      dealType: 'PRODUCT_DEAL',
      verificationStatus: 'SOURCE_STATED'
    },
    {
      id: 'aud-8',
      name: 'CMF by Nothing Buds Pro 2 (50dB Smart ANC, Smart Dial Roller Case, LDAC)',
      brand: 'Nothing',
      model: 'CMF Buds Pro 2',
      category: 'audio',
      price: 3999,
      originalPrice: 5999,
      discountPercentage: 33,
      currency: 'INR',
      rating: 4.4,
      reviewCount: 3100,
      axevoraScore: 8.8,
      scoreLabel: 'Innovative Design',
      badge: 'Best Value',
      specs: {
        processor: 'Dual Drivers (11mm Bass Driver + 6mm Micro-Planar)',
        battery: '43 Hours Total Battery + 10-Min Fast Charge',
        display: '50dB Hybrid Active Noise Cancellation',
        os: 'Customizable Smart Dial on Charging Case + LDAC'
      },
      whyWeLikeIt: 'Revolutionary customizable physical Smart Dial roller on the case for instant volume and ANC control.',
      bestFor: 'Gadget Enthusiasts, Students & Tactile Control Lovers',
      tradeOff: 'Case is slightly thicker due to the rotating dial mechanism.',
      merchantName: 'Flipkart',
      merchantLogoUrl: 'https://www.google.com/s2/favicons?domain=flipkart.com&sz=64',
      dealUrl: 'https://www.flipkart.com/search?q=CMF+Buds+Pro+2',
      imageUrl: 'https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6525/6525404_sd.jpg',
      imageSourceDomain: 'bestbuy.com',
      dealType: 'PRODUCT_DEAL',
      verificationStatus: 'SOURCE_STATED'
    },
    {
      id: 'aud-9',
      name: 'Soundcore by Anker Space Q45 (98% Noise Reduction, LDAC Hi-Res, 65hr Battery)',
      brand: 'Anker',
      model: 'Space Q45',
      category: 'audio',
      price: 8999,
      originalPrice: 14999,
      discountPercentage: 40,
      currency: 'INR',
      rating: 4.5,
      reviewCount: 4200,
      axevoraScore: 9.1,
      scoreLabel: 'Long-Haul Champion',
      badge: 'Best Battery',
      specs: {
        processor: '40mm Double-Layer Silk & Ceramic Diaphragm Drivers',
        battery: '65 Hours Playback (50 Hours with ANC On)',
        display: 'Adaptive 3-Stage Active Noise Cancelling System',
        os: 'LDAC Wireless Hi-Res Audio & Custom App EQ'
      },
      whyWeLikeIt: 'Massive 65-hour battery life with 5-minute charge giving 4 hours of music and hard travel case included.',
      bestFor: 'Long International Flights, Coders & Endurance Listeners',
      tradeOff: 'Earcups are plush and deep, which can feel warm in high-humidity summers.',
      merchantName: 'Amazon',
      merchantLogoUrl: 'https://www.google.com/s2/favicons?domain=amazon.in&sz=64',
      dealUrl: 'https://www.amazon.in/s?k=Anker+Space+Q45&tag=axevora06-21',
      imageUrl: 'https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6525/6525404_sd.jpg',
      imageSourceDomain: 'bestbuy.com',
      dealType: 'PRODUCT_DEAL',
      verificationStatus: 'SOURCE_STATED'
    },
    {
      id: 'aud-10',
      name: 'Bose QuietComfort 45 Bluetooth Wireless Noise Cancelling Headphones',
      brand: 'Bose',
      model: 'QuietComfort 45',
      category: 'audio',
      price: 21990,
      originalPrice: 29900,
      discountPercentage: 26,
      currency: 'INR',
      rating: 4.6,
      reviewCount: 7100,
      axevoraScore: 9.4,
      scoreLabel: 'Ergonomic Benchmark',
      badge: 'Best Performance',
      specs: {
        processor: 'Bose TriPort Acoustic Architecture',
        battery: '24 Hours Playback on Single Charge',
        display: 'Acoustic Noise Cancelling with Quiet & Aware Modes',
        os: 'Plush Synthetic Leather & Cast-Metal Hinges'
      },
      whyWeLikeIt: 'Legendary Bose lightweight comfort with zero clamping fatigue during 8+ hour continuous wear.',
      bestFor: 'Office Professionals, Frequent Travelers & Sensitive Ears',
      tradeOff: 'No custom adjustable EQ presets on older firmware (updated in Bose app).',
      merchantName: 'Croma',
      merchantLogoUrl: 'https://www.google.com/s2/favicons?domain=croma.com&sz=64',
      dealUrl: 'https://www.croma.com/searchB?q=Bose+QuietComfort+45',
      imageUrl: 'https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6525/6525404_sd.jpg',
      imageSourceDomain: 'bestbuy.com',
      dealType: 'PRODUCT_DEAL',
      verificationStatus: 'SOURCE_STATED'
    }
  ]
};

export const onRequestGet = async (context: { request: Request; env?: Record<string, unknown> }) => {
  const { request, env } = context;
  const url = new URL(request.url);
  const categoryParam = (url.searchParams.get('category') || 'all').toLowerCase();

  let resultData: Record<string, DailyProduct[]> = {};

  if (categoryParam === 'all') {
    resultData = DAILY_CURATED_DATA;
  } else if (DAILY_CURATED_DATA[categoryParam]) {
    resultData = {
      [categoryParam]: DAILY_CURATED_DATA[categoryParam]
    };
  } else {
    resultData = {
      [categoryParam]: DAILY_CURATED_DATA['tablets'] || []
    };
  }

  // Enrich all deal URLs through the 3-layer affiliate engine
  const enrichedCategories: Record<string, DailyProduct[]> = {};
  for (const [catKey, products] of Object.entries(resultData)) {
    enrichedCategories[catKey] = await Promise.all(
      products.map(async (prod) => {
        const affiliateUrl = await convertToAffiliateUrl(prod.dealUrl, env);
        return {
          ...prod,
          dealUrl: affiliateUrl
        };
      })
    );
  }

  return new Response(JSON.stringify({
    ok: true,
    success: true,
    date: new Date().toISOString().split('T')[0],
    generatedAt: new Date().toISOString(),
    totalCategories: Object.keys(enrichedCategories).length,
    categories: enrichedCategories
  }), {
    status: 200,
    headers: {
      'Content-Type': 'application/json',
      'Cache-Control': 'public, max-age=3600, s-maxage=14400'
    }
  });
};

export const onRequest = onRequestGet;
