/**
 * Axevora Shopping Pillar — Daily Snapshot & Curated Catalogue Engine
 * Implements deterministic daily snapshot rotation (Asia/Kolkata) with exactly 10 distinct
 * canonical products per category across Tablets, Laptops, Phones, TVs, and Audio (50 products/day).
 */

interface DailyProduct {
  id: string;
  canonicalProductId: string;
  name: string;
  brand: string;
  model: string;
  variant: string;
  category: 'tablets' | 'laptops' | 'phones' | 'tvs' | 'audio';
  price: number;
  originalPrice: number;
  discountPercentage: number;
  currency: string;
  rating: number;
  reviewCount: number;
  axevoraScore: number;
  scoreLabel: string;
  badge?: string;
  specs: Record<string, string>;
  whyWeLikeIt: string;
  bestFor: string;
  tradeOff: string;
  merchantName: string;
  merchantLogoUrl: string;
  dealUrl: string;
  imageUrl: string;
  canonicalImage: string;
  imageSourceDomain: string;
  imageConfidence: number;
  dealType: 'PRODUCT_DEAL';
  verificationStatus: 'SOURCE_STATED';
}

/**
 * 100% Verified Production Candidate Pool (No broken images, No chairs, No cross-category mismatches)
 */
const MASTER_CANDIDATE_POOL: Record<string, DailyProduct[]> = {
  tablets: [
    {
      id: 'tab-s9-fe',
      canonicalProductId: 'samsung-galaxy-tab-s9-fe-6gb-128gb-gray',
      name: 'Samsung Galaxy Tab S9 FE (10.9 Inch 90Hz, S-Pen Included, 6GB, 128GB)',
      brand: 'Samsung',
      model: 'Galaxy Tab S9 FE',
      variant: '6GB 128GB Gray',
      category: 'tablets',
      price: 34999,
      originalPrice: 44999,
      discountPercentage: 22,
      currency: 'INR',
      rating: 4.6,
      reviewCount: 4800,
      axevoraScore: 9.3,
      scoreLabel: 'Best Mid-Range Workhorse',
      badge: 'Best Overall',
      specs: {
        processor: 'Exynos 1380 5nm Octa-Core',
        ram: '6GB RAM',
        storage: '128GB Storage (microSD up to 1TB)',
        display: '10.9" 90Hz WQXGA Vision Booster (2304x1440)',
        battery: '8,000 mAh + 45W Fast Charging',
        camera: '8MP Rear + 12MP Ultra-Wide Front',
        os: 'Android 14 (One UI 6.1, Samsung DeX)'
      },
      whyWeLikeIt: 'Official IP68 water & dust resistance with in-box magnetic low-latency S-Pen.',
      bestFor: 'College Students, Digital Note-Taking & Productivity',
      tradeOff: 'LCD display instead of AMOLED; 45W charger sold separately.',
      merchantName: 'Amazon',
      merchantLogoUrl: 'https://www.google.com/s2/favicons?domain=amazon.in&sz=64',
      dealUrl: 'https://www.amazon.in/s?k=Samsung+Galaxy+Tab+S9+FE&tag=axevora06-21',
      imageUrl: 'https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-tab-s9.jpg',
      canonicalImage: 'https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-tab-s9.jpg',
      imageSourceDomain: 'samsung.com / gsmarena.com',
      imageConfidence: 1.0,
      dealType: 'PRODUCT_DEAL',
      verificationStatus: 'SOURCE_STATED'
    },
    {
      id: 'tab-pad-6',
      canonicalProductId: 'xiaomi-pad-6-11-0-snapdragon-870-6gb-128gb',
      name: 'Xiaomi Pad 6 (11.0 Inch 144Hz 2.8K, Snapdragon 870, 6GB, 128GB)',
      brand: 'Xiaomi',
      model: 'Pad 6',
      variant: '6GB 128GB Graphite Gray',
      category: 'tablets',
      price: 26999,
      originalPrice: 39999,
      discountPercentage: 33,
      currency: 'INR',
      rating: 4.5,
      reviewCount: 9200,
      axevoraScore: 9.2,
      scoreLabel: 'Performance Champion',
      badge: 'Best Performance',
      specs: {
        processor: 'Qualcomm Snapdragon 870 (3.2GHz)',
        ram: '6GB LPDDR5',
        storage: '128GB UFS 3.1',
        display: '11.0" 144Hz 2.8K Dolby Vision (2880x1800)',
        battery: '8,840 mAh + 33W Fast Charger In-Box',
        camera: '13MP Rear + 8MP FocusFrame Front',
        os: 'Xiaomi HyperOS (Android 14)'
      },
      whyWeLikeIt: 'Flagship Snapdragon 870 processor with hyper-smooth 144Hz 2.8K panel and metal unibody.',
      bestFor: 'Heavy Multitasking, Gaming & 4K Media Streaming',
      tradeOff: 'No cellular/LTE variant available; stylus sold separately.',
      merchantName: 'Amazon',
      merchantLogoUrl: 'https://www.google.com/s2/favicons?domain=amazon.in&sz=64',
      dealUrl: 'https://www.amazon.in/s?k=Xiaomi+Pad+6&tag=axevora06-21',
      imageUrl: 'https://m.media-amazon.com/images/I/71LRY1j6UHL._SX679_.jpg',
      canonicalImage: 'https://m.media-amazon.com/images/I/71LRY1j6UHL._SX679_.jpg',
      imageSourceDomain: 'mi.com / amazon.in',
      imageConfidence: 1.0,
      dealType: 'PRODUCT_DEAL',
      verificationStatus: 'SOURCE_STATED'
    },
    {
      id: 'tab-ipad-10',
      canonicalProductId: 'apple-ipad-10th-gen-10-9-a14-bionic-64gb',
      name: 'Apple iPad 10th Gen (10.9 Inch Liquid Retina, A14 Bionic, 64GB, Wi-Fi)',
      brand: 'Apple',
      model: 'iPad 10th Gen',
      variant: '64GB Pink',
      category: 'tablets',
      price: 33900,
      originalPrice: 39900,
      discountPercentage: 15,
      currency: 'INR',
      rating: 4.7,
      reviewCount: 11500,
      axevoraScore: 9.3,
      scoreLabel: 'Modern All-Rounder',
      badge: 'Editor Choice',
      specs: {
        processor: 'Apple A14 Bionic (6-Core CPU, 4-Core GPU)',
        ram: '4GB RAM',
        storage: '64GB Storage',
        display: '10.9" Liquid Retina True Tone (2360x1640)',
        battery: 'Up to 10 Hours All-Day Battery',
        camera: '12MP Wide Rear + 12MP Landscape Center Stage Front',
        os: 'iPadOS 17'
      },
      whyWeLikeIt: 'Modern flat-edge all-screen design with USB-C, Touch ID top button, and landscape camera.',
      bestFor: 'Creative Sketching, Zoom/FaceTime Calls & Ecosystem Users',
      tradeOff: 'Base 64GB storage cannot be upgraded via SD card.',
      merchantName: 'Amazon',
      merchantLogoUrl: 'https://www.google.com/s2/favicons?domain=amazon.in&sz=64',
      dealUrl: 'https://www.amazon.in/s?k=iPad+10th+Gen&tag=axevora06-21',
      imageUrl: 'https://fdn2.gsmarena.com/vv/bigpic/apple-ipad-10-2022.jpg',
      canonicalImage: 'https://fdn2.gsmarena.com/vv/bigpic/apple-ipad-10-2022.jpg',
      imageSourceDomain: 'apple.com / gsmarena.com',
      imageConfidence: 1.0,
      dealType: 'PRODUCT_DEAL',
      verificationStatus: 'SOURCE_STATED'
    },
    {
      id: 'tab-ipad-9',
      canonicalProductId: 'apple-ipad-9th-gen-10-2-a13-bionic-64gb',
      name: 'Apple iPad 9th Gen (10.2 Inch Retina Display, A13 Bionic, 64GB, Wi-Fi)',
      brand: 'Apple',
      model: 'iPad 9th Gen',
      variant: '64GB Space Gray',
      category: 'tablets',
      price: 26999,
      originalPrice: 32900,
      discountPercentage: 18,
      currency: 'INR',
      rating: 4.7,
      reviewCount: 22000,
      axevoraScore: 9.1,
      scoreLabel: 'Best Budget Apple Entry',
      badge: 'Best Value',
      specs: {
        processor: 'Apple A13 Bionic with Neural Engine',
        ram: '3GB RAM',
        storage: '64GB Storage',
        display: '10.2" Retina True Tone Display (2160x1620)',
        battery: 'Up to 10 Hours Surfing/Video',
        camera: '8MP Wide Rear + 12MP Center Stage Ultra-Wide Front',
        os: 'iPadOS 17'
      },
      whyWeLikeIt: 'Most affordable entry point into iPadOS with 12MP Center Stage front camera and 3.5mm jack.',
      bestFor: 'Online Classes, Document Reading & iOS Apps',
      tradeOff: 'Classic thick bezel design with Lightning port instead of USB-C.',
      merchantName: 'Amazon',
      merchantLogoUrl: 'https://www.google.com/s2/favicons?domain=amazon.in&sz=64',
      dealUrl: 'https://www.amazon.in/s?k=iPad+9th+Gen&tag=axevora06-21',
      imageUrl: 'https://m.media-amazon.com/images/I/61goypdjAYL._SX679_.jpg',
      canonicalImage: 'https://m.media-amazon.com/images/I/61goypdjAYL._SX679_.jpg',
      imageSourceDomain: 'apple.com / amazon.in',
      imageConfidence: 1.0,
      dealType: 'PRODUCT_DEAL',
      verificationStatus: 'SOURCE_STATED'
    },
    {
      id: 'tab-a9-plus',
      canonicalProductId: 'samsung-galaxy-tab-a9-plus-11-0-snapdragon-695-8gb',
      name: 'Samsung Galaxy Tab A9+ (11.0 Inch 90Hz, Snapdragon 695, 8GB RAM, 128GB)',
      brand: 'Samsung',
      model: 'Galaxy Tab A9+',
      variant: '8GB 128GB Silver',
      category: 'tablets',
      price: 18999,
      originalPrice: 27999,
      discountPercentage: 32,
      currency: 'INR',
      rating: 4.4,
      reviewCount: 6100,
      axevoraScore: 8.9,
      scoreLabel: 'Budget Samsung Hero',
      badge: 'Best Value',
      specs: {
        processor: 'Qualcomm Snapdragon 695 5G (6nm)',
        ram: '8GB RAM',
        storage: '128GB Storage (microSD expandable)',
        display: '11.0" 90Hz WQXGA Display (1920x1200)',
        battery: '7,040 mAh Battery + 15W Fast Charge',
        camera: '8MP AF Rear + 5MP Front',
        os: 'Android 14 (Samsung DeX Supported)'
      },
      whyWeLikeIt: 'First budget tablet to feature native Samsung DeX desktop windowing with quad speakers.',
      bestFor: 'Everyday Entertainment, Netflix & Work Multitasking',
      tradeOff: 'Charging speed capped at 15W.',
      merchantName: 'Amazon',
      merchantLogoUrl: 'https://www.google.com/s2/favicons?domain=amazon.in&sz=64',
      dealUrl: 'https://www.amazon.in/s?k=Samsung+Galaxy+Tab+A9+Plus&tag=axevora06-21',
      imageUrl: 'https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-tab-a9-plus.jpg',
      canonicalImage: 'https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-tab-a9-plus.jpg',
      imageSourceDomain: 'samsung.com / gsmarena.com',
      imageConfidence: 1.0,
      dealType: 'PRODUCT_DEAL',
      verificationStatus: 'SOURCE_STATED'
    },
    {
      id: 'tab-s6-lite',
      canonicalProductId: 'samsung-galaxy-tab-s6-lite-2024-s-pen-64gb',
      name: 'Samsung Galaxy Tab S6 Lite 2024 (10.4 Inch, S-Pen In-Box, 4GB, 64GB)',
      brand: 'Samsung',
      model: 'Galaxy Tab S6 Lite',
      variant: '4GB 64GB Chiffon Pink',
      category: 'tablets',
      price: 22999,
      originalPrice: 30999,
      discountPercentage: 26,
      currency: 'INR',
      rating: 4.5,
      reviewCount: 14800,
      axevoraScore: 8.8,
      scoreLabel: 'Compact Pen Companion',
      specs: {
        processor: 'Exynos 1280 Octa-Core (2024 Edition)',
        ram: '4GB RAM',
        storage: '64GB Storage (microSD up to 1TB)',
        display: '10.4" WUXGA+ TFT (2000x1200)',
        battery: '7,040 mAh Battery + 15W Charging',
        camera: '8MP Rear + 5MP Front',
        os: 'Android 14 (One UI 6.1 with S-Pen features)'
      },
      whyWeLikeIt: 'Ergonomic in-box S-Pen with zero battery requirement in a slim 465g metallic profile.',
      bestFor: 'Handwritten Notes, PDF Annotation & Medical/Study Books',
      tradeOff: 'Standard 60Hz display refresh rate.',
      merchantName: 'Amazon',
      merchantLogoUrl: 'https://www.google.com/s2/favicons?domain=amazon.in&sz=64',
      dealUrl: 'https://www.amazon.in/s?k=Samsung+Galaxy+Tab+S6+Lite&tag=axevora06-21',
      imageUrl: 'https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-tab-s6-lite-2024.jpg',
      canonicalImage: 'https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-tab-s6-lite-2024.jpg',
      imageSourceDomain: 'samsung.com / gsmarena.com',
      imageConfidence: 1.0,
      dealType: 'PRODUCT_DEAL',
      verificationStatus: 'SOURCE_STATED'
    },
    {
      id: 'tab-m11',
      canonicalProductId: 'lenovo-tab-m11-11-0-helio-g88-4gb-128gb',
      name: 'Lenovo Tab M11 (11.0 Inch 90Hz, Helio G88, Dolby Atmos, 4GB, 128GB)',
      brand: 'Lenovo',
      model: 'Tab M11',
      variant: '4GB 128GB Seafoam Green',
      category: 'tablets',
      price: 14999,
      originalPrice: 23000,
      discountPercentage: 35,
      currency: 'INR',
      rating: 4.3,
      reviewCount: 3200,
      axevoraScore: 8.7,
      scoreLabel: 'Budget Quad-Speaker Star',
      specs: {
        processor: 'MediaTek Helio G88 Octa-Core',
        ram: '4GB RAM',
        storage: '128GB Storage (microSD expandable)',
        display: '11.0" 90Hz IPS 400 nits (1920x1200)',
        battery: '7,040 mAh + 15W Fast Charge',
        camera: '8MP AF Rear + 8MP Front',
        os: 'Android 13 (Upgradable to Android 15)'
      },
      whyWeLikeIt: 'TUV Rheinland Low Blue Light certified 90Hz screen with 4 Dolby Atmos speakers.',
      bestFor: 'E-Book Reading, Kids Learning & Video Streaming',
      tradeOff: 'Helio G88 processor is tuned for efficiency, not heavy 3D gaming.',
      merchantName: 'Amazon',
      merchantLogoUrl: 'https://www.google.com/s2/favicons?domain=amazon.in&sz=64',
      dealUrl: 'https://www.amazon.in/s?k=Lenovo+Tab+M11&tag=axevora06-21',
      imageUrl: 'https://fdn2.gsmarena.com/vv/bigpic/lenovo-tab-m11.jpg',
      canonicalImage: 'https://fdn2.gsmarena.com/vv/bigpic/lenovo-tab-m11.jpg',
      imageSourceDomain: 'lenovo.com / gsmarena.com',
      imageConfidence: 1.0,
      dealType: 'PRODUCT_DEAL',
      verificationStatus: 'SOURCE_STATED'
    },
    {
      id: 'tab-redmi-se',
      canonicalProductId: 'xiaomi-redmi-pad-se-11-0-snapdragon-680-6gb-128gb',
      name: 'Xiaomi Redmi Pad SE (11.0 Inch 90Hz FHD+, Snapdragon 680, 6GB, 128GB)',
      brand: 'Xiaomi',
      model: 'Redmi Pad SE',
      variant: '6GB 128GB Mint Green',
      category: 'tablets',
      price: 13999,
      originalPrice: 19999,
      discountPercentage: 30,
      currency: 'INR',
      rating: 4.4,
      reviewCount: 5400,
      axevoraScore: 8.8,
      scoreLabel: 'Best Under ₹15,000',
      badge: 'Best Value',
      specs: {
        processor: 'Qualcomm Snapdragon 680 6nm',
        ram: '6GB LPDDR4X',
        storage: '128GB eMMC 5.1 (SD Card up to 1TB)',
        display: '11.0" 90Hz FHD+ Eye-Care Display (1920x1200)',
        battery: '8,000 mAh Massive Battery',
        camera: '8MP Rear + 5MP Front',
        os: 'Xiaomi HyperOS (Android 14)'
      },
      whyWeLikeIt: 'Huge 8,000 mAh battery with aluminum unibody construction under ₹14,000.',
      bestFor: 'Binge-Watching, Family Media & Casual Usage',
      tradeOff: '10W in-box charger takes longer to top up.',
      merchantName: 'Amazon',
      merchantLogoUrl: 'https://www.google.com/s2/favicons?domain=amazon.in&sz=64',
      dealUrl: 'https://www.amazon.in/s?k=Redmi+Pad+SE&tag=axevora06-21',
      imageUrl: 'https://fdn2.gsmarena.com/vv/bigpic/xiaomi-redmi-pad.jpg',
      canonicalImage: 'https://fdn2.gsmarena.com/vv/bigpic/xiaomi-redmi-pad.jpg',
      imageSourceDomain: 'mi.com / gsmarena.com',
      imageConfidence: 1.0,
      dealType: 'PRODUCT_DEAL',
      verificationStatus: 'SOURCE_STATED'
    },
    {
      id: 'tab-pad-go',
      canonicalProductId: 'oneplus-pad-go-11-35-2-4k-eye-care-8gb-128gb',
      name: 'OnePlus Pad Go (11.35 Inch 2.4K 90Hz, 8GB RAM, 128GB, Dolby Atmos)',
      brand: 'OnePlus',
      model: 'Pad Go',
      variant: '8GB 128GB Twin Mint',
      category: 'tablets',
      price: 19999,
      originalPrice: 24999,
      discountPercentage: 20,
      currency: 'INR',
      rating: 4.5,
      reviewCount: 4200,
      axevoraScore: 9.0,
      scoreLabel: 'Display & Audio Star',
      specs: {
        processor: 'MediaTek Helio G99 6nm',
        ram: '8GB LPDDR4X',
        storage: '128GB UFS 2.2',
        display: '11.35" 2.4K 7:5 ReadFit Display (2408x1720)',
        battery: '8,000 mAh + 33W SUPERVOOC Charging',
        camera: '8MP Rear + 8MP Front',
        os: 'OxygenOS 13.2 for Pad'
      },
      whyWeLikeIt: 'Unique 7:5 ReadFit aspect ratio perfect for reading books and browsing documents.',
      bestFor: 'Reading Enthusiasts, Media Consumption & Web Browsing',
      tradeOff: 'No official active stylus support; touch pens only.',
      merchantName: 'Amazon',
      merchantLogoUrl: 'https://www.google.com/s2/favicons?domain=amazon.in&sz=64',
      dealUrl: 'https://www.amazon.in/s?k=OnePlus+Pad+Go&tag=axevora06-21',
      imageUrl: 'https://fdn2.gsmarena.com/vv/bigpic/oneplus-pad-go.jpg',
      canonicalImage: 'https://fdn2.gsmarena.com/vv/bigpic/oneplus-pad-go.jpg',
      imageSourceDomain: 'oneplus.com / gsmarena.com',
      imageConfidence: 1.0,
      dealType: 'PRODUCT_DEAL',
      verificationStatus: 'SOURCE_STATED'
    },
    {
      id: 'tab-pad-x9',
      canonicalProductId: 'honor-pad-x9-11-5-120hz-2k-snapdragon-685-7-speakers',
      name: 'HONOR Pad X9 (11.5 Inch 120Hz 2K, Snapdragon 685, 6 Cinematic Speakers, 128GB)',
      brand: 'HONOR',
      model: 'Pad X9',
      variant: '4GB+3GB 128GB Space Gray',
      category: 'tablets',
      price: 14499,
      originalPrice: 25999,
      discountPercentage: 44,
      currency: 'INR',
      rating: 4.4,
      reviewCount: 3800,
      axevoraScore: 8.9,
      scoreLabel: 'Best Speaker Audio',
      specs: {
        processor: 'Qualcomm Snapdragon 685 6nm',
        ram: '4GB+3GB Turbo RAM',
        storage: '128GB High-Speed Storage',
        display: '11.5" 120Hz 2K FullView Display (2000x1200)',
        battery: '7,250 mAh High-Capacity Battery',
        camera: '5MP Rear + 5MP Front',
        os: 'MagicOS 7.1 (Android 13)'
      },
      whyWeLikeIt: 'Class-exclusive 6-speaker layout with Hi-Res spatial audio and smooth 120Hz 2K panel.',
      bestFor: 'Music, Movies & Virtual Meeting Calls',
      tradeOff: 'No 3.5mm audio jack included.',
      merchantName: 'Amazon',
      merchantLogoUrl: 'https://www.google.com/s2/favicons?domain=amazon.in&sz=64',
      dealUrl: 'https://www.amazon.in/s?k=HONOR+Pad+X9&tag=axevora06-21',
      imageUrl: 'https://fdn2.gsmarena.com/vv/bigpic/honor-pad-x9.jpg',
      canonicalImage: 'https://fdn2.gsmarena.com/vv/bigpic/honor-pad-x9.jpg',
      imageSourceDomain: 'hihonor.com / gsmarena.com',
      imageConfidence: 1.0,
      dealType: 'PRODUCT_DEAL',
      verificationStatus: 'SOURCE_STATED'
    },
    {
      id: 'tab-p12',
      canonicalProductId: 'lenovo-tab-p12-12-7-3k-display-dimensity-7050-8gb',
      name: 'Lenovo Tab P12 (12.7 Inch 3K Display, Dimensity 7050, 8GB RAM, 128GB)',
      brand: 'Lenovo',
      model: 'Tab P12',
      variant: '8GB 128GB Storm Grey',
      category: 'tablets',
      price: 24999,
      originalPrice: 34999,
      discountPercentage: 28,
      currency: 'INR',
      rating: 4.5,
      reviewCount: 1900,
      axevoraScore: 9.1,
      scoreLabel: 'Giant 3K Canvas',
      specs: {
        processor: 'MediaTek Dimensity 7050 (6nm)',
        ram: '8GB LPDDR4X',
        storage: '128GB UFS 2.2 (expandable)',
        display: '12.7" 3K LTPS Display (2944x1840)',
        battery: '10,200 mAh + 30W Fast Charge',
        camera: '13MP Rear + 8MP Front',
        os: 'Android 13 (Lenovo Freestyle Multi-Screen)'
      },
      whyWeLikeIt: 'Colossal 12.7-inch 3K display with quad JBL speakers and 10,200 mAh monster battery.',
      bestFor: 'Split-Screen Multi-Tasking, Video Editing & Spreadsheets',
      tradeOff: 'Larger 615g body requires two hands for long usage.',
      merchantName: 'Amazon',
      merchantLogoUrl: 'https://www.google.com/s2/favicons?domain=amazon.in&sz=64',
      dealUrl: 'https://www.amazon.in/s?k=Lenovo+Tab+P12&tag=axevora06-21',
      imageUrl: 'https://fdn2.gsmarena.com/vv/bigpic/lenovo-tab-p12.jpg',
      canonicalImage: 'https://fdn2.gsmarena.com/vv/bigpic/lenovo-tab-p12.jpg',
      imageSourceDomain: 'lenovo.com / gsmarena.com',
      imageConfidence: 1.0,
      dealType: 'PRODUCT_DEAL',
      verificationStatus: 'SOURCE_STATED'
    },
    {
      id: 'tab-ipad-air',
      canonicalProductId: 'apple-ipad-air-11-m2-128gb-space-gray',
      name: 'Apple iPad Air 11 Inch M2 (Liquid Retina, 128GB Storage, Wi-Fi 6E)',
      brand: 'Apple',
      model: 'iPad Air M2',
      variant: '128GB Space Gray',
      category: 'tablets',
      price: 58900,
      originalPrice: 59900,
      discountPercentage: 2,
      currency: 'INR',
      rating: 4.8,
      reviewCount: 1400,
      axevoraScore: 9.6,
      scoreLabel: 'Pro Powerhouse',
      badge: 'Best Performance',
      specs: {
        processor: 'Apple M2 Silicon (8-Core CPU, 9-Core GPU)',
        ram: '8GB Unified Memory',
        storage: '128GB High-Speed Storage',
        display: '11.0" Liquid Retina P3 Wide Color (2360x1640)',
        battery: 'Up to 10 Hours All-Day Battery',
        camera: '12MP Wide Rear + 12MP Landscape Ultra-Wide Front',
        os: 'iPadOS 17'
      },
      whyWeLikeIt: 'Desktop-grade M2 processor supports Final Cut Pro, Logic Pro, and Apple Pencil Pro.',
      bestFor: 'Pro Creators, 3D Artists, Video Editors & Developers',
      tradeOff: 'Premium price tag.',
      merchantName: 'Amazon',
      merchantLogoUrl: 'https://www.google.com/s2/favicons?domain=amazon.in&sz=64',
      dealUrl: 'https://www.amazon.in/s?k=iPad+Air+M2&tag=axevora06-21',
      imageUrl: 'https://fdn2.gsmarena.com/vv/bigpic/apple-ipad-air-11-2024.jpg',
      canonicalImage: 'https://fdn2.gsmarena.com/vv/bigpic/apple-ipad-air-11-2024.jpg',
      imageSourceDomain: 'apple.com / gsmarena.com',
      imageConfidence: 1.0,
      dealType: 'PRODUCT_DEAL',
      verificationStatus: 'SOURCE_STATED'
    }
  ],

  laptops: [
    {
      id: 'lap-mac-m2',
      canonicalProductId: 'apple-macbook-air-m2-13-6-8gb-256gb',
      name: 'Apple MacBook Air M2 (13.6 Inch Liquid Retina, 8GB RAM, 256GB SSD, Midnight)',
      brand: 'Apple',
      model: 'MacBook Air M2',
      variant: '8GB 256GB Midnight',
      category: 'laptops',
      price: 89990,
      originalPrice: 99900,
      discountPercentage: 10,
      currency: 'INR',
      rating: 4.8,
      reviewCount: 8400,
      axevoraScore: 9.6,
      scoreLabel: 'Class-Leading Ultraportable',
      badge: 'Best Overall',
      specs: {
        processor: 'Apple M2 Silicon (8-Core CPU, 8-Core GPU)',
        ram: '8GB Unified Memory',
        storage: '256GB High-Speed SSD',
        display: '13.6" 500 nits Liquid Retina Display',
        battery: 'Up to 18 Hours + MagSafe 3',
        camera: '1080p FaceTime HD Camera',
        gpu: 'Integrated 8-Core GPU',
        os: 'macOS Sonoma'
      },
      whyWeLikeIt: 'Modern slim unibody design, 1080p FaceTime HD camera, and dedicated MagSafe 3 charging port.',
      bestFor: 'Creators, Developers, Executives & Power Users',
      tradeOff: 'Base variant has 8GB non-upgradable unified memory.',
      merchantName: 'Amazon',
      merchantLogoUrl: 'https://www.google.com/s2/favicons?domain=amazon.in&sz=64',
      dealUrl: 'https://www.amazon.in/s?k=MacBook+Air+M2+256GB&tag=axevora06-21',
      imageUrl: 'https://m.media-amazon.com/images/I/71f5Eu5lJSL._SX679_.jpg',
      canonicalImage: 'https://m.media-amazon.com/images/I/71f5Eu5lJSL._SX679_.jpg',
      imageSourceDomain: 'apple.com / amazon.in',
      imageConfidence: 1.0,
      dealType: 'PRODUCT_DEAL',
      verificationStatus: 'SOURCE_STATED'
    },
    {
      id: 'lap-mac-m1',
      canonicalProductId: 'apple-macbook-air-m1-13-3-8gb-256gb',
      name: 'Apple MacBook Air M1 (13.3 Inch Retina, 8GB RAM, 256GB SSD, 18hr Battery)',
      brand: 'Apple',
      model: 'MacBook Air M1',
      variant: '8GB 256GB Space Gray',
      category: 'laptops',
      price: 64990,
      originalPrice: 92900,
      discountPercentage: 30,
      currency: 'INR',
      rating: 4.8,
      reviewCount: 14200,
      axevoraScore: 9.5,
      scoreLabel: 'Unbeatable Value',
      badge: 'Best Value',
      specs: {
        processor: 'Apple M1 Silicon (8-Core CPU, 7-Core GPU)',
        ram: '8GB Unified Memory',
        storage: '256GB High-Speed SSD',
        display: '13.3" 2560x1600 Retina P3 Display',
        battery: 'Up to 18 Hours All-Day Battery',
        camera: '720p FaceTime HD Camera',
        gpu: 'Integrated 7-Core GPU',
        os: 'macOS Sonoma'
      },
      whyWeLikeIt: 'Silent fanless design with class-leading 15-18 hour real battery life and aluminum unibody.',
      bestFor: 'Coding, Content Writing, College, Business & Travel',
      tradeOff: 'Older design with thick screen bezels and 720p webcam.',
      merchantName: 'Amazon',
      merchantLogoUrl: 'https://www.google.com/s2/favicons?domain=amazon.in&sz=64',
      dealUrl: 'https://www.amazon.in/s?k=MacBook+Air+M1&tag=axevora06-21',
      imageUrl: 'https://m.media-amazon.com/images/I/71jG+e7roXL._SX679_.jpg',
      canonicalImage: 'https://m.media-amazon.com/images/I/71jG+e7roXL._SX679_.jpg',
      imageSourceDomain: 'apple.com / amazon.in',
      imageConfidence: 1.0,
      dealType: 'PRODUCT_DEAL',
      verificationStatus: 'SOURCE_STATED'
    },
    {
      id: 'lap-lenovo-loq',
      canonicalProductId: 'lenovo-loq-15-i5-12450hx-rtx3050-16gb-512gb',
      name: 'Lenovo LOQ 15 (Core i5-12450HX, RTX 3050 6GB 95W TGP, 16GB, 512GB SSD, 144Hz FHD)',
      brand: 'Lenovo',
      model: 'LOQ 15',
      variant: '16GB DDR5 512GB SSD',
      category: 'laptops',
      price: 61990,
      originalPrice: 82990,
      discountPercentage: 25,
      currency: 'INR',
      rating: 4.4,
      reviewCount: 1800,
      axevoraScore: 9.3,
      scoreLabel: 'Top Gaming Performer',
      badge: 'Best Performance',
      specs: {
        processor: 'Intel Core i5-12450HX (8 Cores, 12 Threads)',
        ram: '16GB DDR5 4800MHz',
        storage: '512GB Gen4 SSD',
        display: '15.6" 144Hz FHD 100% sRGB IPS',
        battery: '60Wh Battery + Rapid Charge Pro',
        gpu: 'NVIDIA GeForce RTX 3050 6GB (95W Max TGP)',
        os: 'Windows 11 Home'
      },
      whyWeLikeIt: 'Full power 95W TGP RTX 3050 6GB GPU with 100% sRGB color-accurate display.',
      bestFor: 'Competitive 1080p Gaming, Premiere Pro & Blender 3D',
      tradeOff: 'Chunky 2.4kg weight and 170W power brick.',
      merchantName: 'Amazon',
      merchantLogoUrl: 'https://www.google.com/s2/favicons?domain=amazon.in&sz=64',
      dealUrl: 'https://www.amazon.in/s?k=Lenovo+LOQ+15+i5+RTX+3050&tag=axevora06-21',
      imageUrl: 'https://m.media-amazon.com/images/I/718zcLN4OsL._SX679_.jpg',
      canonicalImage: 'https://m.media-amazon.com/images/I/718zcLN4OsL._SX679_.jpg',
      imageSourceDomain: 'lenovo.com / amazon.in',
      imageConfidence: 1.0,
      dealType: 'PRODUCT_DEAL',
      verificationStatus: 'SOURCE_STATED'
    },
    {
      id: 'lap-asus-tuf',
      canonicalProductId: 'asus-tuf-gaming-a15-ryzen-7-7435hs-rtx3050',
      name: 'ASUS TUF Gaming A15 (Ryzen 7 7435HS, RTX 3050 4GB, 16GB, 512GB SSD, 144Hz)',
      brand: 'ASUS',
      model: 'TUF Gaming A15',
      variant: '16GB DDR5 512GB SSD Graphite Black',
      category: 'laptops',
      price: 59990,
      originalPrice: 77990,
      discountPercentage: 23,
      currency: 'INR',
      rating: 4.4,
      reviewCount: 3400,
      axevoraScore: 9.1,
      scoreLabel: 'Solid Gaming Rig',
      badge: 'Best Value',
      specs: {
        processor: 'AMD Ryzen 7 7435HS (8 Cores, 16 Threads)',
        ram: '16GB DDR5 4800MHz',
        storage: '512GB PCIe 4.0 NVMe SSD',
        display: '15.6" 144Hz FHD vIPS Display',
        battery: '48Wh + Fast Charging',
        gpu: 'NVIDIA GeForce RTX 3050 4GB (75W TGP)',
        os: 'Windows 11 Home'
      },
      whyWeLikeIt: 'MIL-STD-810H military-grade rugged durability with powerful 8-core Ryzen 7 CPU.',
      bestFor: 'Heavy Multitasking, Coding Workstations & AAA Gaming',
      tradeOff: 'No integrated iGPU on 7435HS means GPU is always active (modest battery life).',
      merchantName: 'Amazon',
      merchantLogoUrl: 'https://www.google.com/s2/favicons?domain=amazon.in&sz=64',
      dealUrl: 'https://www.amazon.in/s?k=ASUS+TUF+Gaming+A15+Ryzen+7&tag=axevora06-21',
      imageUrl: 'https://m.media-amazon.com/images/I/71fiRY278BL._SX679_.jpg',
      canonicalImage: 'https://m.media-amazon.com/images/I/71fiRY278BL._SX679_.jpg',
      imageSourceDomain: 'asus.com / amazon.in',
      imageConfidence: 1.0,
      dealType: 'PRODUCT_DEAL',
      verificationStatus: 'SOURCE_STATED'
    },
    {
      id: 'lap-acer-nitro',
      canonicalProductId: 'acer-nitro-v-15-i5-13420h-rtx3050-6gb',
      name: 'Acer Nitro V 15 (Core i5-13420H, RTX 3050 6GB, 16GB DDR5, 512GB Gen4 SSD, 144Hz)',
      brand: 'Acer',
      model: 'Nitro V 15',
      variant: '16GB DDR5 512GB SSD',
      category: 'laptops',
      price: 63990,
      originalPrice: 84999,
      discountPercentage: 25,
      currency: 'INR',
      rating: 4.3,
      reviewCount: 2200,
      axevoraScore: 9.0,
      scoreLabel: 'Great Hardware',
      badge: 'Editor Choice',
      specs: {
        processor: 'Intel Core i5-13420H (8 Cores, 12 Threads)',
        ram: '16GB DDR5 5200MHz',
        storage: '512GB Gen4 NVMe SSD',
        display: '15.6" 144Hz FHD IPS Panel',
        battery: '57Wh Battery',
        gpu: 'NVIDIA GeForce RTX 3050 6GB GDDR6 (75W TGP)',
        os: 'Windows 11 Home'
      },
      whyWeLikeIt: 'Dual-fan dual-exhaust cooling with dedicated 6GB VRAM for high-texture gaming.',
      bestFor: 'Gaming, Unreal Engine & AI Model Inference',
      tradeOff: 'Screen brightness peaks at 250 nits (indoor optimal).',
      merchantName: 'Amazon',
      merchantLogoUrl: 'https://www.google.com/s2/favicons?domain=amazon.in&sz=64',
      dealUrl: 'https://www.amazon.in/s?k=Acer+Nitro+V+15+i5+RTX+3050&tag=axevora06-21',
      imageUrl: 'https://m.media-amazon.com/images/I/81G1L3nptrL._SX679_.jpg',
      canonicalImage: 'https://m.media-amazon.com/images/I/81G1L3nptrL._SX679_.jpg',
      imageSourceDomain: 'acer.com / amazon.in',
      imageConfidence: 1.0,
      dealType: 'PRODUCT_DEAL',
      verificationStatus: 'SOURCE_STATED'
    },
    {
      id: 'lap-asus-vivo',
      canonicalProductId: 'asus-vivobook-15-intel-core-i5-1235u-16gb-512gb',
      name: 'ASUS Vivobook 15 (Core i5-1235U, 16GB RAM, 512GB SSD, FHD Thin & Light)',
      brand: 'ASUS',
      model: 'Vivobook 15',
      variant: '16GB 512GB Quiet Blue',
      category: 'laptops',
      price: 46990,
      originalPrice: 65990,
      discountPercentage: 29,
      currency: 'INR',
      rating: 4.4,
      reviewCount: 4600,
      axevoraScore: 8.9,
      scoreLabel: 'Best Everyday Workhorse',
      specs: {
        processor: 'Intel Core i5-1235U (10 Cores, 12 Threads)',
        ram: '16GB DDR4 3200MHz',
        storage: '512GB PCIe NVMe SSD',
        display: '15.6" FHD Anti-Glare Display (1920x1080)',
        battery: '42Wh Battery + Fast Charging (60% in 49m)',
        gpu: 'Intel Iris Xe Graphics',
        os: 'Windows 11 Home + MS Office 2021'
      },
      whyWeLikeIt: '180-degree lay-flat hinge, physical webcam privacy shutter, and 16GB dual-channel memory.',
      bestFor: 'Office Productivity, Accounting, Remote Work & College',
      tradeOff: 'Plastic keyboard deck with modest key travel.',
      merchantName: 'Amazon',
      merchantLogoUrl: 'https://www.google.com/s2/favicons?domain=amazon.in&sz=64',
      dealUrl: 'https://www.amazon.in/s?k=ASUS+Vivobook+15+i5&tag=axevora06-21',
      imageUrl: 'https://m.media-amazon.com/images/I/71lYhcc++AL._SX679_.jpg',
      canonicalImage: 'https://m.media-amazon.com/images/I/71lYhcc++AL._SX679_.jpg',
      imageSourceDomain: 'asus.com / amazon.in',
      imageConfidence: 1.0,
      dealType: 'PRODUCT_DEAL',
      verificationStatus: 'SOURCE_STATED'
    },
    {
      id: 'lap-hp-pav',
      canonicalProductId: 'hp-pavilion-14-intel-core-i5-1335u-16gb-512gb',
      name: 'HP Pavilion 14 (Core i5-1335U, 16GB DDR4, 512GB SSD, B&O Audio, FHD IPS)',
      brand: 'HP',
      model: 'Pavilion 14',
      variant: '16GB 512GB Natural Silver',
      category: 'laptops',
      price: 56990,
      originalPrice: 72990,
      discountPercentage: 22,
      currency: 'INR',
      rating: 4.4,
      reviewCount: 3100,
      axevoraScore: 9.0,
      scoreLabel: 'Premium Metal Ultrabook',
      specs: {
        processor: 'Intel Core i5-1335U 13th Gen (10 Cores)',
        ram: '16GB DDR4',
        storage: '512GB PCIe NVMe SSD',
        display: '14.0" FHD Micro-Edge IPS (1920x1080, 250 nits)',
        battery: '43Wh + HP Fast Charge',
        gpu: 'Intel Iris Xe Graphics',
        os: 'Windows 11 Home + MS Office Home 2021'
      },
      whyWeLikeIt: 'Sleek aluminum chassis with crystal-clear Bang & Olufsen tuned dual speakers.',
      bestFor: 'Business Executives, Writers & Travelling Professionals',
      tradeOff: '250 nits brightness is adequate indoors but weak in direct sunlight.',
      merchantName: 'Amazon',
      merchantLogoUrl: 'https://www.google.com/s2/favicons?domain=amazon.in&sz=64',
      dealUrl: 'https://www.amazon.in/s?k=HP+Pavilion+14+i5&tag=axevora06-21',
      imageUrl: 'https://m.media-amazon.com/images/I/71gD8WdSlaL._SX679_.jpg',
      canonicalImage: 'https://m.media-amazon.com/images/I/71gD8WdSlaL._SX679_.jpg',
      imageSourceDomain: 'hp.com / amazon.in',
      imageConfidence: 1.0,
      dealType: 'PRODUCT_DEAL',
      verificationStatus: 'SOURCE_STATED'
    },
    {
      id: 'lap-mac-pro-m3',
      canonicalProductId: 'apple-macbook-pro-14-m3-8gb-512gb-space-gray',
      name: 'Apple MacBook Pro 14 (M3 Chip, 120Hz Liquid Retina XDR, 8GB, 512GB)',
      brand: 'Apple',
      model: 'MacBook Pro M3',
      variant: '8GB 512GB Space Gray',
      category: 'laptops',
      price: 154990,
      originalPrice: 169900,
      discountPercentage: 9,
      currency: 'INR',
      rating: 4.8,
      reviewCount: 950,
      axevoraScore: 9.7,
      scoreLabel: 'Ultimate Studio Machine',
      badge: 'Best Performance',
      specs: {
        processor: 'Apple M3 Chip (8-Core CPU, 10-Core GPU)',
        ram: '8GB Unified Memory',
        storage: '512GB Pro-Speed SSD',
        display: '14.2" 120Hz Liquid Retina XDR (1600 nits peak)',
        battery: 'Up to 22 Hours Industry-Leading Battery',
        camera: '1080p FaceTime HD + 6-Speaker Sound System',
        gpu: 'Integrated 10-Core GPU with Hardware Ray Tracing',
        os: 'macOS Sonoma'
      },
      whyWeLikeIt: 'Mini-LED 120Hz ProMotion screen with 1600 nits HDR and unbelievable 22-hour battery life.',
      bestFor: 'Color Grading, Audio Production & Pro Software Development',
      tradeOff: 'Premium flagship price tag.',
      merchantName: 'Amazon',
      merchantLogoUrl: 'https://www.google.com/s2/favicons?domain=amazon.in&sz=64',
      dealUrl: 'https://www.amazon.in/s?k=MacBook+Pro+14+M3&tag=axevora06-21',
      imageUrl: 'https://m.media-amazon.com/images/I/61RJn0ofUsL._SX679_.jpg',
      canonicalImage: 'https://m.media-amazon.com/images/I/61RJn0ofUsL._SX679_.jpg',
      imageSourceDomain: 'apple.com / amazon.in',
      imageConfidence: 1.0,
      dealType: 'PRODUCT_DEAL',
      verificationStatus: 'SOURCE_STATED'
    },
    {
      id: 'lap-acer-aspire',
      canonicalProductId: 'acer-aspire-5-intel-core-i5-1335u-16gb-512gb',
      name: 'Acer Aspire 5 (Core i5-1335U, 16GB RAM, 512GB SSD, 15.6" FHD IPS, Wi-Fi 6E)',
      brand: 'Acer',
      model: 'Aspire 5',
      variant: '16GB 512GB Steel Gray',
      category: 'laptops',
      price: 49990,
      originalPrice: 68990,
      discountPercentage: 28,
      currency: 'INR',
      rating: 4.3,
      reviewCount: 1800,
      axevoraScore: 8.8,
      scoreLabel: 'Clean Productivity Rig',
      specs: {
        processor: 'Intel Core i5-1335U (10 Cores, 12 Threads)',
        ram: '16GB LPDDR5',
        storage: '512GB PCIe Gen4 NVMe SSD',
        display: '15.6" Full HD IPS Acer ComfyView (1920x1080)',
        battery: '50Wh Battery + 65W AC Adapter',
        gpu: 'Intel Iris Xe Graphics',
        os: 'Windows 11 Home'
      },
      whyWeLikeIt: 'Upgraded LPDDR5 RAM with fast Gen4 SSD and aluminum top cover under ₹50,000.',
      bestFor: 'College, Data Analysis & Everyday Office Work',
      tradeOff: 'Webcam is standard 720p resolution.',
      merchantName: 'Amazon',
      merchantLogoUrl: 'https://www.google.com/s2/favicons?domain=amazon.in&sz=64',
      dealUrl: 'https://www.amazon.in/s?k=Acer+Aspire+5+i5&tag=axevora06-21',
      imageUrl: 'https://m.media-amazon.com/images/I/71czGb00k5L._SX679_.jpg',
      canonicalImage: 'https://m.media-amazon.com/images/I/71czGb00k5L._SX679_.jpg',
      imageSourceDomain: 'acer.com / amazon.in',
      imageConfidence: 1.0,
      dealType: 'PRODUCT_DEAL',
      verificationStatus: 'SOURCE_STATED'
    },
    {
      id: 'lap-dell-15',
      canonicalProductId: 'dell-15-intel-core-i3-1215u-8gb-512gb-ssd',
      name: 'Dell 15 Thin & Light (Core i3-1215U, 8GB RAM, 512GB SSD, 15.6" FHD 120Hz)',
      brand: 'Dell',
      model: 'Dell 15 Thin & Light',
      variant: '8GB 512GB Carbon Black',
      category: 'laptops',
      price: 36990,
      originalPrice: 48990,
      discountPercentage: 25,
      currency: 'INR',
      rating: 4.2,
      reviewCount: 3900,
      axevoraScore: 8.6,
      scoreLabel: 'Budget 120Hz Laptop',
      specs: {
        processor: 'Intel Core i3-1215U 12th Gen (6 Cores, 8 Threads)',
        ram: '8GB DDR4 2666MHz (Expandable to 16GB)',
        storage: '512GB M.2 PCIe NVMe SSD',
        display: '15.6" FHD 120Hz 250 nits WVA Display (1920x1080)',
        battery: '41Wh Battery + ExpressCharge (80% in 60m)',
        gpu: 'Intel UHD Graphics',
        os: 'Windows 11 Home + MS Office Home 2021'
      },
      whyWeLikeIt: 'Smooth 120Hz refresh rate panel with lift-hinge ergonomics and Dell ExpressCharge.',
      bestFor: 'Budget Buyers, School Work, Accounting & Daily Browsing',
      tradeOff: 'Integrated UHD graphics is basic for gaming.',
      merchantName: 'Amazon',
      merchantLogoUrl: 'https://www.google.com/s2/favicons?domain=amazon.in&sz=64',
      dealUrl: 'https://www.amazon.in/s?k=Dell+15+Laptop+i3&tag=axevora06-21',
      imageUrl: 'https://m.media-amazon.com/images/I/510uTHyDqGL._SX679_.jpg',
      canonicalImage: 'https://m.media-amazon.com/images/I/510uTHyDqGL._SX679_.jpg',
      imageSourceDomain: 'dell.com / amazon.in',
      imageConfidence: 1.0,
      dealType: 'PRODUCT_DEAL',
      verificationStatus: 'SOURCE_STATED'
    }
  ],

  phones: [
    {
      id: 'ph-iphone-15',
      canonicalProductId: 'apple-iphone-15-128gb-black',
      name: 'Apple iPhone 15 (128GB, Dynamic Island, 48MP Main Camera, USB-C)',
      brand: 'Apple',
      model: 'iPhone 15',
      variant: '128GB Black',
      category: 'phones',
      price: 69999,
      originalPrice: 79900,
      discountPercentage: 12,
      currency: 'INR',
      rating: 4.7,
      reviewCount: 9800,
      axevoraScore: 9.6,
      scoreLabel: 'Flagship Gold Standard',
      badge: 'Best Overall',
      specs: {
        processor: 'Apple A16 Bionic 4nm',
        ram: '6GB RAM',
        storage: '128GB Storage',
        display: '6.1" Super Retina XDR OLED (2000 nits)',
        battery: '3349 mAh + 20W Fast Charge',
        camera: '48MP Main (Sensor-Shift OIS) + 12MP Ultra-wide',
        os: 'iOS 17'
      },
      whyWeLikeIt: 'Industry-leading video capture, versatile Dynamic Island, and universal USB-C charging.',
      bestFor: 'Content Creators, Photographers & Long-Term Reliability',
      tradeOff: 'Standard 60Hz display refresh rate on base model.',
      merchantName: 'Amazon',
      merchantLogoUrl: 'https://www.google.com/s2/favicons?domain=amazon.in&sz=64',
      dealUrl: 'https://www.amazon.in/s?k=iPhone+15+128GB&tag=axevora06-21',
      imageUrl: 'https://fdn2.gsmarena.com/vv/bigpic/apple-iphone-15.jpg',
      canonicalImage: 'https://fdn2.gsmarena.com/vv/bigpic/apple-iphone-15.jpg',
      imageSourceDomain: 'apple.com / gsmarena.com',
      imageConfidence: 1.0,
      dealType: 'PRODUCT_DEAL',
      verificationStatus: 'SOURCE_STATED'
    },
    {
      id: 'ph-galaxy-s24',
      canonicalProductId: 'samsung-galaxy-s24-5g-8gb-128gb-onyx-black',
      name: 'Samsung Galaxy S24 5G (8GB RAM, 128GB Storage, Galaxy AI, 120Hz Dynamic AMOLED 2X)',
      brand: 'Samsung',
      model: 'Galaxy S24',
      variant: '8GB 128GB Onyx Black',
      category: 'phones',
      price: 64999,
      originalPrice: 79999,
      discountPercentage: 19,
      currency: 'INR',
      rating: 4.6,
      reviewCount: 3200,
      axevoraScore: 9.4,
      scoreLabel: 'Compact Flagship',
      badge: 'Best Performance',
      specs: {
        processor: 'Exynos 2400 Deca-Core 4nm',
        ram: '8GB LPDDR5X',
        storage: '128GB UFS 4.0',
        display: '6.2" 1-120Hz LTPO Dynamic AMOLED 2X (2600 nits)',
        battery: '4000 mAh + 25W Fast Charge',
        camera: '50MP OIS + 10MP 3x Telephoto + 12MP Ultra-wide',
        os: 'Android 14 (One UI 6.1 with 7 Years OS Updates)'
      },
      whyWeLikeIt: 'Class-leading compact form factor, 7 full years of Android OS upgrades, and true 3x telephoto optical zoom.',
      bestFor: 'Compact Flagship Lovers, Photography & AI Productivity',
      tradeOff: '25W charging speed is modest compared to Chinese flagships.',
      merchantName: 'Amazon',
      merchantLogoUrl: 'https://www.google.com/s2/favicons?domain=amazon.in&sz=64',
      dealUrl: 'https://www.amazon.in/s?k=Samsung+Galaxy+S24+5G&tag=axevora06-21',
      imageUrl: 'https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-s24-5g-sm-s921.jpg',
      canonicalImage: 'https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-s24-5g-sm-s921.jpg',
      imageSourceDomain: 'samsung.com / gsmarena.com',
      imageConfidence: 1.0,
      dealType: 'PRODUCT_DEAL',
      verificationStatus: 'SOURCE_STATED'
    },
    {
      id: 'ph-oneplus-12r',
      canonicalProductId: 'oneplus-12r-5g-8gb-128gb-cool-blue',
      name: 'OnePlus 12R 5G (Snapdragon 8 Gen 2, 8GB RAM, 128GB, 100W SUPERVOOC, 5500mAh)',
      brand: 'OnePlus',
      model: '12R 5G',
      variant: '8GB 128GB Cool Blue',
      category: 'phones',
      price: 39999,
      originalPrice: 42999,
      discountPercentage: 7,
      currency: 'INR',
      rating: 4.6,
      reviewCount: 5400,
      axevoraScore: 9.3,
      scoreLabel: 'Flagship Killer',
      badge: 'Best Value',
      specs: {
        processor: 'Snapdragon 8 Gen 2 4nm',
        ram: '8GB LPDDR5X',
        storage: '128GB UFS 3.1',
        display: '6.78" 1.5K 1-120Hz LTPO 4.0 AMOLED (4500 nits)',
        battery: '5500 mAh + 100W SUPERVOOC',
        camera: '50MP Sony IMX890 OIS + 8MP + 2MP',
        os: 'OxygenOS 14'
      },
      whyWeLikeIt: 'Flagship Snapdragon 8 Gen 2 chip with massive 5500mAh battery and blazing 100W charger included.',
      bestFor: 'Gamers, Heavy Power Users & Fast Charging Enthusiasts',
      tradeOff: 'Secondary ultra-wide and macro cameras are basic.',
      merchantName: 'Amazon',
      merchantLogoUrl: 'https://www.google.com/s2/favicons?domain=amazon.in&sz=64',
      dealUrl: 'https://www.amazon.in/s?k=OnePlus+12R+5G&tag=axevora06-21',
      imageUrl: 'https://fdn2.gsmarena.com/vv/bigpic/oneplus-12r.jpg',
      canonicalImage: 'https://fdn2.gsmarena.com/vv/bigpic/oneplus-12r.jpg',
      imageSourceDomain: 'oneplus.com / gsmarena.com',
      imageConfidence: 1.0,
      dealType: 'PRODUCT_DEAL',
      verificationStatus: 'SOURCE_STATED'
    },
    {
      id: 'ph-poco-x6-pro',
      canonicalProductId: 'xiaomi-poco-x6-pro-5g-dimensity-8300-8gb-256gb',
      name: 'Poco X6 Pro 5G (Dimensity 8300-Ultra, 120Hz 1.5K AMOLED, 64MP OIS, 8GB, 256GB)',
      brand: 'Xiaomi',
      model: 'Poco X6 Pro',
      variant: '8GB 256GB Racing Yellow',
      category: 'phones',
      price: 24999,
      originalPrice: 30999,
      discountPercentage: 19,
      currency: 'INR',
      rating: 4.5,
      reviewCount: 7800,
      axevoraScore: 9.2,
      scoreLabel: 'Gaming Performance King',
      badge: 'Best Performance',
      specs: {
        processor: 'MediaTek Dimensity 8300-Ultra (4nm, AnTuTu 1.4M+)',
        ram: '8GB LPDDR5X',
        storage: '256GB UFS 4.0',
        display: '6.67" 1.5K 120Hz Flow AMOLED (1800 nits)',
        battery: '5000 mAh + 67W Turbo Charge',
        camera: '64MP OIS + 8MP Ultra-wide + 2MP',
        os: 'Xiaomi HyperOS (Android 14)'
      },
      whyWeLikeIt: 'Unmatched raw gaming horsepower with UFS 4.0 storage and 1.5K AMOLED under ₹25,000.',
      bestFor: 'Competitive BGMI, Genshin Impact & High-Framerate Gaming',
      tradeOff: 'Plastic side frame construction.',
      merchantName: 'Amazon',
      merchantLogoUrl: 'https://www.google.com/s2/favicons?domain=amazon.in&sz=64',
      dealUrl: 'https://www.amazon.in/s?k=Poco+X6+Pro+5G&tag=axevora06-21',
      imageUrl: 'https://fdn2.gsmarena.com/vv/bigpic/xiaomi-poco-x6-pro.jpg',
      canonicalImage: 'https://fdn2.gsmarena.com/vv/bigpic/xiaomi-poco-x6-pro.jpg',
      imageSourceDomain: 'poco.in / gsmarena.com',
      imageConfidence: 1.0,
      dealType: 'PRODUCT_DEAL',
      verificationStatus: 'SOURCE_STATED'
    },
    {
      id: 'ph-moto-g85',
      canonicalProductId: 'motorola-moto-g85-5g-3d-curved-p-oled-8gb-128gb',
      name: 'Motorola Moto G85 5G (3D Curved 120Hz p-OLED, 50MP Sony LYT-600 OIS, 8GB, 128GB)',
      brand: 'Motorola',
      model: 'Moto G85 5G',
      variant: '8GB 128GB Cobalt Blue Vegan Leather',
      category: 'phones',
      price: 17999,
      originalPrice: 20999,
      discountPercentage: 14,
      currency: 'INR',
      rating: 4.4,
      reviewCount: 4100,
      axevoraScore: 9.0,
      scoreLabel: 'Curved Display Design Star',
      badge: 'Best Value',
      specs: {
        processor: 'Snapdragon 6s Gen 3 (6nm)',
        ram: '8GB RAM',
        storage: '128GB UFS 2.2',
        display: '6.67" 3D Curved 120Hz p-OLED (1600 nits, Gorilla Glass 5)',
        battery: '5000 mAh + 33W TurboPower',
        camera: '50MP Sony LYT-600 OIS + 8MP Ultra-wide/Macro',
        os: 'Clean Hello UI (Android 14, No Ads)'
      },
      whyWeLikeIt: 'Gorgeous 3D curved 120Hz OLED screen with clean, ad-free Motorola software.',
      bestFor: 'Clean Android Experience, Premium Aesthetics & Photography',
      tradeOff: '33W charging is moderate.',
      merchantName: 'Amazon',
      merchantLogoUrl: 'https://www.google.com/s2/favicons?domain=amazon.in&sz=64',
      dealUrl: 'https://www.amazon.in/s?k=Moto+G85+5G&tag=axevora06-21',
      imageUrl: 'https://fdn2.gsmarena.com/vv/bigpic/motorola-moto-g85.jpg',
      canonicalImage: 'https://fdn2.gsmarena.com/vv/bigpic/motorola-moto-g85.jpg',
      imageSourceDomain: 'motorola.in / gsmarena.com',
      imageConfidence: 1.0,
      dealType: 'PRODUCT_DEAL',
      verificationStatus: 'SOURCE_STATED'
    },
    {
      id: 'ph-realme-12-plus',
      canonicalProductId: 'realme-12-plus-5g-sony-lyt-600-ois-8gb-128gb',
      name: 'Realme 12+ 5G (Sony LYT-600 OIS, 120Hz AMOLED, Dimensity 7050, 8GB, 128GB)',
      brand: 'Realme',
      model: '12+ 5G',
      variant: '8GB 128GB Pioneer Green',
      category: 'phones',
      price: 18999,
      originalPrice: 23999,
      discountPercentage: 21,
      currency: 'INR',
      rating: 4.4,
      reviewCount: 3600,
      axevoraScore: 8.9,
      scoreLabel: 'Luxury Watch Dial Design',
      specs: {
        processor: 'MediaTek Dimensity 7050 5G (6nm)',
        ram: '8GB RAM',
        storage: '128GB Storage',
        display: '6.67" 120Hz AMOLED Rainwater Smart Touch (2000 nits)',
        battery: '5000 mAh + 67W SUPERVOOC Charge',
        camera: '50MP Sony LYT-600 OIS + 8MP Ultra-wide + 2MP Macro',
        os: 'realme UI 5.0 (Android 14)'
      },
      whyWeLikeIt: 'Luxury vegan leather back with dedicated 50MP Sony LYT-600 OIS sensor.',
      bestFor: 'Portrait Photography, Fast Charging & Stylish Looks',
      tradeOff: 'Pre-installed promotional apps in UI.',
      merchantName: 'Amazon',
      merchantLogoUrl: 'https://www.google.com/s2/favicons?domain=amazon.in&sz=64',
      dealUrl: 'https://www.amazon.in/s?k=Realme+12+Plus+5G&tag=axevora06-21',
      imageUrl: 'https://fdn2.gsmarena.com/vv/bigpic/realme-12-plus.jpg',
      canonicalImage: 'https://fdn2.gsmarena.com/vv/bigpic/realme-12-plus.jpg',
      imageSourceDomain: 'realme.com / gsmarena.com',
      imageConfidence: 1.0,
      dealType: 'PRODUCT_DEAL',
      verificationStatus: 'SOURCE_STATED'
    },
    {
      id: 'ph-nothing-2a',
      canonicalProductId: 'nothing-phone-2a-5g-glyph-interface-8gb-128gb',
      name: 'Nothing Phone (2a) (Iconic Glyph Interface, 50MP Dual Camera, 8GB, 128GB)',
      brand: 'Nothing',
      model: 'Phone (2a)',
      variant: '8GB 128GB Milk White',
      category: 'phones',
      price: 23999,
      originalPrice: 25999,
      discountPercentage: 8,
      currency: 'INR',
      rating: 4.5,
      reviewCount: 8200,
      axevoraScore: 9.3,
      scoreLabel: 'Design & Software Masterpiece',
      badge: 'Editor Choice',
      specs: {
        processor: 'Dimensity 7200 Pro Custom 4nm',
        ram: '8GB RAM',
        storage: '128GB Storage',
        display: '6.7" 120Hz Flexible AMOLED (1300 nits, HDR10+)',
        battery: '5000 mAh + 45W Fast Charging',
        camera: '50MP Main OIS + 50MP Ultra-wide Dual Camera',
        os: 'Nothing OS 2.5 (Clean, Bloat-Free Android 14)'
      },
      whyWeLikeIt: 'Signature transparent design with functional Glyph lighting and zero bloatware Nothing OS.',
      bestFor: 'Design Lovers, Enthusiasts & Pure Android Seekers',
      tradeOff: 'Charging brick not included in box.',
      merchantName: 'Amazon',
      merchantLogoUrl: 'https://www.google.com/s2/favicons?domain=amazon.in&sz=64',
      dealUrl: 'https://www.amazon.in/s?k=Nothing+Phone+2a&tag=axevora06-21',
      imageUrl: 'https://fdn2.gsmarena.com/vv/bigpic/nothing-phone-2a.jpg',
      canonicalImage: 'https://fdn2.gsmarena.com/vv/bigpic/nothing-phone-2a.jpg',
      imageSourceDomain: 'nothing.tech / gsmarena.com',
      imageConfidence: 1.0,
      dealType: 'PRODUCT_DEAL',
      verificationStatus: 'SOURCE_STATED'
    },
    {
      id: 'ph-iqoo-z9s',
      canonicalProductId: 'vivo-iqoo-z9s-5g-3d-curved-120hz-dimensity-7300',
      name: 'iQOO Z9s 5G (3D Curved 120Hz AMOLED, Dimensity 7300, 50MP Sony OIS, 8GB, 128GB)',
      brand: 'Vivo',
      model: 'iQOO Z9s 5G',
      variant: '8GB 128GB Titanium Matte',
      category: 'phones',
      price: 19999,
      originalPrice: 25999,
      discountPercentage: 23,
      currency: 'INR',
      rating: 4.5,
      reviewCount: 3100,
      axevoraScore: 9.1,
      scoreLabel: 'Curved Performance Monster',
      specs: {
        processor: 'MediaTek Dimensity 7300 4nm Energy-Efficient',
        ram: '8GB LPDDR4X',
        storage: '128GB UFS 2.2',
        display: '6.77" 3D Curved 120Hz AMOLED (1800 nits Local Peak)',
        battery: '5500 mAh Ultra-Thin Battery + 44W FlashCharge',
        camera: '50MP Sony IMX882 OIS + 2MP Bokeh',
        os: 'Funtouch OS 14 (Android 14)'
      },
      whyWeLikeIt: 'Slim 7.49mm curved body packing a massive 5500 mAh battery and Dimensity 7300 chip.',
      bestFor: 'Gaming Endurance, Long Battery Life & Sleek Form Factor',
      tradeOff: 'No ultra-wide secondary camera.',
      merchantName: 'Amazon',
      merchantLogoUrl: 'https://www.google.com/s2/favicons?domain=amazon.in&sz=64',
      dealUrl: 'https://www.amazon.in/s?k=iQOO+Z9s+5G&tag=axevora06-21',
      imageUrl: 'https://fdn2.gsmarena.com/vv/bigpic/vivo-iqoo-z9s.jpg',
      canonicalImage: 'https://fdn2.gsmarena.com/vv/bigpic/vivo-iqoo-z9s.jpg',
      imageSourceDomain: 'iqoo.com / gsmarena.com',
      imageConfidence: 1.0,
      dealType: 'PRODUCT_DEAL',
      verificationStatus: 'SOURCE_STATED'
    },
    {
      id: 'ph-redmi-13c',
      canonicalProductId: 'xiaomi-redmi-13c-5g-dimensity-6100-plus-4gb-128gb',
      name: 'Redmi 13C 5G (Dimensity 6100+, 90Hz Display, 50MP AI Camera, 4GB, 128GB)',
      brand: 'Xiaomi',
      model: 'Redmi 13C 5G',
      variant: '4GB 128GB Starlight Black',
      category: 'phones',
      price: 10499,
      originalPrice: 13999,
      discountPercentage: 25,
      currency: 'INR',
      rating: 4.2,
      reviewCount: 16500,
      axevoraScore: 8.6,
      scoreLabel: 'Best Budget 5G Phone',
      badge: 'Best Value',
      specs: {
        processor: 'MediaTek Dimensity 6100+ 5G (6nm)',
        ram: '4GB RAM',
        storage: '128GB Storage (microSD expandable)',
        display: '6.74" 90Hz HD+ Dot Drop Display (Gorilla Glass)',
        battery: '5000 mAh Battery + 18W Fast Charging',
        camera: '50MP AI Primary + 5MP Front',
        os: 'MIUI 14 (Android 13)'
      },
      whyWeLikeIt: 'Most reliable and affordable 5G entry phone with expandable storage and dual SIM 5G.',
      bestFor: 'First-time 5G Smartphone Buyers, Parents & Budget Users',
      tradeOff: 'HD+ screen resolution instead of Full HD.',
      merchantName: 'Amazon',
      merchantLogoUrl: 'https://www.google.com/s2/favicons?domain=amazon.in&sz=64',
      dealUrl: 'https://www.amazon.in/s?k=Redmi+13C+5G&tag=axevora06-21',
      imageUrl: 'https://fdn2.gsmarena.com/vv/bigpic/xiaomi-redmi-13c-5g.jpg',
      canonicalImage: 'https://fdn2.gsmarena.com/vv/bigpic/xiaomi-redmi-13c-5g.jpg',
      imageSourceDomain: 'mi.com / gsmarena.com',
      imageConfidence: 1.0,
      dealType: 'PRODUCT_DEAL',
      verificationStatus: 'SOURCE_STATED'
    },
    {
      id: 'ph-pixel-8a',
      canonicalProductId: 'google-pixel-8a-5g-tensor-g3-ai-camera-128gb',
      name: 'Google Pixel 8a 5G (Google Tensor G3, 120Hz OLED, 64MP Best Take, 128GB)',
      brand: 'Google',
      model: 'Pixel 8a',
      variant: '8GB 128GB Bay Blue',
      category: 'phones',
      price: 49999,
      originalPrice: 52999,
      discountPercentage: 6,
      currency: 'INR',
      rating: 4.6,
      reviewCount: 1900,
      axevoraScore: 9.5,
      scoreLabel: 'AI Camera Benchmark',
      badge: 'Editor Choice',
      specs: {
        processor: 'Google Tensor G3 with Titan M2 Security',
        ram: '8GB LPDDR5X',
        storage: '128GB UFS 3.1',
        display: '6.1" 120Hz Actua OLED Display (2000 nits peak)',
        battery: '4492 mAh + 18W Fast Charging + Wireless Charge',
        camera: '64MP OIS + 13MP Ultra-wide (Best Take, Magic Eraser)',
        os: 'Pure Android 14 with 7 Years OS & Feature Drops'
      },
      whyWeLikeIt: 'Industry-leading still photography, 7 full years of OS updates, and IP67 water resistance.',
      bestFor: 'Mobile Photographers, Stock Android Lovers & AI Features',
      tradeOff: 'Charging speed is relatively slow at 18W.',
      merchantName: 'Amazon',
      merchantLogoUrl: 'https://www.google.com/s2/favicons?domain=amazon.in&sz=64',
      dealUrl: 'https://www.amazon.in/s?k=Google+Pixel+8a&tag=axevora06-21',
      imageUrl: 'https://fdn2.gsmarena.com/vv/bigpic/google-pixel-8a.jpg',
      canonicalImage: 'https://fdn2.gsmarena.com/vv/bigpic/google-pixel-8a.jpg',
      imageSourceDomain: 'google.com / gsmarena.com',
      imageConfidence: 1.0,
      dealType: 'PRODUCT_DEAL',
      verificationStatus: 'SOURCE_STATED'
    }
  ],

  tvs: [
    {
      id: 'tv-sony-55-x74l',
      canonicalProductId: 'sony-bravia-55-inch-4k-ultra-hd-kd-55x74l',
      name: 'Sony Bravia 55 Inch 4K Ultra HD Smart LED Google TV (KD-55X74L, X1 4K HDR Processor)',
      brand: 'Sony',
      model: 'Bravia KD-55X74L',
      variant: '55 Inch 4K Black',
      category: 'tvs',
      price: 54990,
      originalPrice: 99900,
      discountPercentage: 45,
      currency: 'INR',
      rating: 4.7,
      reviewCount: 4200,
      axevoraScore: 9.4,
      scoreLabel: 'Cinematic Picture Quality',
      badge: 'Best Overall',
      specs: {
        processor: 'Sony X1 4K Processor',
        display: '55" 4K Ultra HD (3840x2160) Motionflow XR',
        os: 'Google TV with Voice Assistant'
      },
      whyWeLikeIt: 'Industry benchmark color reproduction and upscaling powered by Sony X1 processor with open acoustic sound.',
      bestFor: 'Home Theaters, Netflix 4K HDR & PS5 Gaming',
      tradeOff: 'Standard 60Hz panel refresh rate.',
      merchantName: 'Amazon',
      merchantLogoUrl: 'https://www.google.com/s2/favicons?domain=amazon.in&sz=64',
      dealUrl: 'https://www.amazon.in/s?k=Sony+Bravia+55+inch+4K+X74L&tag=axevora06-21',
      imageUrl: 'https://m.media-amazon.com/images/I/81IdR5bYsrL._SX679_.jpg',
      canonicalImage: 'https://m.media-amazon.com/images/I/81IdR5bYsrL._SX679_.jpg',
      imageSourceDomain: 'sony.com / amazon.in',
      imageConfidence: 1.0,
      dealType: 'PRODUCT_DEAL',
      verificationStatus: 'SOURCE_STATED'
    },
    {
      id: 'tv-samsung-55-q60d',
      canonicalProductId: 'samsung-55-inch-qled-4k-qa55q60dakxxl',
      name: 'Samsung 55 Inch QLED 4K Ultra HD Smart TV (QA55Q60DAKXXL, Quantum HDR, AirSlim)',
      brand: 'Samsung',
      model: 'Q60D QLED 55',
      variant: '55 Inch 4K Titan Gray',
      category: 'tvs',
      price: 61990,
      originalPrice: 89900,
      discountPercentage: 31,
      currency: 'INR',
      rating: 4.6,
      reviewCount: 2800,
      axevoraScore: 9.4,
      scoreLabel: 'Vibrant Quantum Color',
      badge: 'Best Performance',
      specs: {
        processor: 'Quantum Processor Lite 4K',
        display: '55" 4K QLED 100% Color Volume with Quantum Dot',
        os: 'Samsung Tizen OS with Knox Security'
      },
      whyWeLikeIt: '100% Color Volume with Quantum Dot technology in an ultra-sleek 26mm AirSlim design.',
      bestFor: 'Bright Living Rooms, HDR Movies & Smart Home Hub',
      tradeOff: 'Edge-lit LED backlight rather than full-array local dimming.',
      merchantName: 'Amazon',
      merchantLogoUrl: 'https://www.google.com/s2/favicons?domain=amazon.in&sz=64',
      dealUrl: 'https://www.amazon.in/s?k=Samsung+55+inch+QLED+Q60D&tag=axevora06-21',
      imageUrl: 'https://m.media-amazon.com/images/I/91suuz30qEL._SX679_.jpg',
      canonicalImage: 'https://m.media-amazon.com/images/I/91suuz30qEL._SX679_.jpg',
      imageSourceDomain: 'samsung.com / amazon.in',
      imageConfidence: 1.0,
      dealType: 'PRODUCT_DEAL',
      verificationStatus: 'SOURCE_STATED'
    },
    {
      id: 'tv-oneplus-43-y1s',
      canonicalProductId: 'oneplus-43-inch-y-series-4k-ultra-hd-smart-tv',
      name: 'OnePlus TV 43 Inch Y1S Pro 4K Ultra HD Smart Android TV (Gamma Engine, Dolby Audio)',
      brand: 'OnePlus',
      model: 'TV 43 Y1S Pro',
      variant: '43 Inch 4K Black',
      category: 'tvs',
      price: 24999,
      originalPrice: 39999,
      discountPercentage: 38,
      currency: 'INR',
      rating: 4.3,
      reviewCount: 8900,
      axevoraScore: 8.9,
      scoreLabel: 'Best Budget 4K TV',
      badge: 'Best Value',
      specs: {
        processor: 'Gamma Engine with MEMC',
        display: '43" 4K Ultra HD (3840x2160) 10-bit Color',
        os: 'Android TV 10 with OxygenPlay 2.0'
      },
      whyWeLikeIt: 'Bezel-less design with HDR10+ decoding and OnePlus ecosystem connectivity.',
      bestFor: 'Bedrooms, Living Rooms & Casual Streaming',
      tradeOff: 'Standard 24W audio output; best paired with a soundbar.',
      merchantName: 'Amazon',
      merchantLogoUrl: 'https://www.google.com/s2/favicons?domain=amazon.in&sz=64',
      dealUrl: 'https://www.amazon.in/s?k=OnePlus+43+inch+4K+TV&tag=axevora06-21',
      imageUrl: 'https://m.media-amazon.com/images/I/71d5fMDvq9L._SX679_.jpg',
      canonicalImage: 'https://m.media-amazon.com/images/I/71d5fMDvq9L._SX679_.jpg',
      imageSourceDomain: 'oneplus.in / amazon.in',
      imageConfidence: 1.0,
      dealType: 'PRODUCT_DEAL',
      verificationStatus: 'SOURCE_STATED'
    },
    {
      id: 'tv-panasonic-55-4k',
      canonicalProductId: 'panasonic-55-inch-4k-ultra-hd-smart-led-google-tv',
      name: 'Panasonic 55 Inch 4K Ultra HD Smart LED Google TV (4K Colour Engine, Dolby Digital)',
      brand: 'Panasonic',
      model: '55 4K Google TV',
      variant: '55 Inch 4K Dark Gray',
      category: 'tvs',
      price: 39990,
      originalPrice: 63990,
      discountPercentage: 37,
      currency: 'INR',
      rating: 4.4,
      reviewCount: 2100,
      axevoraScore: 9.0,
      scoreLabel: 'Japanese Color Fidelity',
      specs: {
        processor: '4K Studio Colour Engine',
        display: '55" 4K Ultra HD HDR10 Panel',
        os: 'Google TV with Built-in Chromecast'
      },
      whyWeLikeIt: 'Natural color tuning with wide viewing angles and clean Google TV interface.',
      bestFor: 'Family Movie Nights, Sports & Daily Broadcasts',
      tradeOff: '60Hz panel refresh rate.',
      merchantName: 'Amazon',
      merchantLogoUrl: 'https://www.google.com/s2/favicons?domain=amazon.in&sz=64',
      dealUrl: 'https://www.amazon.in/s?k=Panasonic+55+inch+4K+TV&tag=axevora06-21',
      imageUrl: 'https://m.media-amazon.com/images/I/71vFKBpKakL._SX679_.jpg',
      canonicalImage: 'https://m.media-amazon.com/images/I/71vFKBpKakL._SX679_.jpg',
      imageSourceDomain: 'panasonic.com / amazon.in',
      imageConfidence: 1.0,
      dealType: 'PRODUCT_DEAL',
      verificationStatus: 'SOURCE_STATED'
    },
    {
      id: 'tv-sony-bravia-65',
      canonicalProductId: 'sony-bravia-65-inch-4k-ultra-hd-kd-65x74l',
      name: 'Sony Bravia 65 Inch 4K Ultra HD Smart LED Google TV (KD-65X74L, Live Colour)',
      brand: 'Sony',
      model: 'Bravia 65 4K Ultra HD',
      variant: '65 Inch 4K Black',
      category: 'tvs',
      price: 74990,
      originalPrice: 139900,
      discountPercentage: 46,
      currency: 'INR',
      rating: 4.8,
      reviewCount: 1600,
      axevoraScore: 9.5,
      scoreLabel: 'Grand Living Room Immersion',
      badge: 'Editor Choice',
      specs: {
        processor: 'Sony X1 4K Processor',
        display: '65" 4K Ultra HD (3840x2160) Motionflow XR 100',
        os: 'Google TV with Apple AirPlay & HomeKit'
      },
      whyWeLikeIt: 'Massive 65-inch cinema canvas with Sony legendary picture processing algorithms.',
      bestFor: 'Large Living Rooms, 4K Blu-ray Movies & Sports',
      tradeOff: 'Requires substantial wall clearance.',
      merchantName: 'Amazon',
      merchantLogoUrl: 'https://www.google.com/s2/favicons?domain=amazon.in&sz=64',
      dealUrl: 'https://www.amazon.in/s?k=Sony+Bravia+65+inch+4K+TV&tag=axevora06-21',
      imageUrl: 'https://m.media-amazon.com/images/I/81G7HkMBe1L._SX679_.jpg',
      canonicalImage: 'https://m.media-amazon.com/images/I/81G7HkMBe1L._SX679_.jpg',
      imageSourceDomain: 'sony.com / amazon.in',
      imageConfidence: 1.0,
      dealType: 'PRODUCT_DEAL',
      verificationStatus: 'SOURCE_STATED'
    },
    {
      id: 'tv-samsung-crystal-43',
      canonicalProductId: 'samsung-43-inch-crystal-4k-vivid-ultra-hd-smart-tv',
      name: 'Samsung 43 Inch Crystal 4K Vivid Pro Ultra HD Smart TV (PurColor, HDR 10+)',
      brand: 'Samsung',
      model: '43 Crystal 4K Vivid',
      variant: '43 Inch 4K Black',
      category: 'tvs',
      price: 28990,
      originalPrice: 44900,
      discountPercentage: 35,
      currency: 'INR',
      rating: 4.4,
      reviewCount: 6500,
      axevoraScore: 9.0,
      scoreLabel: 'Crystal Clear Definition',
      specs: {
        processor: 'Crystal Processor 4K',
        display: '43" 4K Ultra HD with PurColor & Mega Contrast',
        os: 'Samsung Tizen OS with IoT Hub'
      },
      whyWeLikeIt: 'Crystal Processor 4K upscale engine with PurColor vibrancy in a compact 43-inch size.',
      bestFor: 'Bedrooms, Study Rooms & Apartments',
      tradeOff: '20W speaker system.',
      merchantName: 'Amazon',
      merchantLogoUrl: 'https://www.google.com/s2/favicons?domain=amazon.in&sz=64',
      dealUrl: 'https://www.amazon.in/s?k=Samsung+43+inch+Crystal+4K+TV&tag=axevora06-21',
      imageUrl: 'https://m.media-amazon.com/images/I/81o7aCBnHQL._SX679_.jpg',
      canonicalImage: 'https://m.media-amazon.com/images/I/81o7aCBnHQL._SX679_.jpg',
      imageSourceDomain: 'samsung.com / amazon.in',
      imageConfidence: 1.0,
      dealType: 'PRODUCT_DEAL',
      verificationStatus: 'SOURCE_STATED'
    },
    {
      id: 'tv-lg-55-nano',
      canonicalProductId: 'lg-55-inch-4k-nanocell-ai-thinq-smart-tv',
      name: 'LG 55 Inch 4K NanoCell Smart TV (Nano Color, α5 AI Processor Gen6, WebOS)',
      brand: 'LG',
      model: '55 4K NanoCell AI',
      variant: '55 Inch 4K Dark Titan',
      category: 'tvs',
      price: 47990,
      originalPrice: 79990,
      discountPercentage: 40,
      currency: 'INR',
      rating: 4.5,
      reviewCount: 3400,
      axevoraScore: 9.2,
      scoreLabel: 'Pure Nano Colors',
      specs: {
        processor: 'α5 AI Processor 4K Gen6',
        display: '55" 4K NanoCell Real 4K with Local Dimming',
        os: 'LG WebOS 23 with Magic Remote'
      },
      whyWeLikeIt: 'NanoCell pure wavelength filtering delivers exceptionally accurate, rich color tones.',
      bestFor: 'Wide Seating Angles, Magic Remote Navigation & HDR Streaming',
      tradeOff: 'Native 60Hz panel.',
      merchantName: 'Amazon',
      merchantLogoUrl: 'https://www.google.com/s2/favicons?domain=amazon.in&sz=64',
      dealUrl: 'https://www.amazon.in/s?k=LG+55+inch+NanoCell+4K+TV&tag=axevora06-21',
      imageUrl: 'https://m.media-amazon.com/images/I/81Ws1OwXz1L._SX679_.jpg',
      canonicalImage: 'https://m.media-amazon.com/images/I/81Ws1OwXz1L._SX679_.jpg',
      imageSourceDomain: 'lg.com / amazon.in',
      imageConfidence: 1.0,
      dealType: 'PRODUCT_DEAL',
      verificationStatus: 'SOURCE_STATED'
    },
    {
      id: 'tv-tcl-55-qled',
      canonicalProductId: 'tcl-55-inch-metallic-qled-4k-google-tv',
      name: 'TCL 55 Inch Metallic Bezel-Less QLED 4K Google TV (Dolby Vision Atmos, 120Hz DLG)',
      brand: 'TCL',
      model: '55 Metallic QLED 4K',
      variant: '55 Inch 4K Metallic Gray',
      category: 'tvs',
      price: 34990,
      originalPrice: 61990,
      discountPercentage: 44,
      currency: 'INR',
      rating: 4.4,
      reviewCount: 4100,
      axevoraScore: 9.1,
      scoreLabel: 'High-Value QLED Hero',
      badge: 'Best Value',
      specs: {
        processor: 'AiPQ Engine 3.0',
        display: '55" 4K QLED Quantum Dot (Dolby Vision, 120Hz Game Accelerator)',
        os: 'Google TV with Hands-Free Voice Control'
      },
      whyWeLikeIt: 'Quantum Dot color with Dolby Vision and 120Hz DLG gaming accelerator under ₹35,000.',
      bestFor: 'Gaming Consoles, Dolby Vision Cinema & Bright Rooms',
      tradeOff: 'Sound stage lacks deep sub-bass.',
      merchantName: 'Amazon',
      merchantLogoUrl: 'https://www.google.com/s2/favicons?domain=amazon.in&sz=64',
      dealUrl: 'https://www.amazon.in/s?k=TCL+55+inch+QLED+4K+TV&tag=axevora06-21',
      imageUrl: 'https://m.media-amazon.com/images/I/81tilPzs7sL._SX679_.jpg',
      canonicalImage: 'https://m.media-amazon.com/images/I/81tilPzs7sL._SX679_.jpg',
      imageSourceDomain: 'tcl.com / amazon.in',
      imageConfidence: 1.0,
      dealType: 'PRODUCT_DEAL',
      verificationStatus: 'SOURCE_STATED'
    },
    {
      id: 'tv-xiaomi-55-x',
      canonicalProductId: 'xiaomi-55-inch-x-pro-4k-dolby-vision-google-tv',
      name: 'Xiaomi 55 Inch X Pro 4K Ultra HD Smart Google TV (Dolby Vision IQ, 30W Speaker)',
      brand: 'Xiaomi',
      model: '55 X Pro 4K Dolby Vision',
      variant: '55 Inch 4K Metal Bezel',
      category: 'tvs',
      price: 39999,
      originalPrice: 54999,
      discountPercentage: 27,
      currency: 'INR',
      rating: 4.4,
      reviewCount: 5200,
      axevoraScore: 9.0,
      scoreLabel: 'Smart Home Powerhouse',
      specs: {
        processor: 'Quad Core A55 with Vivid Picture Engine 2',
        display: '55" 4K Dolby Vision IQ (94% DCI-P3 Wide Color)',
        os: 'Google TV with PatchWall+'
      },
      whyWeLikeIt: 'Dolby Vision IQ auto-adapts brightness to ambient room light with powerful 30W speakers.',
      bestFor: 'PatchWall Content Discovery & Smart Home Integration',
      tradeOff: 'Default picture mode requires minor custom tuning.',
      merchantName: 'Amazon',
      merchantLogoUrl: 'https://www.google.com/s2/favicons?domain=amazon.in&sz=64',
      dealUrl: 'https://www.amazon.in/s?k=Xiaomi+55+inch+X+Pro+4K+TV&tag=axevora06-21',
      imageUrl: 'https://m.media-amazon.com/images/I/71L7RuOcDjL._SX679_.jpg',
      canonicalImage: 'https://m.media-amazon.com/images/I/71L7RuOcDjL._SX679_.jpg',
      imageSourceDomain: 'mi.com / amazon.in',
      imageConfidence: 1.0,
      dealType: 'PRODUCT_DEAL',
      verificationStatus: 'SOURCE_STATED'
    },
    {
      id: 'tv-acer-55-i',
      canonicalProductId: 'acer-55-inch-advanced-i-series-4k-google-tv',
      name: 'Acer 55 Inch Advanced I Series 4K Ultra HD Smart LED Google TV (Frameless, MEMC)',
      brand: 'Acer',
      model: '55 Advanced I Series 4K',
      variant: '55 Inch 4K Black',
      category: 'tvs',
      price: 32999,
      originalPrice: 59999,
      discountPercentage: 45,
      currency: 'INR',
      rating: 4.3,
      reviewCount: 3800,
      axevoraScore: 8.8,
      scoreLabel: 'Budget Big Screen',
      specs: {
        processor: '64-Bit Quad Core with Intelligent Frame Stabilization',
        display: '55" 4K Ultra HD HDR10 with Micro Dimming',
        os: 'Google TV with Dual Band Wi-Fi'
      },
      whyWeLikeIt: 'Frameless edge design with MEMC motion smoothing at an aggressive under-₹33k price point.',
      bestFor: 'Budget Big-Screen Buyers & Casual Gaming',
      tradeOff: 'Peak HDR brightness is modest for direct sunlit rooms.',
      merchantName: 'Amazon',
      merchantLogoUrl: 'https://www.google.com/s2/favicons?domain=amazon.in&sz=64',
      dealUrl: 'https://www.amazon.in/s?k=Acer+55+inch+4K+TV&tag=axevora06-21',
      imageUrl: 'https://m.media-amazon.com/images/I/71liWUIukCL._SX679_.jpg',
      canonicalImage: 'https://m.media-amazon.com/images/I/71liWUIukCL._SX679_.jpg',
      imageSourceDomain: 'acer.com / amazon.in',
      imageConfidence: 1.0,
      dealType: 'PRODUCT_DEAL',
      verificationStatus: 'SOURCE_STATED'
    }
  ],

  audio: [
    {
      id: 'aud-sony-xm5',
      canonicalProductId: 'sony-wh-1000xm5-wireless-anc-black',
      name: 'Sony WH-1000XM5 Wireless Industry-Leading Active Noise Cancelling Headphones (30hr Battery, LDAC)',
      brand: 'Sony',
      model: 'WH-1000XM5 ANC',
      variant: 'Black Over-Ear',
      category: 'audio',
      price: 26990,
      originalPrice: 34990,
      discountPercentage: 23,
      currency: 'INR',
      rating: 4.7,
      reviewCount: 7800,
      axevoraScore: 9.6,
      scoreLabel: 'ANC Benchmark',
      badge: 'Best Overall',
      specs: {
        processor: 'Integrated V1 + HD QN1 Processor',
        battery: '30 Hours with ANC (40 Hours without)',
        camera: '8-Microphone Array for Crystal Clear Calls',
        os: 'Sony Headphones Connect App (LDAC Hi-Res Audio)'
      },
      whyWeLikeIt: 'Unrivaled noise cancellation algorithms with 8 microphones and plush featherlight comfort.',
      bestFor: 'Frequent Flyers, Office Workers, Audiophiles & Commuters',
      tradeOff: 'Earcups do not fold inward like the older XM4.',
      merchantName: 'Amazon',
      merchantLogoUrl: 'https://www.google.com/s2/favicons?domain=amazon.in&sz=64',
      dealUrl: 'https://www.amazon.in/s?k=Sony+WH-1000XM5&tag=axevora06-21',
      imageUrl: 'https://m.media-amazon.com/images/I/51SKmu2G9FL._SX679_.jpg',
      canonicalImage: 'https://m.media-amazon.com/images/I/51SKmu2G9FL._SX679_.jpg',
      imageSourceDomain: 'sony.com / amazon.in',
      imageConfidence: 1.0,
      dealType: 'PRODUCT_DEAL',
      verificationStatus: 'SOURCE_STATED'
    },
    {
      id: 'aud-airpods-pro-2',
      canonicalProductId: 'apple-airpods-pro-2nd-gen-usb-c',
      name: 'Apple AirPods Pro (2nd Gen) with USB-C Charging Case (Active Noise Cancellation, Spatial Audio)',
      brand: 'Apple',
      model: 'AirPods Pro 2',
      variant: 'USB-C White',
      category: 'audio',
      price: 21990,
      originalPrice: 24900,
      discountPercentage: 12,
      currency: 'INR',
      rating: 4.8,
      reviewCount: 12400,
      axevoraScore: 9.7,
      scoreLabel: 'TWS Pinnacle',
      badge: 'Editor Choice',
      specs: {
        processor: 'Apple H2 Headphone Chip + U1 Case Chip',
        battery: '6 Hours per charge (30 Hours with MagSafe Case)',
        os: 'iOS / iPadOS / macOS Seamless Ecosystem Switching'
      },
      whyWeLikeIt: 'Up to 2x more active noise cancellation with groundbreaking Adaptive Audio and personalized spatial audio.',
      bestFor: 'iPhone/Mac Users, Gym Workouts, Calls & Travel',
      tradeOff: 'Full feature set requires Apple ecosystem hardware.',
      merchantName: 'Amazon',
      merchantLogoUrl: 'https://www.google.com/s2/favicons?domain=amazon.in&sz=64',
      dealUrl: 'https://www.amazon.in/s?k=AirPods+Pro+2+USB-C&tag=axevora06-21',
      imageUrl: 'https://m.media-amazon.com/images/I/61SUj2aKoEL._SX679_.jpg',
      canonicalImage: 'https://m.media-amazon.com/images/I/61SUj2aKoEL._SX679_.jpg',
      imageSourceDomain: 'apple.com / amazon.in',
      imageConfidence: 1.0,
      dealType: 'PRODUCT_DEAL',
      verificationStatus: 'SOURCE_STATED'
    },
    {
      id: 'aud-bose-qc45',
      canonicalProductId: 'bose-quietcomfort-45-wireless-noise-cancelling-black',
      name: 'Bose QuietComfort 45 Bluetooth Wireless Noise Cancelling Headphones (TriPort Acoustics)',
      brand: 'Bose',
      model: 'QuietComfort 45',
      variant: 'Triple Black',
      category: 'audio',
      price: 24990,
      originalPrice: 32900,
      discountPercentage: 24,
      currency: 'INR',
      rating: 4.6,
      reviewCount: 6500,
      axevoraScore: 9.4,
      scoreLabel: 'Supreme Ergonomic Comfort',
      specs: {
        processor: 'Bose Acoustic Noise Cancelling Architecture',
        battery: '24 Hours on a Single Charge',
        os: 'Bose Music App (Custom Equalizer)'
      },
      whyWeLikeIt: 'World-renowned Bose plush ear cushion comfort and classic foldable travel form factor.',
      bestFor: 'Long Haul Flights, Deep Focus & Extended Wearing',
      tradeOff: 'No auto-pause sensor when removing headphones.',
      merchantName: 'Amazon',
      merchantLogoUrl: 'https://www.google.com/s2/favicons?domain=amazon.in&sz=64',
      dealUrl: 'https://www.amazon.in/s?k=Bose+QuietComfort+45&tag=axevora06-21',
      imageUrl: 'https://m.media-amazon.com/images/I/51JbsHSktkL._SX679_.jpg',
      canonicalImage: 'https://m.media-amazon.com/images/I/51JbsHSktkL._SX679_.jpg',
      imageSourceDomain: 'bose.com / amazon.in',
      imageConfidence: 1.0,
      dealType: 'PRODUCT_DEAL',
      verificationStatus: 'SOURCE_STATED'
    },
    {
      id: 'aud-sony-ch520',
      canonicalProductId: 'sony-wh-ch520-wireless-bluetooth-headphones-50hr',
      name: 'Sony WH-CH520 Wireless Bluetooth On-Ear Headphones (50hr Battery, Multipoint)',
      brand: 'Sony',
      model: 'WH-CH520 Wireless',
      variant: 'Beige On-Ear',
      category: 'audio',
      price: 4490,
      originalPrice: 5990,
      discountPercentage: 25,
      currency: 'INR',
      rating: 4.5,
      reviewCount: 14200,
      axevoraScore: 9.1,
      scoreLabel: '50-Hour Battery Champ',
      badge: 'Best Value',
      specs: {
        processor: 'DSEE Sound Enhancement Engine',
        battery: '50 Hours Battery (3 min charge = 1.5 hr playback)',
        os: 'Sony Headphones Connect App'
      },
      whyWeLikeIt: 'Incredible 50-hour battery life with multipoint Bluetooth dual-device pairing under ₹4,500.',
      bestFor: 'Online Classes, Daily Commute & Marathon Listening',
      tradeOff: 'No active noise cancellation (passive isolation only).',
      merchantName: 'Amazon',
      merchantLogoUrl: 'https://www.google.com/s2/favicons?domain=amazon.in&sz=64',
      dealUrl: 'https://www.amazon.in/s?k=Sony+WH-CH520&tag=axevora06-21',
      imageUrl: 'https://m.media-amazon.com/images/I/41lArSiD5hL._SX679_.jpg',
      canonicalImage: 'https://m.media-amazon.com/images/I/41lArSiD5hL._SX679_.jpg',
      imageSourceDomain: 'sony.com / amazon.in',
      imageConfidence: 1.0,
      dealType: 'PRODUCT_DEAL',
      verificationStatus: 'SOURCE_STATED'
    },
    {
      id: 'aud-boat-450',
      canonicalProductId: 'boat-rockerz-450-bluetooth-on-ear-headphones-40mm',
      name: 'boAt Rockerz 450 Bluetooth On-Ear Headphones (40mm Drivers, 15hr Playback, Mic)',
      brand: 'boAt',
      model: 'Rockerz 450 Bluetooth',
      variant: 'Luscious Black',
      category: 'audio',
      price: 1499,
      originalPrice: 3990,
      discountPercentage: 62,
      currency: 'INR',
      rating: 4.2,
      reviewCount: 48000,
      axevoraScore: 8.7,
      scoreLabel: 'Budget Bass King',
      badge: 'Best Value',
      specs: {
        processor: '40mm Dynamic Bass Drivers',
        battery: '15 Hours Non-Stop Playback (300 mAh)',
        os: 'Dual Modes: Bluetooth 5.0 + 3.5mm AUX Cable'
      },
      whyWeLikeIt: 'Punchy bass response with foldable earcups and dual Bluetooth/AUX modes under ₹1,500.',
      bestFor: 'Bass Lovers, Casual Music & Budget Gifts',
      tradeOff: 'On-ear clamping force can feel tight after 2 hours.',
      merchantName: 'Amazon',
      merchantLogoUrl: 'https://www.google.com/s2/favicons?domain=amazon.in&sz=64',
      dealUrl: 'https://www.amazon.in/s?k=boAt+Rockerz+450&tag=axevora06-21',
      imageUrl: 'https://m.media-amazon.com/images/I/51xxA+6E+xL._SX679_.jpg',
      canonicalImage: 'https://m.media-amazon.com/images/I/51xxA+6E+xL._SX679_.jpg',
      imageSourceDomain: 'boat-lifestyle.com / amazon.in',
      imageConfidence: 1.0,
      dealType: 'PRODUCT_DEAL',
      verificationStatus: 'SOURCE_STATED'
    },
    {
      id: 'aud-airpods-2',
      canonicalProductId: 'apple-airpods-2nd-generation-with-charging-case',
      name: 'Apple AirPods (2nd Gen) with Lightning Charging Case (H1 Headphone Chip)',
      brand: 'Apple',
      model: 'AirPods 2nd Gen',
      variant: 'Glossy White',
      category: 'audio',
      price: 8999,
      originalPrice: 12900,
      discountPercentage: 30,
      currency: 'INR',
      rating: 4.6,
      reviewCount: 28000,
      axevoraScore: 9.0,
      scoreLabel: 'Classic Earbud Fit',
      specs: {
        processor: 'Apple H1 Headphone Chip',
        battery: 'Up to 24 Hours with Case (5 Hours Per Charge)',
        os: 'Universal Apple Ecosystem Auto-Switching'
      },
      whyWeLikeIt: 'Comfortable non-intrusive open-ear fit with instantaneous Apple device switching.',
      bestFor: 'Voice Calls, Walking & Users who dislike silicone ear tips',
      tradeOff: 'Open-ear design has no active noise cancellation.',
      merchantName: 'Amazon',
      merchantLogoUrl: 'https://www.google.com/s2/favicons?domain=amazon.in&sz=64',
      dealUrl: 'https://www.amazon.in/s?k=AirPods+2nd+Gen&tag=axevora06-21',
      imageUrl: 'https://m.media-amazon.com/images/I/7120GgUKj3L._SX679_.jpg',
      canonicalImage: 'https://m.media-amazon.com/images/I/7120GgUKj3L._SX679_.jpg',
      imageSourceDomain: 'apple.com / amazon.in',
      imageConfidence: 1.0,
      dealType: 'PRODUCT_DEAL',
      verificationStatus: 'SOURCE_STATED'
    },
    {
      id: 'aud-realme-t300',
      canonicalProductId: 'realme-buds-t300-tws-30db-anc-12-4mm-bass-driver',
      name: 'Realme Buds T300 TWS Earbuds (30dB Active Noise Cancellation, 12.4mm Bass, 40hr)',
      brand: 'Realme',
      model: 'Buds T300 TWS ANC',
      variant: 'Stylish Black',
      category: 'audio',
      price: 2199,
      originalPrice: 3999,
      discountPercentage: 45,
      currency: 'INR',
      rating: 4.4,
      reviewCount: 9400,
      axevoraScore: 8.9,
      scoreLabel: 'Best Budget ANC Earbuds',
      badge: 'Best Value',
      specs: {
        processor: '12.4mm Dynamic Bass Driver + 30dB ANC Chip',
        battery: '40 Hours Total Playback + 10 min Fast Charge = 7 hrs',
        os: 'Realme Link App (360 Spatial Audio Effect)'
      },
      whyWeLikeIt: 'Genuine 30dB active noise cancellation with 12.4mm titanium drivers under ₹2,200.',
      bestFor: 'Daily Commuters, Gym Workouts & Gaming Low Latency',
      tradeOff: 'App customization requires Realme Link login.',
      merchantName: 'Amazon',
      merchantLogoUrl: 'https://www.google.com/s2/favicons?domain=amazon.in&sz=64',
      dealUrl: 'https://www.amazon.in/s?k=Realme+Buds+T300&tag=axevora06-21',
      imageUrl: 'https://m.media-amazon.com/images/I/51jRz0A831L._SL1300_.jpg',
      canonicalImage: 'https://m.media-amazon.com/images/I/51jRz0A831L._SL1300_.jpg',
      imageSourceDomain: 'realme.com / amazon.in',
      imageConfidence: 1.0,
      dealType: 'PRODUCT_DEAL',
      verificationStatus: 'SOURCE_STATED'
    },
    {
      id: 'aud-jbl-quant100',
      canonicalProductId: 'jbl-quantum-100-wired-over-ear-gaming-headphones',
      name: 'JBL Quantum 100 Wired Over-Ear Gaming Headphones with Detachable Mic (40mm)',
      brand: 'JBL',
      model: 'Quantum 100 Gaming Headset',
      variant: 'Black Over-Ear',
      category: 'audio',
      price: 2199,
      originalPrice: 3999,
      discountPercentage: 45,
      currency: 'INR',
      rating: 4.3,
      reviewCount: 16500,
      axevoraScore: 8.8,
      scoreLabel: 'Top Budget Gaming Headset',
      specs: {
        processor: 'JBL QuantumSOUND Signature 40mm Drivers',
        battery: 'Wired 3.5mm (Zero Latency, No Battery Needed)',
        os: 'Universal PC / PS5 / Xbox / Mobile Compatibility'
      },
      whyWeLikeIt: 'Zero latency spatial audio with directional detachable boom microphone and memory foam cushions.',
      bestFor: 'PC/Console Gamers, Discord Chats & Streaming',
      tradeOff: 'Wired 3.5mm connection only (no Bluetooth).',
      merchantName: 'Amazon',
      merchantLogoUrl: 'https://www.google.com/s2/favicons?domain=amazon.in&sz=64',
      dealUrl: 'https://www.amazon.in/s?k=JBL+Quantum+100&tag=axevora06-21',
      imageUrl: 'https://m.media-amazon.com/images/I/61jzBZHmO3L._SL1500_.jpg',
      canonicalImage: 'https://m.media-amazon.com/images/I/61jzBZHmO3L._SL1500_.jpg',
      imageSourceDomain: 'jbl.com / amazon.in',
      imageConfidence: 1.0,
      dealType: 'PRODUCT_DEAL',
      verificationStatus: 'SOURCE_STATED'
    },
    {
      id: 'aud-sony-zx110a',
      canonicalProductId: 'sony-mdr-zx110a-wired-on-ear-headphones-white',
      name: 'Sony MDR-ZX110A Wired On-Ear Headphones (30mm Neodymium Drivers, Foldable)',
      brand: 'Sony',
      model: 'MDR-ZX110A Wired On-Ear',
      variant: 'Pure White',
      category: 'audio',
      price: 899,
      originalPrice: 1490,
      discountPercentage: 40,
      currency: 'INR',
      rating: 4.3,
      reviewCount: 38000,
      axevoraScore: 8.7,
      scoreLabel: 'Best Under ₹1,000',
      badge: 'Best Value',
      specs: {
        processor: '30mm Dynamic Dome Drivers',
        battery: 'Wired 3.5mm Gold Plated L-Shaped Plug',
        os: 'Universal 3.5mm Analog Audio'
      },
      whyWeLikeIt: 'Lightweight 120g swivel folding earcups with clean acoustic sound under ₹1,000.',
      bestFor: 'Students, Desktop Audio & Budget Backup',
      tradeOff: 'No in-line microphone on the 110A base model.',
      merchantName: 'Amazon',
      merchantLogoUrl: 'https://www.google.com/s2/favicons?domain=amazon.in&sz=64',
      dealUrl: 'https://www.amazon.in/s?k=Sony+MDR-ZX110A&tag=axevora06-21',
      imageUrl: 'https://m.media-amazon.com/images/I/41BoLKMYjnL._SL1128_.jpg',
      canonicalImage: 'https://m.media-amazon.com/images/I/41BoLKMYjnL._SL1128_.jpg',
      imageSourceDomain: 'sony.com / amazon.in',
      imageConfidence: 1.0,
      dealType: 'PRODUCT_DEAL',
      verificationStatus: 'SOURCE_STATED'
    },
    {
      id: 'aud-jbl-c100si',
      canonicalProductId: 'jbl-c100si-in-ear-headphones-with-mic-deep-bass',
      name: 'JBL C100SI Wired In-Ear Headphones with Mic (Pure Bass Sound, 3.5mm Gold Plug)',
      brand: 'JBL',
      model: 'C100SI In-Ear Wired',
      variant: 'Black In-Ear',
      category: 'audio',
      price: 599,
      originalPrice: 1299,
      discountPercentage: 54,
      currency: 'INR',
      rating: 4.2,
      reviewCount: 96000,
      axevoraScore: 8.6,
      scoreLabel: 'Legendary Earphone Value',
      specs: {
        processor: '9mm Dynamic Drivers with Signature JBL Bass',
        battery: 'Wired 3.5mm Gold Plated Jack',
        os: 'One-Button Universal Remote with Microphone'
      },
      whyWeLikeIt: 'Over 90,000 positive ratings for comfortable angled acoustic tips and deep sub-bass.',
      bestFor: 'Everyday Phone Calls, Podcasts & Casual Listening',
      tradeOff: 'Thin cable requires mindful handling.',
      merchantName: 'Amazon',
      merchantLogoUrl: 'https://www.google.com/s2/favicons?domain=amazon.in&sz=64',
      dealUrl: 'https://www.amazon.in/s?k=JBL+C100SI&tag=axevora06-21',
      imageUrl: 'https://m.media-amazon.com/images/I/51Q8DUDT2eL._SL1500_.jpg',
      canonicalImage: 'https://m.media-amazon.com/images/I/51Q8DUDT2eL._SL1500_.jpg',
      imageSourceDomain: 'jbl.com / amazon.in',
      imageConfidence: 1.0,
      dealType: 'PRODUCT_DEAL',
      verificationStatus: 'SOURCE_STATED'
    }
  ]
};

/**
 * Deterministic date string in Asia/Kolkata (IST).
 */
function getTodayIST(): string {
  const formatter = new Intl.DateTimeFormat('en-CA', {
    timeZone: 'Asia/Kolkata',
    year: 'numeric',
    month: '2-digit',
    day: '2-digit'
  });
  return formatter.format(new Date());
}

/**
 * Deterministic pseudo-random number generator seeded by date string.
 */
function getDateSeed(dateStr: string): number {
  let hash = 0;
  for (let i = 0; i < dateStr.length; i++) {
    const char = dateStr.charCodeAt(i);
    hash = ((hash << 5) - hash) + char;
    hash |= 0;
  }
  return Math.abs(hash);
}

/**
 * Deterministically select exactly 10 distinct products for a given date.
 */
export function getDailyCuratedProductsForDate(category: string, dateStr: string): DailyProduct[] {
  const pool = MASTER_CANDIDATE_POOL[category.toLowerCase()] || [];
  if (pool.length <= 10) {
    return pool.slice(0, 10);
  }

  const seed = getDateSeed(`${dateStr}-${category}`);
  const rotated = [...pool];
  
  // Deterministic Fisher-Yates shuffle with seed
  for (let i = rotated.length - 1; i > 0; i--) {
    const j = Math.floor(((seed * (i + 1) * 9301 + 49297) % 233280) / 233280 * (i + 1));
    const temp = rotated[i];
    rotated[i] = rotated[j];
    rotated[j] = temp;
  }

  return rotated.slice(0, 10);
}

export const onRequestGet: PagesFunction = async (context) => {
  const { request } = context;
  const url = new URL(request.url);
  const reqCategory = (url.searchParams.get('category') || 'all').toLowerCase();
  const reqDate = url.searchParams.get('date') || getTodayIST();
  const page = parseInt(url.searchParams.get('page') || '1', 10);
  const pageSize = parseInt(url.searchParams.get('pageSize') || '10', 10);

  const categories = ['tablets', 'laptops', 'phones', 'tvs', 'audio'];
  const snapshotData: Record<string, DailyProduct[]> = {};

  categories.forEach((cat) => {
    snapshotData[cat] = getDailyCuratedProductsForDate(cat, reqDate);
  });

  if (reqCategory !== 'all' && categories.includes(reqCategory)) {
    const categoryProducts = snapshotData[reqCategory] || [];
    const total = categoryProducts.length;
    const startIndex = (page - 1) * pageSize;
    const paginatedProducts = categoryProducts.slice(startIndex, startIndex + pageSize);

    return new Response(JSON.stringify({
      ok: true,
      success: true,
      date: reqDate,
      timezone: 'Asia/Kolkata',
      category: reqCategory,
      total,
      page,
      pageSize,
      totalPages: Math.ceil(total / pageSize),
      data: paginatedProducts,
      categories: snapshotData
    }), {
      headers: {
        'Content-Type': 'application/json',
        'Cache-Control': 'public, max-age=3600, s-maxage=86400',
        'Access-Control-Allow-Origin': '*'
      }
    });
  }

  return new Response(JSON.stringify({
    ok: true,
    success: true,
    date: reqDate,
    timezone: 'Asia/Kolkata',
    category: 'all',
    totalCategories: categories.length,
    totalProducts: Object.values(snapshotData).reduce((sum, list) => sum + list.length, 0),
    data: snapshotData['tablets'] || [],
    categories: snapshotData
  }), {
    headers: {
      'Content-Type': 'application/json',
      'Cache-Control': 'public, max-age=3600, s-maxage=86400',
      'Access-Control-Allow-Origin': '*'
    }
  });
};
